ExtLP: ExtVector Class Reference
ExtVector Class Reference
Detailed Description
Cache is allocated on per vector basis Always remember to allocate and deallocate cache pages as necessary.
Definition at line 18 of file ExtVector.h.
Public Types
typedef item_vector::iterator iterator
Allowing iterator of item_vector for access.
Public Member Functions
ExtVector ()
Forced Initialization with default values Need to use it only when necessary.
ExtVector (PackedVector &packedVector)
Simple initialization from the input packed.
void add (unsigned int index, double value)
Adds the input element at the input index position.
void allocate_cache ()
Allocates the 16MB cache desired by an individual vector.
iterator begin ()
Returns iterator to the beginning(first) element in the vector.
void deallocate_cache ()
Deallocates all the cache pertaining to this vector.
iterator end ()
Returns iterator to the ending(last) of the vector.
float get_sparsity ()
Returns the sparsity of the vector.
unsigned int nnz ()
Return the number of non zeros.
double operator[] (const unsigned int index) const
Simple access to the element at index position Always preferably use the iterator instead for better performance.
void resize (unsigned int p_size, bool p_allow_shrink=true)
Resizes the vector, also has an option to shrink_necessary.
unsigned int size ()
Return the number actual size of the vector.
void storeFromPackedVector (PackedVector &packedVector)
Storing from PackedVector.
Private Types
typedef VECTOR_GENERATOR
< double, 1, 1, 6 *8 *1024 >
::result item_vector
Vector to store the Items onto external memory template parameters<ValueType, PageSize, CachePages, BlockSize, AllocStratg>
typedef item_vector::iterator iterator_type
Private Attributes
unsigned int m_nnz
Total number of non zeros in the vector.
unsigned int m_size
Total number of elements without compaction/compression.
item_vector m_vct_disk
Member Typedef Documentation
typedef VECTOR_GENERATOR< double , 1, 1, 6*8*1024 >::result ExtVector::item_vector [private]
Vector to store the Items onto external memory template parameters<ValueType, PageSize, CachePages, BlockSize, AllocStratg>
Definition at line 22 of file ExtVector.h.
typedef item_vector::iterator ExtVector::iterator
Allowing iterator of item_vector for access.
Definition at line 35 of file ExtVector.h.
typedef item_vector::iterator ExtVector::iterator_type [private]
Definition at line 23 of file ExtVector.h.
Constructor & Destructor Documentation
ExtVector::ExtVector () [inline]
Forced Initialization with default values Need to use it only when necessary.
Definition at line 39 of file ExtVector.h.
ExtVector::ExtVector (PackedVector & packedVector) [inline]
Simple initialization from the input packed.
Definition at line 42 of file ExtVector.h.
References storeFromPackedVector().
Member Function Documentation
void ExtVector::add (unsigned int index, double value) [inline]
Adds the input element at the input index position.
Definition at line 58 of file ExtVector.h.
References m_size, and m_vct_disk.
Referenced by Test::testExtVector().
void ExtVector::allocate_cache () [inline]
Allocates the 16MB cache desired by an individual vector.
Definition at line 81 of file ExtVector.h.
References m_vct_disk.
Referenced by Test::testExtVector().
iterator ExtVector::begin () [inline]
Returns iterator to the beginning(first) element in the vector.
Definition at line 89 of file ExtVector.h.
References m_vct_disk.
void ExtVector::deallocate_cache () [inline]
Deallocates all the cache pertaining to this vector.
Definition at line 85 of file ExtVector.h.
References m_vct_disk.
Referenced by storeFromPackedVector(), and Test::testExtVector().
iterator ExtVector::end () [inline]
Returns iterator to the ending(last) of the vector.
Definition at line 93 of file ExtVector.h.
References m_vct_disk.
float ExtVector::get_sparsity () [inline]
Returns the sparsity of the vector.
Definition at line 97 of file ExtVector.h.
References m_nnz, and m_size.
unsigned int ExtVector::nnz () [inline]
Return the number of non zeros.
Definition at line 68 of file ExtVector.h.
References m_nnz.
double ExtVector::operator[] (const unsigned int index) const [inline]
Simple access to the element at index position Always preferably use the iterator instead for better performance.
Definition at line 77 of file ExtVector.h.
References m_vct_disk.
void ExtVector::resize (unsigned int p_size, bool p_allow_shrink = true) [inline]
Resizes the vector, also has an option to shrink_necessary.
Definition at line 63 of file ExtVector.h.
References m_size, and m_vct_disk.
Referenced by Test::testExtVector().
unsigned int ExtVector::size () [inline]
Return the number actual size of the vector.
Definition at line 72 of file ExtVector.h.
References m_size.
void ExtVector::storeFromPackedVector (PackedVector & packedVector) [inline]
Storing from PackedVector.
Definition at line 46 of file ExtVector.h.
References PackedVector< ItemClass >::begin(), deallocate_cache(), PackedVector< ItemClass >::end(), PackedElement< ItemClass >::get_index(), PackedVector< ItemClass >::get_real_size(), PackedElement< ItemClass >::get_value(), and m_vct_disk.
Referenced by ExtVector().
Member Data Documentation
unsigned int ExtVector::m_nnz [private]
Total number of non zeros in the vector.
Definition at line 26 of file ExtVector.h.
Referenced by get_sparsity(), and nnz().
unsigned int ExtVector::m_size [private]
Total number of elements without compaction/compression.
Definition at line 28 of file ExtVector.h.
Referenced by add(), get_sparsity(), resize(), and size().
item_vector ExtVector::m_vct_disk [private]
Definition at line 24 of file ExtVector.h.
Referenced by add(), allocate_cache(), begin(), deallocate_cache(), end(), operator[](), resize(), and storeFromPackedVector().
The documentation for this class was generated from the following file:
local/deprecated/ExtVector.h