ExtLP: vector_bufreader_reverse< VectorIterator > Class Template Reference
vector_bufreader_reverse< VectorIterator > Class Template Reference
vector
Detailed Description
template<typename VectorIterator>
class vector_bufreader_reverse< VectorIterator >
Buffered sequential reverse reader from a vector using overlapped I/O.
This buffered reader can be used to read a large sequential region of a vector _in_reverse_ using overlapped I/O. The object is created from an iterator range, which can then be read to using operator<<(), or with operator*() and operator++(), where ++ actually goes to the preceding element.
The interface also fulfills all requirements of a stream. Actually most of the code is identical to stream::vector_iterator2stream.
Note that this buffered reader is inefficient for reading small ranges. This is intentional, as one can just use operator[] on the vector for that.
See Efficient Sequential Reading and Writing to Vectors
Definition at line 1913 of file ExtStxxlVector.h.
Public Types
typedef
vector_iterator::bids_container_iterator bids_container_iterator
block identifier iterator of the vector
typedef vector_iterator::block_type block_type
block type used in the vector
typedef
stxxl::buf_istream_reverse
< block_type,
bids_container_iterator > buf_istream_type
construct output buffered stream used for overlapped reading
typedef vector_iterator::value_type value_type
value type of the output vector
typedef VectorIterator vector_iterator
template parameter: the vector iterator type
typedef
vector_iterator::vector_type vector_type
type of the input vector
Public Member Functions
vector_bufreader_reverse (vector_iterator begin, vector_iterator end, stxxl::unsigned_type nbuffers=0)
Create overlapped reader for the given iterator range.
vector_bufreader_reverse (const vector_type &vec, stxxl::unsigned_type nbuffers=0)
Create overlapped reader for the whole vector's content.
~vector_bufreader_reverse ()
Finish reading and free buffered reader.
bool empty () const
Returns true once the whole range has been read.
const value_type & operator* () const
Return constant reference to current item.
vector_bufreader_reverse & operator++ ()
Advance to next item (asserts if !empty()).
const value_type * operator-> () const
Return constant pointer to current item.
vector_bufreader_reverse & operator>> (value_type &v)
Read current item into variable and advance to next one.
void rewind ()
Rewind stream back to begin. Note that this recreates the buffered reader and is thus not cheap.
size_t size () const
Return remaining size.
Protected Attributes
vector_iterator m_begin
iterator to the beginning of the range.
buf_istream_type * m_bufin
buffered input stream used to overlapped I/O.
vector_iterator m_end
iterator to the end of the range.
vector_iterator m_iter
internal "current" iterator into the vector.
stxxl::unsigned_type m_nbuffers
number of blocks to use as buffers.
Member Typedef Documentation
template<typename VectorIterator > typedef vector_iterator::bids_container_iterator vector_bufreader_reverse< VectorIterator >::bids_container_iterator
block identifier iterator of the vector
Definition at line 1928 of file ExtStxxlVector.h.
template<typename VectorIterator > typedef vector_iterator::block_type vector_bufreader_reverse< VectorIterator >::block_type
block type used in the vector
Definition at line 1922 of file ExtStxxlVector.h.
template<typename VectorIterator > typedef stxxl::buf_istream_reverse<block_type, bids_container_iterator> vector_bufreader_reverse< VectorIterator >::buf_istream_type
construct output buffered stream used for overlapped reading
Definition at line 1931 of file ExtStxxlVector.h.
template<typename VectorIterator > typedef vector_iterator::value_type vector_bufreader_reverse< VectorIterator >::value_type
value type of the output vector
Definition at line 1919 of file ExtStxxlVector.h.
template<typename VectorIterator > typedef VectorIterator vector_bufreader_reverse< VectorIterator >::vector_iterator
template parameter: the vector iterator type
Definition at line 1916 of file ExtStxxlVector.h.
template<typename VectorIterator > typedef vector_iterator::vector_type vector_bufreader_reverse< VectorIterator >::vector_type
type of the input vector
Definition at line 1925 of file ExtStxxlVector.h.
Constructor & Destructor Documentation
template<typename VectorIterator > vector_bufreader_reverse< VectorIterator >::vector_bufreader_reverse (vector_iterator begin, vector_iterator end, stxxl::unsigned_type nbuffers = 0) [inline]
Create overlapped reader for the given iterator range.
Parameters:
begin iterator to position were to start reading in vector
end iterator to position were to end reading in vector
nbuffers number of buffers used for overlapped I/O (>= 2*D recommended)
Definition at line 1954 of file ExtStxxlVector.h.
References vector_bufreader_reverse< VectorIterator >::m_begin, vector_bufreader_reverse< VectorIterator >::m_nbuffers, and vector_bufreader_reverse< VectorIterator >::rewind().
template<typename VectorIterator > vector_bufreader_reverse< VectorIterator >::vector_bufreader_reverse (const vector_type & vec, stxxl::unsigned_type nbuffers = 0) [inline]
Create overlapped reader for the whole vector's content.
Parameters:
vec vector to read
nbuffers number of buffers used for overlapped I/O (>= 2*D recommended)
Definition at line 1969 of file ExtStxxlVector.h.
References vector_bufreader_reverse< VectorIterator >::m_begin, vector_bufreader_reverse< VectorIterator >::m_nbuffers, and vector_bufreader_reverse< VectorIterator >::rewind().
template<typename VectorIterator > vector_bufreader_reverse< VectorIterator >::~vector_bufreader_reverse () [inline]
Finish reading and free buffered reader.
Definition at line 2008 of file ExtStxxlVector.h.
References vector_bufreader_reverse< VectorIterator >::m_bufin.
Member Function Documentation
template<typename VectorIterator > bool vector_bufreader_reverse< VectorIterator >::empty () const [inline]
Returns true once the whole range has been read.
Definition at line 2051 of file ExtStxxlVector.h.
References vector_bufreader_reverse< VectorIterator >::m_begin, and vector_bufreader_reverse< VectorIterator >::m_iter.
Referenced by vector_bufreader_reverse< VectorIterator >::operator++(), and vector_bufreader_reverse< VectorIterator >::rewind().
template<typename VectorIterator > const value_type& vector_bufreader_reverse< VectorIterator >::operator* () const [inline]
Return constant reference to current item.
Definition at line 2013 of file ExtStxxlVector.h.
Referenced by vector_bufreader_reverse< VectorIterator >::operator>>().
template<typename VectorIterator > vector_bufreader_reverse& vector_bufreader_reverse< VectorIterator >::operator++ () [inline]
Advance to next item (asserts if !empty()).
Definition at line 2023 of file ExtStxxlVector.h.
References vector_bufreader_reverse< VectorIterator >::empty(), vector_bufreader_reverse< VectorIterator >::m_bufin, and vector_bufreader_reverse< VectorIterator >::m_iter.
Referenced by vector_bufreader_reverse< VectorIterator >::operator>>().
template<typename VectorIterator > const value_type* vector_bufreader_reverse< VectorIterator >::operator-> () const [inline]
Return constant pointer to current item.
Definition at line 2018 of file ExtStxxlVector.h.
template<typename VectorIterator > vector_bufreader_reverse& vector_bufreader_reverse< VectorIterator >::operator>> (value_type & v) [inline]
Read current item into variable and advance to next one.
Definition at line 2037 of file ExtStxxlVector.h.
References vector_bufreader_reverse< VectorIterator >::operator*(), and vector_bufreader_reverse< VectorIterator >::operator++().
template<typename VectorIterator > void vector_bufreader_reverse< VectorIterator >::rewind () [inline]
Rewind stream back to begin. Note that this recreates the buffered reader and is thus not cheap.
Definition at line 1983 of file ExtStxxlVector.h.
References vector_bufreader_reverse< VectorIterator >::empty(), vector_bufreader_reverse< VectorIterator >::m_begin, vector_bufreader_reverse< VectorIterator >::m_bufin, vector_bufreader_reverse< VectorIterator >::m_end, vector_bufreader_reverse< VectorIterator >::m_iter, vector_bufreader_reverse< VectorIterator >::m_nbuffers, and vector_bufreader_reverse< VectorIterator >::size().
Referenced by vector_bufreader_reverse< VectorIterator >::vector_bufreader_reverse().
template<typename VectorIterator > size_t vector_bufreader_reverse< VectorIterator >::size () const [inline]
Return remaining size.
Definition at line 2045 of file ExtStxxlVector.h.
References vector_bufreader_reverse< VectorIterator >::m_begin, vector_bufreader_reverse< VectorIterator >::m_end, and vector_bufreader_reverse< VectorIterator >::m_iter.
Referenced by vector_bufreader_reverse< VectorIterator >::rewind().
Member Data Documentation
template<typename VectorIterator > vector_iterator vector_bufreader_reverse< VectorIterator >::m_begin [protected]
iterator to the beginning of the range.
Definition at line 1935 of file ExtStxxlVector.h.
Referenced by vector_bufreader_reverse< VectorIterator >::empty(), vector_bufreader_reverse< VectorIterator >::rewind(), vector_bufreader_reverse< VectorIterator >::size(), and vector_bufreader_reverse< VectorIterator >::vector_bufreader_reverse().
template<typename VectorIterator > buf_istream_type* vector_bufreader_reverse< VectorIterator >::m_bufin [protected]
buffered input stream used to overlapped I/O.
Definition at line 1944 of file ExtStxxlVector.h.
Referenced by vector_bufreader_reverse< VectorIterator >::operator++(), vector_bufreader_reverse< VectorIterator >::rewind(), and vector_bufreader_reverse< VectorIterator >::~vector_bufreader_reverse().
template<typename VectorIterator > vector_iterator vector_bufreader_reverse< VectorIterator >::m_end [protected]
iterator to the end of the range.
Definition at line 1941 of file ExtStxxlVector.h.
Referenced by vector_bufreader_reverse< VectorIterator >::rewind(), and vector_bufreader_reverse< VectorIterator >::size().
template<typename VectorIterator > vector_iterator vector_bufreader_reverse< VectorIterator >::m_iter [protected]
internal "current" iterator into the vector.
Definition at line 1938 of file ExtStxxlVector.h.
Referenced by vector_bufreader_reverse< VectorIterator >::empty(), vector_bufreader_reverse< VectorIterator >::operator++(), vector_bufreader_reverse< VectorIterator >::rewind(), and vector_bufreader_reverse< VectorIterator >::size().
template<typename VectorIterator > stxxl::unsigned_type vector_bufreader_reverse< VectorIterator >::m_nbuffers [protected]
number of blocks to use as buffers.
Definition at line 1947 of file ExtStxxlVector.h.
Referenced by vector_bufreader_reverse< VectorIterator >::rewind(), and vector_bufreader_reverse< VectorIterator >::vector_bufreader_reverse().
The documentation for this class was generated from the following file:
local/deprecated/ExtStxxlVector.h