ExtLP: ExtRowVector Class Reference
ExtRowVector Class Reference
Detailed Description
Definition at line 13 of file ExtRowVector.h.
Public Types
Types
enum Type { LESS_EQUAL, EQUAL, GREATER_EQUAL, RANGE }
(In)Equality of an LP row.
Public Member Functions
Construction / destruction
ExtRowVector (PackedRowVector &packedRowVector)
Construct LPRow with a vector ready to hold defDim nonzeros The ExtRowVector is constructed from the existing PackedRowVector from the memory Not using row-wise representation of the vector for now.
Access / modification
Type type () const
get type of row.
void setType (Type p_type)
set type of (in)equality
REAL value () const
REAL getLhs () const
get left-hand side value.
std::string getName () const
get the name of the LP Row
void setName (std::string p_name)
access the name of the LP row
void setLhs (REAL p_left)
access left-hand side value.
REAL getRhs () const
get right-hand side value of (in)equality.
void setRhs (REAL p_right)
access right-hand side value.
Private Attributes
Data
REAL m_left
left-hand side of the constraint
REAL m_right
right-hand side of the constraint
std::string m_name
Member Enumeration Documentation
enum ExtRowVector::Type
(In)Equality of an LP row.
LPRows may be of one of the above Types. This datatype may be used for constructing new LPRows in the regular form.
Enumerator:
LESS_EQUAL
.
EQUAL
.
GREATER_EQUAL
.
RANGE
.
Definition at line 31 of file ExtRowVector.h.
Constructor & Destructor Documentation
ExtRowVector::ExtRowVector (PackedRowVector & packedRowVector) [inline, explicit]
Construct LPRow with a vector ready to hold defDim nonzeros The ExtRowVector is constructed from the existing PackedRowVector from the memory Not using row-wise representation of the vector for now.
Definition at line 46 of file ExtRowVector.h.
Member Function Documentation
REAL ExtRowVector::getLhs () const [inline]
get left-hand side value.
Definition at line 116 of file ExtRowVector.h.
References m_left.
Referenced by setType(), type(), and value().
std::string ExtRowVector::getName () const [inline]
get the name of the LP Row
Definition at line 121 of file ExtRowVector.h.
References m_name.
REAL ExtRowVector::getRhs () const [inline]
get right-hand side value of (in)equality.
Definition at line 136 of file ExtRowVector.h.
References m_right.
Referenced by setType(), type(), and value().
void ExtRowVector::setLhs (REAL p_left) [inline]
access left-hand side value.
Definition at line 131 of file ExtRowVector.h.
References m_left.
void ExtRowVector::setName (std::string p_name) [inline]
access the name of the LP row
Definition at line 126 of file ExtRowVector.h.
References m_name.
void ExtRowVector::setRhs (REAL p_right) [inline]
access right-hand side value.
Definition at line 141 of file ExtRowVector.h.
References m_right.
void ExtRowVector::setType (Type p_type) [inline]
set type of (in)equality
Definition at line 76 of file ExtRowVector.h.
References DEBUG_ERROR, EQUAL, getLhs(), getRhs(), GREATER_EQUAL, INFINITY_VALUE, LESS_EQUAL, m_left, m_right, and RANGE.
Type ExtRowVector::type () const [inline]
get type of row.
Definition at line 65 of file ExtRowVector.h.
References EQUAL, getLhs(), getRhs(), GREATER_EQUAL, INFINITY_VALUE, LESS_EQUAL, and RANGE.
Referenced by value().
REAL ExtRowVector::value () const [inline]
This method returns for a LPRow in regular form. However, value() may only be called for LPRows with type() != RANGE.
Definition at line 103 of file ExtRowVector.h.
References getLhs(), getRhs(), INFINITY_VALUE, RANGE, and type().
Member Data Documentation
REAL ExtRowVector::m_left [private]
left-hand side of the constraint
Definition at line 18 of file ExtRowVector.h.
Referenced by getLhs(), setLhs(), and setType().
std::string ExtRowVector::m_name [private]
Definition at line 21 of file ExtRowVector.h.
Referenced by getName(), and setName().
REAL ExtRowVector::m_right [private]
right-hand side of the constraint
Definition at line 19 of file ExtRowVector.h.
Referenced by getRhs(), setRhs(), and setType().
The documentation for this class was generated from the following file:
local/deprecated/ExtRowVector.h