ExtLP: PackedVectorPrototype Class Reference
PackedVectorPrototype Class Reference
Detailed Description
Checks if the vector has sparsity>0.5 and stores in packed form if it does otherwise it will store the complete vector This is the best form to store on disk to reduce the number of I/O(compressed storage)
Definition at line 26 of file PackedVectorPrototype.h.
Public Types
enum VectorStatus { UNINITIALIZED, PACKED, UNPACKED }
Public Member Functions
PackedVectorPrototype (int p_realSize=0)
Initialization section.
PackedVectorPrototype (int p_realSize, bool isPacked)
PackedVectorPrototype (std::vector< double > &vct)
void add (unsigned int index, double value)
Adds into packed form without even checking, if the index already exists.
void clear ()
void convertForDiskWrite ()
Best for performing disk read Main intution is to reduce disk I/O.
void convertToPacked ()
void convertToUnPacked ()
void displayVector ()
PackedElementPrototype get (unsigned int index) const
Gets the packed or unpacked element present in the absolute index position input within corresponding vector When element index is returned to be -1, there is some error Which is either that vector is unintizlized, array out of bounds, or that vector status is unknown.
int getPackedSize ()
Get the total number of non zeros in the vector.
float getSparsity ()
Get the sparsity of the vector.
int getUnPackedSize ()
Get the max capacity of the vector including the zeros.
bool isInitialized () const
checks if the status of the vector is initialized
bool isPacked () const
checks if the status of the vector is packed
void resize (unsigned int p_size)
void setRealSize (unsigned int p_realSize)
unsigned int size () const
void storeUnpackedVector (std::vector< double > &vctUnpack)
Store unpacked vector externally into vctUnpack.
void validateStatus ()
Status should take either of the values in the Status enum.
Static Public Member Functions
static void test ()
Testing the functionality of the Vector.
Public Attributes
VectorStatus status
Private Attributes
unsigned int nnz
unsigned int realSize
Number of non-zeros, define the packed or unpacked form of vector It is the compressed size in Packed form.
std::vector
< PackedElementPrototype > vctPacked
std::vector< double > vctUnpacked
Max number of elements in unpacked form.
Member Enumeration Documentation
enum PackedVectorPrototype::VectorStatus
Enumerator:
UNINITIALIZED
PACKED
Vector status unknown and not yet initialized.
UNPACKED
Vector is in compressed form.
Vector is full-length vector
Definition at line 36 of file PackedVectorPrototype.h.
Constructor & Destructor Documentation
PackedVectorPrototype::PackedVectorPrototype (int p_realSize = 0) [inline]
Initialization section.
Definition at line 45 of file PackedVectorPrototype.h.
References nnz, realSize, status, and UNINITIALIZED.
PackedVectorPrototype::PackedVectorPrototype (int p_realSize, bool isPacked) [inline]
Definition at line 51 of file PackedVectorPrototype.h.
References isPacked(), nnz, PACKED, realSize, status, UNPACKED, and vctUnpacked.
PackedVectorPrototype::PackedVectorPrototype (std::vector< double > & vct) [inline]
Calculating the number of non-zeros Adding the elements into Packed form by default
Definition at line 59 of file PackedVectorPrototype.h.
References PackedElementPrototype::index, nnz, PACKED, realSize, status, PackedElementPrototype::value, and vctPacked.
Member Function Documentation
void PackedVectorPrototype::add (unsigned int index, double value) [inline]
Adds into packed form without even checking, if the index already exists.
Definition at line 185 of file PackedVectorPrototype.h.
References DEBUG_ERROR, PackedElementPrototype::index, nnz, PACKED, size(), status, UNINITIALIZED, UNPACKED, PackedElementPrototype::value, vctPacked, and vctUnpacked.
Referenced by ExtVectorPrototype::storePackPackedVector(), test(), and Test::testExtVectorPrototype().
void PackedVectorPrototype::clear () [inline]
Definition at line 277 of file PackedVectorPrototype.h.
References isPacked(), nnz, realSize, vctPacked, and vctUnpacked.
void PackedVectorPrototype::convertForDiskWrite () [inline]
Best for performing disk read Main intution is to reduce disk I/O.
Definition at line 174 of file PackedVectorPrototype.h.
References convertToPacked(), convertToUnPacked(), nnz, and realSize.
void PackedVectorPrototype::convertToPacked () [inline]
Definition at line 117 of file PackedVectorPrototype.h.
References PackedElementPrototype::index, nnz, PACKED, status, UNINITIALIZED, PackedElementPrototype::value, vctPacked, and vctUnpacked.
Referenced by convertForDiskWrite(), and ExtVectorPrototype::ExtVectorPrototype().
void PackedVectorPrototype::convertToUnPacked () [inline]
Definition at line 135 of file PackedVectorPrototype.h.
References REAL, realSize, status, UNINITIALIZED, UNPACKED, vctPacked, and vctUnpacked.
Referenced by convertForDiskWrite(), ExtVectorPrototype::ExtVectorPrototype(), and test().
void PackedVectorPrototype::displayVector () [inline]
Definition at line 291 of file PackedVectorPrototype.h.
References CONSOLE_PRINTLN, getSparsity(), PACKED, size(), status, UNINITIALIZED, UNPACKED, vctPacked, and vctUnpacked.
Referenced by test().
PackedElementPrototype PackedVectorPrototype::get (unsigned int index) const [inline]
Gets the packed or unpacked element present in the absolute index position input within corresponding vector When element index is returned to be -1, there is some error Which is either that vector is unintizlized, array out of bounds, or that vector status is unknown.
Definition at line 216 of file PackedVectorPrototype.h.
References DEBUG_ERROR, DEBUG_WARNING, PackedElementPrototype::index, nnz, PACKED, realSize, status, UNINITIALIZED, UNPACKED, PackedElementPrototype::value, vctPacked, and vctUnpacked.
Referenced by ExtVectorPrototype::ExtVectorPrototype().
int PackedVectorPrototype::getPackedSize () [inline]
Get the total number of non zeros in the vector.
Definition at line 78 of file PackedVectorPrototype.h.
References nnz, status, UNINITIALIZED, and validateStatus().
Referenced by ExtVectorPrototype::ExtVectorPrototype().
float PackedVectorPrototype::getSparsity () [inline]
Get the sparsity of the vector.
Definition at line 96 of file PackedVectorPrototype.h.
References nnz, realSize, status, UNINITIALIZED, and validateStatus().
Referenced by displayVector(), and ExtVectorPrototype::ExtVectorPrototype().
int PackedVectorPrototype::getUnPackedSize () [inline]
Get the max capacity of the vector including the zeros.
Definition at line 87 of file PackedVectorPrototype.h.
References realSize, status, UNINITIALIZED, and validateStatus().
Referenced by ExtVectorPrototype::ExtVectorPrototype().
bool PackedVectorPrototype::isInitialized () const [inline]
checks if the status of the vector is initialized
Definition at line 251 of file PackedVectorPrototype.h.
References status, and UNINITIALIZED.
bool PackedVectorPrototype::isPacked () const [inline]
checks if the status of the vector is packed
Definition at line 244 of file PackedVectorPrototype.h.
References PACKED, and status.
Referenced by clear(), and PackedVectorPrototype().
void PackedVectorPrototype::resize (unsigned int p_size) [inline]
Definition at line 258 of file PackedVectorPrototype.h.
References PACKED, realSize, status, UNPACKED, vctPacked, and vctUnpacked.
void PackedVectorPrototype::setRealSize (unsigned int p_realSize) [inline]
Definition at line 271 of file PackedVectorPrototype.h.
References realSize, status, UNPACKED, and vctUnpacked.
unsigned int PackedVectorPrototype::size () const [inline]
Definition at line 103 of file PackedVectorPrototype.h.
References DEBUG_ERROR, nnz, PACKED, realSize, status, UNINITIALIZED, and UNPACKED.
Referenced by add(), displayVector(), and ExtVectorPrototype::ExtVectorPrototype().
void PackedVectorPrototype::storeUnpackedVector (std::vector< double > & vctUnpack) [inline]
Store unpacked vector externally into vctUnpack.
Definition at line 153 of file PackedVectorPrototype.h.
References nnz, REAL, realSize, status, UNINITIALIZED, UNPACKED, vctPacked, and vctUnpacked.
static void PackedVectorPrototype::test () [inline, static]
Testing the functionality of the Vector.
Definition at line 329 of file PackedVectorPrototype.h.
References add(), CONSOLE_PRINTLN, convertToUnPacked(), displayVector(), and REAL.
void PackedVectorPrototype::validateStatus () [inline]
Status should take either of the values in the Status enum.
Definition at line 323 of file PackedVectorPrototype.h.
References PACKED, status, UNINITIALIZED, and UNPACKED.
Referenced by getPackedSize(), getSparsity(), and getUnPackedSize().
Member Data Documentation
unsigned int PackedVectorPrototype::nnz [private]
Definition at line 28 of file PackedVectorPrototype.h.
Referenced by add(), clear(), convertForDiskWrite(), convertToPacked(), get(), getPackedSize(), getSparsity(), PackedVectorPrototype(), size(), and storeUnpackedVector().
unsigned int PackedVectorPrototype::realSize [private]
Number of non-zeros, define the packed or unpacked form of vector It is the compressed size in Packed form.
Definition at line 30 of file PackedVectorPrototype.h.
Referenced by clear(), convertForDiskWrite(), convertToUnPacked(), get(), getSparsity(), getUnPackedSize(), PackedVectorPrototype(), resize(), setRealSize(), size(), and storeUnpackedVector().
VectorStatus PackedVectorPrototype::status
Definition at line 42 of file PackedVectorPrototype.h.
Referenced by add(), convertToPacked(), convertToUnPacked(), displayVector(), get(), getPackedSize(), getSparsity(), getUnPackedSize(), isInitialized(), isPacked(), PackedVectorPrototype(), resize(), setRealSize(), size(), storeUnpackedVector(), and validateStatus().
std::vector<PackedElementPrototype> PackedVectorPrototype::vctPacked [private]
Definition at line 32 of file PackedVectorPrototype.h.
Referenced by add(), clear(), convertToPacked(), convertToUnPacked(), displayVector(), get(), PackedVectorPrototype(), resize(), and storeUnpackedVector().
std::vector< double > PackedVectorPrototype::vctUnpacked [private]
Max number of elements in unpacked form.
Definition at line 31 of file PackedVectorPrototype.h.
Referenced by add(), clear(), convertToPacked(), convertToUnPacked(), displayVector(), get(), PackedVectorPrototype(), resize(), setRealSize(), and storeUnpackedVector().
The documentation for this class was generated from the following file:
local/deprecated/PackedVectorPrototype.h