ExtLP: ExtPackedVector< ItemClass > Class Template Reference
ExtPackedVector< ItemClass > Class Template Reference
Detailed Description
template<class ItemClass>
class ExtPackedVector< ItemClass >
This is used only for storing packed-form of the vector PackedVector is recommended be stored into ExtPackedVector only when it is in packed-form.
Definition at line 16 of file ExtPackedVector.h.
Public Types
typedef item_vector::iterator iterator
Defining iterator for the purpose of iteration.
typedef item_vector::iterator iterator
Public Member Functions
ExtPackedVector (PackedVector &packedVector)
Initialization from the PackedVector.
ExtPackedVector (PackedVector< ItemClass > &packedVector)
Initialization from the PackedVector.
void add (unsigned int p_index, PackedElement &p_packed_element)
Adding an PackedElement into the PackedVector.
void add (unsigned int p_index, unsigned int p_absoulute_index, REAL p_value)
Adding an element into the PackedVector.
void add (unsigned int p_index, PackedElement< ItemClass > &p_packed_element)
Adding an PackedElement into the PackedVector.
void add (unsigned int p_index, unsigned int p_absoulute_index, ItemClass p_value)
Adding an element into the PackedVector.
void allocate_cache ()
Allocates the cache desired by an individual vector.
void allocate_cache ()
Allocates the 16MB cache desired by an individual vector.
iterator begin ()
Returns iterator to the beginning(first) element in the vector.
iterator begin ()
Returns iterator to the beginning(first) element in the vector.
void deallocate_cache ()
Deallocates all the cache pertaining to this vector.
void deallocate_cache ()
Deallocates all the cache pertaining to this vector.
iterator end ()
Returns iterator to the ending(last) of the vector.
iterator end ()
Returns iterator to the ending(last) of the vector.
REAL get_absolute_item_value (unsigned int absolute_index)
Returns the ItemValue pertaining to the specific absolute index Here the value from <index, value> pair is returned for a given index.
float get_sparsity ()
Returns the sparsity of the vector.
float get_sparsity ()
Returns the sparsity of the vector.
ItemClass getAbsoluteItemValue (unsigned int index)
Returns the ItemValue pertaining to the specific absolute index.
unsigned int nnz ()
Return the number of non zeros.
unsigned int nnz ()
Return the number of non zeros.
void resize (unsigned int p_size, bool p_allow_shrink=true)
Resizes the vector with an option to allow_shrink. Shrinking is allowed by default.
void resize (unsigned int p_size, bool p_allow_shrink=true)
Resizes the vector with an option to allow_shrink. Shrinking is allowed by default.
unsigned int size ()
Return the number actual size of the vector (in unpacked version)
unsigned int size ()
Return the number actual size of the vector (in unpacked version)
void storeFromPackedVector (PackedVector &p_packed_vector)
Publishing Packed Vector into External memory.
void storeFromPackedVector (PackedVector< ItemClass > &p_packed_vector)
Publishing Packed Vector into External memory.
Private Types
typedef
stxxl::VECTOR_GENERATOR
< PackedElement< ItemClass >
, 1, 1, VECTOR_PACKED_BLOCK_SIZE >
::result item_vector
Vector to store the Items onto external memory.
typedef VECTOR_GENERATOR
< PackedElement,
1, 1, VECTOR_PACKED_BLOCK_SIZE >
::result item_vector
Vector to store the Items onto external memory.
Private Attributes
unsigned int m_nnz
Total number of non zeros in the vector.
ItemClass m_nullItem
Null type for the specific ItemClass.
unsigned int m_size
Total number of elements without compaction/compression.
item_vector m_vct_disk
Member Typedef Documentation
template<class ItemClass > typedef stxxl::VECTOR_GENERATOR< PackedElement<ItemClass>, 1, 1, VECTOR_PACKED_BLOCK_SIZE>::result ExtPackedVector< ItemClass >::item_vector [private]
Vector to store the Items onto external memory.
Definition at line 19 of file ExtPackedVector.h.
template<class ItemClass > typedef VECTOR_GENERATOR< PackedElement, 1, 1, VECTOR_PACKED_BLOCK_SIZE>::result ExtPackedVector< ItemClass >::item_vector [private]
Vector to store the Items onto external memory.
Definition at line 19 of file ExtPackedVector_1.h.
template<class ItemClass > typedef item_vector::iterator ExtPackedVector< ItemClass >::iterator
Defining iterator for the purpose of iteration.
Definition at line 29 of file ExtPackedVector_1.h.
template<class ItemClass > typedef item_vector::iterator ExtPackedVector< ItemClass >::iterator
Definition at line 35 of file ExtPackedVector.h.
Constructor & Destructor Documentation
template<class ItemClass > ExtPackedVector< ItemClass >::ExtPackedVector (PackedVector< ItemClass > & packedVector) [inline]
Initialization from the PackedVector.
Definition at line 38 of file ExtPackedVector.h.
References ExtPackedVector< ItemClass >::storeFromPackedVector().
template<class ItemClass > ExtPackedVector< ItemClass >::ExtPackedVector (PackedVector & packedVector) [inline]
Initialization from the PackedVector.
Definition at line 32 of file ExtPackedVector_1.h.
References ExtPackedVector< ItemClass >::storeFromPackedVector().
Member Function Documentation
template<class ItemClass > void ExtPackedVector< ItemClass >::add (unsigned int p_index, PackedElement & p_packed_element) [inline]
Adding an PackedElement into the PackedVector.
Definition at line 51 of file ExtPackedVector_1.h.
References ExtPackedVector< ItemClass >::add(), PackedElement< ItemClass >::get_index(), and PackedElement< ItemClass >::get_value().
template<class ItemClass > void ExtPackedVector< ItemClass >::add (unsigned int p_index, unsigned int p_absoulute_index, REAL p_value) [inline]
Adding an element into the PackedVector.
Definition at line 55 of file ExtPackedVector_1.h.
References ExtPackedVector< ItemClass >::m_nnz, ExtPackedVector< ItemClass >::m_vct_disk, PackedElement< ItemClass >::set_index(), and PackedElement< ItemClass >::set_value().
template<class ItemClass > void ExtPackedVector< ItemClass >::add (unsigned int p_index, PackedElement< ItemClass > & p_packed_element) [inline]
Adding an PackedElement into the PackedVector.
Definition at line 59 of file ExtPackedVector.h.
References PackedElement< ItemClass >::get_index(), and PackedElement< ItemClass >::get_value().
Referenced by ExtPackedVector< ItemClass >::add(), and ExtPackedVector< ItemClass >::storeFromPackedVector().
template<class ItemClass > void ExtPackedVector< ItemClass >::add (unsigned int p_index, unsigned int p_absoulute_index, ItemClass p_value) [inline]
Adding an element into the PackedVector.
Definition at line 63 of file ExtPackedVector.h.
References ExtPackedVector< ItemClass >::m_nnz, ExtPackedVector< ItemClass >::m_nullItem, ExtPackedVector< ItemClass >::m_vct_disk, PackedElement< ItemClass >::set_index(), and PackedElement< ItemClass >::set_value().
template<class ItemClass > void ExtPackedVector< ItemClass >::allocate_cache () [inline]
Allocates the cache desired by an individual vector.
Definition at line 91 of file ExtPackedVector_1.h.
References ExtPackedVector< ItemClass >::m_vct_disk.
template<class ItemClass > void ExtPackedVector< ItemClass >::allocate_cache () [inline]
Allocates the 16MB cache desired by an individual vector.
Definition at line 98 of file ExtPackedVector.h.
References ExtPackedVector< ItemClass >::m_vct_disk.
Referenced by ExtColVector::allocate_cache(), and ExtColVector::getRowElement().
template<class ItemClass > iterator ExtPackedVector< ItemClass >::begin () [inline]
Returns iterator to the beginning(first) element in the vector.
Definition at line 99 of file ExtPackedVector_1.h.
References ExtPackedVector< ItemClass >::m_vct_disk.
template<class ItemClass > iterator ExtPackedVector< ItemClass >::begin () [inline]
Returns iterator to the beginning(first) element in the vector.
Definition at line 106 of file ExtPackedVector.h.
References ExtPackedVector< ItemClass >::m_vct_disk.
Referenced by ExtColVector::begin(), ExtPackedVector< ItemClass >::get_absolute_item_value(), and ExtPackedVector< ItemClass >::getAbsoluteItemValue().
template<class ItemClass > void ExtPackedVector< ItemClass >::deallocate_cache () [inline]
Deallocates all the cache pertaining to this vector.
Definition at line 95 of file ExtPackedVector_1.h.
References ExtPackedVector< ItemClass >::m_vct_disk.
template<class ItemClass > void ExtPackedVector< ItemClass >::deallocate_cache () [inline]
Deallocates all the cache pertaining to this vector.
Definition at line 102 of file ExtPackedVector.h.
References ExtPackedVector< ItemClass >::m_vct_disk.
Referenced by ExtColVector::deallocate_cache(), ExtColVector::getRowElement(), and ExtPackedVector< ItemClass >::storeFromPackedVector().
template<class ItemClass > iterator ExtPackedVector< ItemClass >::end () [inline]
Returns iterator to the ending(last) of the vector.
Definition at line 103 of file ExtPackedVector_1.h.
References ExtPackedVector< ItemClass >::m_vct_disk.
template<class ItemClass > iterator ExtPackedVector< ItemClass >::end () [inline]
Returns iterator to the ending(last) of the vector.
Definition at line 110 of file ExtPackedVector.h.
References ExtPackedVector< ItemClass >::m_vct_disk.
Referenced by ExtColVector::end(), ExtPackedVector< ItemClass >::get_absolute_item_value(), and ExtPackedVector< ItemClass >::getAbsoluteItemValue().
template<class ItemClass > REAL ExtPackedVector< ItemClass >::get_absolute_item_value (unsigned int absolute_index) [inline]
Returns the ItemValue pertaining to the specific absolute index Here the value from <index, value> pair is returned for a given index.
Definition at line 79 of file ExtPackedVector_1.h.
References ExtPackedVector< ItemClass >::begin(), ExtPackedVector< ItemClass >::end(), PackedElement< ItemClass >::get_index(), and PackedElement< ItemClass >::get_value().
Referenced by ExtColVector::getRowElement().
template<class ItemClass > float ExtPackedVector< ItemClass >::get_sparsity () [inline]
Returns the sparsity of the vector.
Definition at line 107 of file ExtPackedVector_1.h.
References ExtPackedVector< ItemClass >::m_nnz, and ExtPackedVector< ItemClass >::m_size.
template<class ItemClass > float ExtPackedVector< ItemClass >::get_sparsity () [inline]
Returns the sparsity of the vector.
Definition at line 114 of file ExtPackedVector.h.
References ExtPackedVector< ItemClass >::m_nnz, and ExtPackedVector< ItemClass >::m_size.
Referenced by ExtColVector::get_sparsity().
template<class ItemClass > ItemClass ExtPackedVector< ItemClass >::getAbsoluteItemValue (unsigned int index) [inline]
Returns the ItemValue pertaining to the specific absolute index.
Definition at line 86 of file ExtPackedVector.h.
References ExtPackedVector< ItemClass >::begin(), ExtPackedVector< ItemClass >::end(), PackedElement< ItemClass >::get_index(), PackedElement< ItemClass >::get_value(), and ExtPackedVector< ItemClass >::m_nullItem.
template<class ItemClass > unsigned int ExtPackedVector< ItemClass >::nnz () [inline]
Return the number of non zeros.
Definition at line 70 of file ExtPackedVector_1.h.
References ExtPackedVector< ItemClass >::m_nnz.
template<class ItemClass > unsigned int ExtPackedVector< ItemClass >::nnz () [inline]
Return the number of non zeros.
Definition at line 78 of file ExtPackedVector.h.
References ExtPackedVector< ItemClass >::m_nnz.
Referenced by ExtColVector::get_nnz().
template<class ItemClass > void ExtPackedVector< ItemClass >::resize (unsigned int p_size, bool p_allow_shrink = true) [inline]
Resizes the vector with an option to allow_shrink. Shrinking is allowed by default.
Definition at line 66 of file ExtPackedVector_1.h.
References ExtPackedVector< ItemClass >::m_vct_disk.
template<class ItemClass > void ExtPackedVector< ItemClass >::resize (unsigned int p_size, bool p_allow_shrink = true) [inline]
Resizes the vector with an option to allow_shrink. Shrinking is allowed by default.
Definition at line 74 of file ExtPackedVector.h.
References ExtPackedVector< ItemClass >::m_vct_disk.
Referenced by ExtPackedVector< ItemClass >::storeFromPackedVector().
template<class ItemClass > unsigned int ExtPackedVector< ItemClass >::size () [inline]
Return the number actual size of the vector (in unpacked version)
Definition at line 74 of file ExtPackedVector_1.h.
References ExtPackedVector< ItemClass >::m_size.
template<class ItemClass > unsigned int ExtPackedVector< ItemClass >::size () [inline]
Return the number actual size of the vector (in unpacked version)
Definition at line 82 of file ExtPackedVector.h.
References ExtPackedVector< ItemClass >::m_size.
Referenced by ExtColVector::real_size().
template<class ItemClass > void ExtPackedVector< ItemClass >::storeFromPackedVector (PackedVector & p_packed_vector) [inline]
Publishing Packed Vector into External memory.
Definition at line 36 of file ExtPackedVector_1.h.
References ExtPackedVector< ItemClass >::add(), PackedVector< ItemClass >::begin(), ExtPackedVector< ItemClass >::deallocate_cache(), PackedVector< ItemClass >::end(), PackedVector< ItemClass >::get_nnz(), PackedVector< ItemClass >::get_real_size(), ExtPackedVector< ItemClass >::m_nnz, ExtPackedVector< ItemClass >::m_size, and ExtPackedVector< ItemClass >::resize().
template<class ItemClass > void ExtPackedVector< ItemClass >::storeFromPackedVector (PackedVector< ItemClass > & p_packed_vector) [inline]
Publishing Packed Vector into External memory.
Definition at line 42 of file ExtPackedVector.h.
References ExtPackedVector< ItemClass >::add(), PackedVector< ItemClass >::begin(), ExtPackedVector< ItemClass >::deallocate_cache(), PackedVector< ItemClass >::end(), PackedVector< ItemClass >::getNullItem(), PackedVector< ItemClass >::getUnPackedSize(), PackedVector< ItemClass >::isPacked(), ExtPackedVector< ItemClass >::m_nnz, ExtPackedVector< ItemClass >::m_nullItem, ExtPackedVector< ItemClass >::m_size, ExtPackedVector< ItemClass >::resize(), and PackedVector< ItemClass >::size().
Referenced by ExtPackedVector< ItemClass >::ExtPackedVector().
Member Data Documentation
template<class ItemClass > unsigned int ExtPackedVector< ItemClass >::m_nnz [private]
Total number of non zeros in the vector.
Definition at line 22 of file ExtPackedVector.h.
Referenced by ExtPackedVector< ItemClass >::add(), ExtPackedVector< ItemClass >::get_sparsity(), ExtPackedVector< ItemClass >::nnz(), and ExtPackedVector< ItemClass >::storeFromPackedVector().
template<class ItemClass > ItemClass ExtPackedVector< ItemClass >::m_nullItem [private]
Null type for the specific ItemClass.
Definition at line 26 of file ExtPackedVector.h.
Referenced by ExtPackedVector< ItemClass >::add(), ExtPackedVector< ItemClass >::getAbsoluteItemValue(), and ExtPackedVector< ItemClass >::storeFromPackedVector().
template<class ItemClass > unsigned int ExtPackedVector< ItemClass >::m_size [private]
Total number of elements without compaction/compression.
Definition at line 24 of file ExtPackedVector.h.
Referenced by ExtPackedVector< ItemClass >::get_sparsity(), ExtPackedVector< ItemClass >::size(), and ExtPackedVector< ItemClass >::storeFromPackedVector().
template<class ItemClass > item_vector ExtPackedVector< ItemClass >::m_vct_disk [private]
Definition at line 20 of file ExtPackedVector.h.
Referenced by ExtPackedVector< ItemClass >::add(), ExtPackedVector< ItemClass >::allocate_cache(), ExtPackedVector< ItemClass >::begin(), ExtPackedVector< ItemClass >::deallocate_cache(), ExtPackedVector< ItemClass >::end(), and ExtPackedVector< ItemClass >::resize().
The documentation for this class was generated from the following files:
local/deprecated/ExtPackedVector.h
local/deprecated/ExtPackedVector_1.h