ExtLP: ExtMatrixA Class Reference
ExtMatrixA Class Reference
Detailed Description
Storage Container for Fixed Matrix The contents of the matrix do not change after assignment/initialization Storage is done in column-wise fashion.
Definition at line 123 of file ExtMatrixA.h.
Public Types
typedef MatrixAColAttr ColAttr
Matrix Row and Column Attributes.
typedef MatrixARowAttr RowAttr
Public Member Functions
ExtMatrixA ()
Simple Initialization.
void add_column (PackedColVector &p_packed_col)
Adds a new column into the matrix.
void add_row (PackedRowVector &p_packed_row)
Adds a new row into the matrix TODO - Check setting of RHS is correct or not.
unsigned int get_basic_columns_count ()
Returns the basic columns count - Total number of basic columns in the matrix There is a possibility that a constraint can lead to more than one columns. Simply the number of basic columns should be equal the total number of constraints.
ColAttr get_col_attr (unsigned int p_col_index)
Returns the column attributes associated with the p_col_index.
unsigned int get_col_nnz (unsigned int p_col_index)
Returns the number of non-zeros for a given p_col_index column Use this to get nnz instead of fetching entire column.
float get_col_sparsity (unsigned int p_col_index)
Returns the sparsity of given p_col_index column. Use this to get sparsity instead of fetching entire column.
unsigned int get_columns_count ()
Returns the columns count - Total number of columns in the matrix.
unsigned int get_element_size ()
float get_overall_density ()
Returns the overall density of the matrix.
float get_overall_nnz ()
Returns the overall number of nonzeros of the matrix.
RowAttr get_row_attr (unsigned int p_row_index)
gets the row attributes specific to a column
unsigned int get_rows_count ()
Returns the rows count - Total number of rows in the matrix.
void set_col_attr (unsigned int p_col_index, ColAttr p_col_attr)
Returns the column attributes associated with the p_col_index.
void set_row_attr (unsigned int p_row_index, MatrixARowAttr &p_row_attr)
sets the row attributes of a column
SimpleVector< unsigned int > standardize_matrix ()
Standardizing the LP Tableau (MatrixA) for performing simplex Returns the base column indices in order.
void store_col_objective_values (SimpleVector< double > &p_vct_obj, SimpleVector< unsigned int > base_col_indices, bool is_min)
Stores the col objective values into the packed vector in the order of base col indices.
void store_column (unsigned int p_column_idx, PackedVector &p_packed_col, bool p_add_objective=true)
Store an Entire column excluding the objective value Send by Reference... Hence parameter PackedVector will be affected TODO - Check if the objective value is added properly to the end.
void store_row_rhs_values (SimpleVector< double > &p_vct_rhs)
Stores the row rhs values into the packedvector.
Private Types
typedef
stxxl::VECTOR_GENERATOR
< MatrixAColAttr, 1, 1,(10 *1024 *1024) >
::resul col_data_vector)
Vector to keep track of columns in the matrix.
typedef
stxxl::VECTOR_GENERATOR
< PackedElement, 10, 1,(10 *1024 *1024) >
::resul item_vector)
Vector to store the Items onto external memory template parameters<ValueType, PageSize, CachePages, BlockSize, AllocStratg>
typedef
stxxl::VECTOR_GENERATOR
< MatrixARowAttr, 1, 1,(10 *1024 *1024) >
::resul row_data_vector)
Vector to keep track of rows in the matrix.
Private Member Functions
void _add_slack_column (unsigned int p_slack_row_index)
Adds a new slack column into the matrix Done programmatically while standardization of the matrix TODO - Incorporate processing singleton columns directly from ColAttr itself.
Private Attributes
col_data_vector m_vct_col_attr
item_vector m_vct_disk
const col_data_vector & m_vct_read_only_col_attr
const item_vector & m_vct_read_only_disk
const row_data_vector & m_vct_read_only_row_attr
row_data_vector m_vct_row_attr
Member Typedef Documentation
typedef stxxl::VECTOR_GENERATOR<MatrixAColAttr, 1, 1, (10*1024*1024) >::resul ExtMatrixA::col_data_vector) [private]
Vector to keep track of columns in the matrix.
Definition at line 131 of file ExtMatrixA.h.
typedef MatrixAColAttr ExtMatrixA::ColAttr
Matrix Row and Column Attributes.
Definition at line 161 of file ExtMatrixA.h.
typedef stxxl::VECTOR_GENERATOR<PackedElement, 10 , 1 , (10*1024*1024) >::resul ExtMatrixA::item_vector) [private]
Vector to store the Items onto external memory template parameters<ValueType, PageSize, CachePages, BlockSize, AllocStratg>
Definition at line 127 of file ExtMatrixA.h.
typedef stxxl::VECTOR_GENERATOR<MatrixARowAttr, 1, 1, (10*1024*1024) >::resul ExtMatrixA::row_data_vector) [private]
Vector to keep track of rows in the matrix.
Definition at line 135 of file ExtMatrixA.h.
typedef MatrixARowAttr ExtMatrixA::RowAttr
Definition at line 163 of file ExtMatrixA.h.
Constructor & Destructor Documentation
ExtMatrixA::ExtMatrixA () [inline]
Simple Initialization.
Definition at line 166 of file ExtMatrixA.h.
Member Function Documentation
void ExtMatrixA::_add_slack_column (unsigned int p_slack_row_index) [inline, private]
Adds a new slack column into the matrix Done programmatically while standardization of the matrix TODO - Incorporate processing singleton columns directly from ColAttr itself.
Definition at line 142 of file ExtMatrixA.h.
References get_row_attr(), MatrixARowAttr::get_row_name(), m_vct_col_attr, m_vct_disk, MatrixAColAttr::set_col_name(), MatrixAColAttr::set_is_basic_col(), MatrixAColAttr::set_is_slack_col(), and MatrixAColAttr::set_objective_value().
Referenced by standardize_matrix().
void ExtMatrixA::add_column (PackedColVector & p_packed_col) [inline]
Adds a new column into the matrix.
TODO - Set the start limit of col appropriately
Initial basis columns would be the set of slack columns. Hence basic property set to false
Definition at line 173 of file ExtMatrixA.h.
References PackedVector< ItemClass >::begin(), PackedVector< ItemClass >::end(), PackedColVector::get_col_vector(), PackedColVector::get_name(), PackedVector< ItemClass >::get_nnz(), PackedColVector::get_objective_value(), m_vct_col_attr, m_vct_disk, and MatrixAColAttr::set_objective_value().
Referenced by ExtReadMPSUtil::readCols().
void ExtMatrixA::add_row (PackedRowVector & p_packed_row) [inline]
Adds a new row into the matrix TODO - Check setting of RHS is correct or not.
Definition at line 257 of file ExtMatrixA.h.
References PackedRowVector::get_lhs(), PackedRowVector::get_name(), PackedRowVector::get_rhs(), PackedRowVector::get_row_type(), m_vct_row_attr, MatrixARowAttr::set_lhs_value(), MatrixARowAttr::set_rhs_value(), MatrixARowAttr::set_row_name(), and MatrixARowAttr::set_row_type().
Referenced by ExtReadMPSUtil::readRows().
unsigned int ExtMatrixA::get_basic_columns_count () [inline]
Returns the basic columns count - Total number of basic columns in the matrix There is a possibility that a constraint can lead to more than one columns. Simply the number of basic columns should be equal the total number of constraints.
Definition at line 233 of file ExtMatrixA.h.
References get_rows_count().
ColAttr ExtMatrixA::get_col_attr (unsigned int p_col_index) [inline]
Returns the column attributes associated with the p_col_index.
Definition at line 221 of file ExtMatrixA.h.
References m_vct_read_only_col_attr.
Referenced by ExtSimplex::debug_b_inverse(), ExtSimplex::debug_base_col_indices(), Test::testExtMatrixA(), Test::testMatrixBInverse(), and ExtSimplex::update_simplex_iteration().
unsigned int ExtMatrixA::get_col_nnz (unsigned int p_col_index) [inline]
Returns the number of non-zeros for a given p_col_index column Use this to get nnz instead of fetching entire column.
Definition at line 273 of file ExtMatrixA.h.
References MatrixAColAttr::get_end(), MatrixAColAttr::get_start(), and m_vct_read_only_col_attr.
Referenced by get_col_sparsity(), get_overall_nnz(), and Test::testExtMatrixA().
float ExtMatrixA::get_col_sparsity (unsigned int p_col_index) [inline]
Returns the sparsity of given p_col_index column. Use this to get sparsity instead of fetching entire column.
Definition at line 280 of file ExtMatrixA.h.
References get_col_nnz(), and get_rows_count().
Referenced by Test::testExtMatrixA().
unsigned int ExtMatrixA::get_columns_count () [inline]
Returns the columns count - Total number of columns in the matrix.
Definition at line 226 of file ExtMatrixA.h.
References m_vct_read_only_col_attr.
Referenced by get_overall_density(), get_overall_nnz(), ExtReadMPSUtil::readMPS(), standardize_matrix(), Test::testExtMatrixA(), and ExtSimplex::update_simplex_iteration().
unsigned int ExtMatrixA::get_element_size () [inline]
Definition at line 314 of file ExtMatrixA.h.
References m_vct_read_only_disk.
Referenced by get_expected_io_currently(), ExtSimplex::get_expected_io_currently(), ExtSimplex::get_expected_read_io_currently(), and get_expected_write_io_currently().
float ExtMatrixA::get_overall_density () [inline]
Returns the overall density of the matrix.
Definition at line 319 of file ExtMatrixA.h.
References get_columns_count(), get_overall_nnz(), and get_rows_count().
Referenced by print_io_statistics().
float ExtMatrixA::get_overall_nnz () [inline]
Returns the overall number of nonzeros of the matrix.
Definition at line 326 of file ExtMatrixA.h.
References get_col_nnz(), and get_columns_count().
Referenced by get_expected_io_currently(), ExtSimplex::get_expected_io_currently(), ExtSimplex::get_expected_read_io_currently(), get_expected_write_io_currently(), get_overall_density(), and print_io_statistics().
RowAttr ExtMatrixA::get_row_attr (unsigned int p_row_index) [inline]
gets the row attributes specific to a column
Definition at line 287 of file ExtMatrixA.h.
References m_vct_read_only_row_attr.
Referenced by _add_slack_column(), ExtSimplex::debug_b_inverse(), ExtReadMPSUtil::readRhs(), standardize_matrix(), Test::testExtMatrixA(), and Test::testMatrixBInverse().
unsigned int ExtMatrixA::get_rows_count () [inline]
Returns the rows count - Total number of rows in the matrix.
Definition at line 267 of file ExtMatrixA.h.
References m_vct_read_only_row_attr.
Referenced by ExtMatrixBInverse::build_matrix_b_inverse(), get_basic_columns_count(), get_col_sparsity(), get_overall_density(), ExtReadMPSUtil::readCols(), ExtReadMPSUtil::readMPS(), standardize_matrix(), store_column(), store_row_rhs_values(), and Test::testExtMatrixA().
void ExtMatrixA::set_col_attr (unsigned int p_col_index, ColAttr p_col_attr) [inline]
Returns the column attributes associated with the p_col_index.
Definition at line 238 of file ExtMatrixA.h.
References m_vct_col_attr.
Referenced by ExtSimplex::update_simplex_iteration().
void ExtMatrixA::set_row_attr (unsigned int p_row_index, MatrixARowAttr & p_row_attr) [inline]
sets the row attributes of a column
Definition at line 293 of file ExtMatrixA.h.
References m_vct_row_attr.
Referenced by ExtReadMPSUtil::readRhs(), and standardize_matrix().
SimpleVector<unsigned int> ExtMatrixA::standardize_matrix () [inline]
Standardizing the LP Tableau (MatrixA) for performing simplex Returns the base column indices in order.
Definition at line 337 of file ExtMatrixA.h.
References _add_slack_column(), SimpleVector< ItemClass >::add(), DEBUG_WARNING, get_columns_count(), get_row_attr(), MatrixARowAttr::get_row_type(), get_rows_count(), set_row_attr(), and MatrixARowAttr::set_row_type().
Referenced by ExtSimplex::init_simplex().
void ExtMatrixA::store_col_objective_values (SimpleVector< double > & p_vct_obj, SimpleVector< unsigned int > base_col_indices, bool is_min) [inline]
Stores the col objective values into the packed vector in the order of base col indices.
Definition at line 242 of file ExtMatrixA.h.
References SimpleVector< ItemClass >::clear(), SimpleVector< ItemClass >::get_size(), m_vct_read_only_col_attr, REAL, and SimpleVector< ItemClass >::resize().
Referenced by ExtSimplex::init_simplex().
void ExtMatrixA::store_column (unsigned int p_column_idx, PackedVector & p_packed_col, bool p_add_objective = true) [inline]
Store an Entire column excluding the objective value Send by Reference... Hence parameter PackedVector will be affected TODO - Check if the objective value is added properly to the end.
Definition at line 197 of file ExtMatrixA.h.
References PackedVector< ItemClass >::add(), PackedVector< ItemClass >::clear(), MatrixAColAttr::get_end(), PackedElement< ItemClass >::get_index(), MatrixAColAttr::get_objective_value(), get_rows_count(), MatrixAColAttr::get_start(), PackedElement< ItemClass >::get_value(), m_vct_read_only_col_attr, m_vct_read_only_disk, REAL, and PackedVector< ItemClass >::resize().
Referenced by ExtMatrixBInverse::build_matrix_b_inverse(), Test::testExtMatrixA(), and ExtSimplex::update_simplex_iteration().
void ExtMatrixA::store_row_rhs_values (SimpleVector< double > & p_vct_rhs) [inline]
Stores the row rhs values into the packedvector.
Definition at line 298 of file ExtMatrixA.h.
References SimpleVector< ItemClass >::clear(), get_rows_count(), m_vct_read_only_row_attr, REAL, and SimpleVector< ItemClass >::resize().
Referenced by ExtSimplex::init_simplex().
Member Data Documentation
col_data_vector ExtMatrixA::m_vct_col_attr [private]
Definition at line 132 of file ExtMatrixA.h.
Referenced by _add_slack_column(), add_column(), and set_col_attr().
item_vector ExtMatrixA::m_vct_disk [private]
Definition at line 128 of file ExtMatrixA.h.
Referenced by _add_slack_column(), and add_column().
const col_data_vector& ExtMatrixA::m_vct_read_only_col_attr [private]
Definition at line 133 of file ExtMatrixA.h.
Referenced by get_col_attr(), get_col_nnz(), get_columns_count(), store_col_objective_values(), and store_column().
const item_vector& ExtMatrixA::m_vct_read_only_disk [private]
Definition at line 129 of file ExtMatrixA.h.
Referenced by get_element_size(), and store_column().
const row_data_vector& ExtMatrixA::m_vct_read_only_row_attr [private]
Definition at line 137 of file ExtMatrixA.h.
Referenced by get_row_attr(), get_rows_count(), and store_row_rhs_values().
row_data_vector ExtMatrixA::m_vct_row_attr [private]
Definition at line 136 of file ExtMatrixA.h.
Referenced by add_row(), and set_row_attr().
The documentation for this class was generated from the following file:
local/ExtMatrixA.h