ExtLP: LinkedListNode< ItemClass > Class Template Reference
LinkedListNode< ItemClass > Class Template Reference
Detailed Description
template<class ItemClass>
class LinkedListNode< ItemClass >
Definition at line 15 of file LinkedList.h.
Public Member Functions
LinkedListNode (ItemClass item)
ItemClass getItem ()
ItemClass & getItemReference ()
LinkedListNode< ItemClass > * getNext ()
void setItem (ItemClass item)
void setNext (LinkedListNode< ItemClass > *next)
Private Attributes
ItemClass item
LinkedListNode< ItemClass > * next
Constructor & Destructor Documentation
template<class ItemClass> LinkedListNode< ItemClass >::LinkedListNode (ItemClass item) [inline]
Definition at line 20 of file LinkedList.h.
Member Function Documentation
template<class ItemClass> ItemClass LinkedListNode< ItemClass >::getItem () [inline]
Definition at line 33 of file LinkedList.h.
Referenced by LinkedList< PackedElement< ItemClass > >::add_sorted(), and LinkedList< PackedElement< ItemClass > >::remove().
template<class ItemClass> ItemClass& LinkedListNode< ItemClass >::getItemReference () [inline]
Definition at line 36 of file LinkedList.h.
template<class ItemClass> LinkedListNode<ItemClass>* LinkedListNode< ItemClass >::getNext () [inline]
Definition at line 30 of file LinkedList.h.
Referenced by LinkedList< PackedElement< ItemClass > >::add(), LinkedList< PackedElement< ItemClass > >::add_sorted(), LinkedList< PackedElement< ItemClass > >::clear(), LinkedList< ItemClass >::iterator::operator+(), and LinkedList< PackedElement< ItemClass > >::remove().
template<class ItemClass> void LinkedListNode< ItemClass >::setItem (ItemClass item) [inline]
Definition at line 27 of file LinkedList.h.
template<class ItemClass> void LinkedListNode< ItemClass >::setNext (LinkedListNode< ItemClass > * next) [inline]
Definition at line 24 of file LinkedList.h.
Referenced by LinkedList< PackedElement< ItemClass > >::add(), LinkedList< PackedElement< ItemClass > >::add_sorted(), and LinkedList< PackedElement< ItemClass > >::remove().
Member Data Documentation
template<class ItemClass> ItemClass LinkedListNode< ItemClass >::item [private]
Definition at line 17 of file LinkedList.h.
Referenced by LinkedListNode< PackedElement< ItemClass > >::getItem(), LinkedListNode< PackedElement< ItemClass > >::getItemReference(), LinkedListNode< PackedElement< ItemClass > >::LinkedListNode(), and LinkedListNode< PackedElement< ItemClass > >::setItem().
template<class ItemClass> LinkedListNode<ItemClass>* LinkedListNode< ItemClass >::next [private]
Definition at line 18 of file LinkedList.h.
Referenced by LinkedListNode< PackedElement< ItemClass > >::getNext(), LinkedListNode< PackedElement< ItemClass > >::LinkedListNode(), and LinkedListNode< PackedElement< ItemClass > >::setNext().
The documentation for this class was generated from the following file:
local/LinkedList.h