ExtLP: LinkedList< ItemClass > Class Template Reference
LinkedList< ItemClass > Class Template Reference
Detailed Description
template<class ItemClass>
class LinkedList< ItemClass >
Definition at line 41 of file LinkedList.h.
Classes
class iterator
Public Member Functions
LinkedList ()
Simple Initialization.
LinkedList (LinkedList &p_list)
Copy Constructor. Does shallow copy by default hence need to be careful Overriding for creating a deep copy of LinkedList.
~LinkedList ()
Destroying LinkedList.
void add (ItemClass item)
Adds the item at the end of the list.
void add (iterator itr, ItemClass item)
Adds the item before the given iterator/position of list.
void add_sorted (ItemClass p_item)
Adds the item in the sorted (assending order) fashion.
iterator begin () const
Returns the iterator pointing to the beginning element of the list.
void clear ()
Clears the complete list (deleting all the nodes in the list)
iterator end () const
Returns the iterator pointing to the ending element of the list.
bool remove (ItemClass p_item)
Just removes the element if exists. Returns true if element exists after deleted it. Returns false if element does not exist.
unsigned int size ()
Returns the size of the linked List.
Private Attributes
LinkedListNode< ItemClass > * head
unsigned int m_size
LinkedListNode< ItemClass > * tail
Constructor & Destructor Documentation
template<class ItemClass> LinkedList< ItemClass >::LinkedList () [inline]
Simple Initialization.
Definition at line 93 of file LinkedList.h.
template<class ItemClass> LinkedList< ItemClass >::LinkedList (LinkedList< ItemClass > & p_list) [inline]
Copy Constructor. Does shallow copy by default hence need to be careful Overriding for creating a deep copy of LinkedList.
Definition at line 100 of file LinkedList.h.
template<class ItemClass> LinkedList< ItemClass >::~LinkedList () [inline]
Destroying LinkedList.
Definition at line 112 of file LinkedList.h.
Member Function Documentation
template<class ItemClass> void LinkedList< ItemClass >::add (ItemClass item) [inline]
Adds the item at the end of the list.
Definition at line 133 of file LinkedList.h.
Referenced by LinkedList< PackedElement< ItemClass > >::add(), PackedVector< ItemClass >::add(), LinkedList< PackedElement< ItemClass > >::LinkedList(), and Test::testLinkedList().
template<class ItemClass> void LinkedList< ItemClass >::add (iterator itr, ItemClass item) [inline]
Adds the item before the given iterator/position of list.
Definition at line 226 of file LinkedList.h.
template<class ItemClass> void LinkedList< ItemClass >::add_sorted (ItemClass p_item) [inline]
Adds the item in the sorted (assending order) fashion.
Definition at line 146 of file LinkedList.h.
Referenced by PackedVector< ItemClass >::add().
template<class ItemClass> iterator LinkedList< ItemClass >::begin () const [inline]
Returns the iterator pointing to the beginning element of the list.
Definition at line 242 of file LinkedList.h.
Referenced by PackedVector< ItemClass >::add(), PackedVector< ItemClass >::begin(), PackedVector< ItemClass >::convertToUnPacked(), PackedVector< ItemClass >::displayVector(), PackedVector< ItemClass >::get(), LinkedList< PackedElement< ItemClass > >::LinkedList(), PackedVector< ItemClass >::operator[](), PackedVector< ItemClass >::sort_by_index(), and Test::testLinkedList().
template<class ItemClass> void LinkedList< ItemClass >::clear () [inline]
Clears the complete list (deleting all the nodes in the list)
Definition at line 116 of file LinkedList.h.
Referenced by PackedVector< ItemClass >::clear(), PackedVector< ItemClass >::convertToPacked(), PackedVector< ItemClass >::convertToUnPacked(), PackedVector< ItemClass >::storeUnpackedVector(), Test::testLinkedList(), and LinkedList< PackedElement< ItemClass > >::~LinkedList().
template<class ItemClass> iterator LinkedList< ItemClass >::end () const [inline]
Returns the iterator pointing to the ending element of the list.
Definition at line 248 of file LinkedList.h.
Referenced by PackedVector< ItemClass >::add(), PackedVector< ItemClass >::convertToUnPacked(), PackedVector< ItemClass >::displayVector(), PackedVector< ItemClass >::end(), PackedVector< ItemClass >::get(), LinkedList< PackedElement< ItemClass > >::LinkedList(), PackedVector< ItemClass >::operator[](), PackedVector< ItemClass >::sort_by_index(), and Test::testLinkedList().
template<class ItemClass> bool LinkedList< ItemClass >::remove (ItemClass p_item) [inline]
Just removes the element if exists. Returns true if element exists after deleted it. Returns false if element does not exist.
Definition at line 185 of file LinkedList.h.
Referenced by PackedVector< ItemClass >::remove().
template<class ItemClass> unsigned int LinkedList< ItemClass >::size () [inline]
Returns the size of the linked List.
Definition at line 238 of file LinkedList.h.
Referenced by Test::testLinkedList().
Member Data Documentation
template<class ItemClass> LinkedListNode<ItemClass>* LinkedList< ItemClass >::head [private]
Definition at line 43 of file LinkedList.h.
Referenced by LinkedList< PackedElement< ItemClass > >::add(), LinkedList< PackedElement< ItemClass > >::add_sorted(), LinkedList< PackedElement< ItemClass > >::begin(), LinkedList< PackedElement< ItemClass > >::clear(), LinkedList< PackedElement< ItemClass > >::LinkedList(), and LinkedList< PackedElement< ItemClass > >::remove().
template<class ItemClass> unsigned int LinkedList< ItemClass >::m_size [private]
Definition at line 45 of file LinkedList.h.
Referenced by LinkedList< PackedElement< ItemClass > >::add(), LinkedList< PackedElement< ItemClass > >::add_sorted(), LinkedList< PackedElement< ItemClass > >::clear(), LinkedList< PackedElement< ItemClass > >::LinkedList(), LinkedList< PackedElement< ItemClass > >::remove(), and LinkedList< PackedElement< ItemClass > >::size().
template<class ItemClass> LinkedListNode<ItemClass>* LinkedList< ItemClass >::tail [private]
Definition at line 44 of file LinkedList.h.
Referenced by LinkedList< PackedElement< ItemClass > >::add(), LinkedList< PackedElement< ItemClass > >::add_sorted(), LinkedList< PackedElement< ItemClass > >::clear(), LinkedList< PackedElement< ItemClass > >::LinkedList(), and LinkedList< PackedElement< ItemClass > >::remove().
The documentation for this class was generated from the following file:
local/LinkedList.h