ExtLP: ExtReadMPSUtil Class Reference
ExtReadMPSUtil Class Reference
Detailed Description
Definition at line 13 of file ExtReadMPSUtil.h.
Public Member Functions
bool readMPS (std::istream &is, ExtLPDSSet &extDataSet)
bool readMPS (std::istream &is, ExtLPDSSet &extDataSet)
Static Public Member Functions
static void readCols (MPSInput &mps, ExtLPDSSet &extDataSet)
Process COLUMNS section.
static void readCols (MPSInput &mps, ExtLPDSSet &extDataSet)
Process COLUMNS section.
static void readName (MPSInput &mps)
Process NAME section.
static void readName (MPSInput &mps)
Process NAME section. TODO - Also store name into the extDataSet.
static void readObjname (MPSInput &mps)
Process OBJNAME section. This Section is an ILOG extension.
static void readObjname (MPSInput &mps)
Process OBJNAME section. This Section is an ILOG extension.
static void readObjsen (MPSInput &mps)
Process OBJSEN section. This Section is an ILOG extension.
static void readObjsen (MPSInput &mps)
Process OBJSEN section. This Section is an ILOG extension.
static void readRhs (MPSInput &mps, ExtLPDSSet &extDataSet)
Process RHS section.
static void readRhs (MPSInput &mps, ExtLPDSSet &extDataSet)
Process RHS section.
static void readRows (MPSInput &mps, ExtLPDSSet &extDataSet)
Process ROWS section.
static void readRows (MPSInput &mps, ExtLPDSSet &extDataSet)
Process ROWS section.
Member Function Documentation
static void ExtReadMPSUtil::readCols (MPSInput & mps, ExtLPDSSet & extDataSet) [inline, static]
Process COLUMNS section.
Definition at line 172 of file ExtReadMPSUtil.h.
References ExtNameMap::contains(), DEBUG_PARSER, DEBUG_SIMPLE, MPSInput::entryIgnored(), MPSInput::field0(), MPSInput::field1(), MPSInput::field2(), MPSInput::field3(), MPSInput::field4(), MPSInput::field5(), ExtNameMap::get(), ExtColVector::get_sparsity(), ExtColVector::getName(), INFINITY_VALUE, ExtLPDSSet::mapColName, ExtLPDSSet::mapRowName, MPSInput::MAX_LINE_LEN, MPSInput::objName(), MPSInput::readLine(), REAL, MPSInput::RHS, ExtNameMap::set(), PackedColVector::set_objective_value(), MPSInput::setSection(), and MPSInput::syntaxError().
Referenced by readMPS().
static void ExtReadMPSUtil::readCols (MPSInput & mps, ExtLPDSSet & extDataSet) [inline, static]
Process COLUMNS section.
Definition at line 246 of file ExtReadMPSUtil.h.
References ExtLPDSSet::A, ExtMatrixA::add_column(), ExtNameMap::contains(), DEBUG_PARSER, MPSInput::entryIgnored(), MPSInput::field0(), MPSInput::field1(), MPSInput::field2(), MPSInput::field3(), MPSInput::field4(), MPSInput::field5(), ExtNameMap::get(), ExtMatrixA::get_rows_count(), INFINITY_VALUE, ExtLPDSSet::mapColName, ExtLPDSSet::mapRowName, MPSInput::MAX_LINE_LEN, MPSInput::objName(), MPSInput::readLine(), REAL, MPSInput::RHS, ExtNameMap::set(), MPSInput::setSection(), and MPSInput::syntaxError().
bool ExtReadMPSUtil::readMPS (std::istream & is, ExtLPDSSet & extDataSet) [inline]
Debugging the logic and results /////////////////////////////////////////////////////////////
Row-wise display of the LP Tableau
Sparsity Analysis --- Column-wise display of LP Tableau
---------------- Sparsity Analysis
Definition at line 390 of file ExtReadMPSUtil.h.
References MPSInput::COLUMNS, DEBUG, DEBUG_FILE, DEBUG_FILE_WITH_TIMESTAMP, DEBUG_PARSER, DEBUG_SIMPLE, ExtColVector::get_nnz(), ExtLPDSSet::get_problem_name(), ExtColVector::get_sparsity(), MPSInput::OBJNAME, MPSInput::objName(), MPSInput::OBJSEN, MPSInput::objSense(), MPSInput::probName(), readCols(), readName(), readObjname(), readObjsen(), readRhs(), readRows(), MPSInput::RHS, MPSInput::ROWS, MPSInput::section(), ExtLPDSSet::set_problem_name(), ExtLPDSSet::setObjName(), and ExtLPDSSet::setObjSense().
Referenced by ReadFileUtil::readFileUsingDisk().
bool ExtReadMPSUtil::readMPS (std::istream & is, ExtLPDSSet & extDataSet) [inline]
Definition at line 432 of file ExtReadMPSUtil.h.
References ExtLPDSSet::A, MPSInput::COLUMNS, DEBUG, DEBUG_FILE_WITH_TIMESTAMP, DEBUG_PARSER, DEBUG_SIMPLE, ExtMatrixA::get_columns_count(), ExtMatrixA::get_rows_count(), MPSInput::OBJNAME, MPSInput::objName(), MPSInput::OBJSEN, MPSInput::objSense(), MPSInput::probName(), readCols(), readName(), readObjname(), readObjsen(), readRhs(), readRows(), MPSInput::RHS, MPSInput::ROWS, MPSInput::section(), ExtLPDSSet::set_problem_name(), ExtLPDSSet::setObjName(), and ExtLPDSSet::setObjSense().
static void ExtReadMPSUtil::readName (MPSInput & mps) [inline, static]
Process NAME section.
Definition at line 16 of file ExtReadMPSUtil.h.
References MPSInput::field0(), MPSInput::field1(), MPSInput::OBJNAME, MPSInput::OBJSEN, MPSInput::readLine(), MPSInput::ROWS, MPSInput::setProbName(), MPSInput::setSection(), and MPSInput::syntaxError().
Referenced by readMPS().
static void ExtReadMPSUtil::readName (MPSInput & mps) [inline, static]
Process NAME section. TODO - Also store name into the extDataSet.
Definition at line 19 of file ExtReadMPSUtil.h.
References MPSInput::field0(), MPSInput::field1(), MPSInput::OBJNAME, MPSInput::OBJSEN, MPSInput::readLine(), MPSInput::ROWS, MPSInput::setProbName(), MPSInput::setSection(), and MPSInput::syntaxError().
static void ExtReadMPSUtil::readObjname (MPSInput & mps) [inline, static]
Process OBJNAME section. This Section is an ILOG extension.
Definition at line 73 of file ExtReadMPSUtil.h.
References MPSInput::field0(), MPSInput::field1(), MPSInput::readLine(), MPSInput::ROWS, MPSInput::setObjName(), MPSInput::setSection(), and MPSInput::syntaxError().
static void ExtReadMPSUtil::readObjname (MPSInput & mps) [inline, static]
Process OBJNAME section. This Section is an ILOG extension.
Definition at line 84 of file ExtReadMPSUtil.h.
References MPSInput::field0(), MPSInput::field1(), MPSInput::readLine(), MPSInput::ROWS, MPSInput::setObjName(), MPSInput::setSection(), and MPSInput::syntaxError().
Referenced by readMPS().
static void ExtReadMPSUtil::readObjsen (MPSInput & mps) [inline, static]
Process OBJSEN section. This Section is an ILOG extension.
Definition at line 46 of file ExtReadMPSUtil.h.
References MPSInput::field0(), MPSInput::field1(), MPSInput::OBJNAME, MPSInput::readLine(), MPSInput::ROWS, MPSInput::setObjSense(), MPSInput::setSection(), and MPSInput::syntaxError().
static void ExtReadMPSUtil::readObjsen (MPSInput & mps) [inline, static]
Process OBJSEN section. This Section is an ILOG extension.
Definition at line 53 of file ExtReadMPSUtil.h.
References MPSInput::field0(), MPSInput::field1(), MPSInput::OBJNAME, MPSInput::readLine(), MPSInput::ROWS, MPSInput::setObjSense(), MPSInput::setSection(), and MPSInput::syntaxError().
Referenced by readMPS().
static void ExtReadMPSUtil::readRhs (MPSInput & mps, ExtLPDSSet & extDataSet) [inline, static]
Process RHS section.
Definition at line 295 of file ExtReadMPSUtil.h.
References MPSInput::BOUNDS, ExtNameMap::contains(), DEBUG_PARSER, MPSInput::ENDATA, MPSInput::entryIgnored(), MPSInput::field0(), MPSInput::field1(), MPSInput::field2(), MPSInput::field3(), MPSInput::field4(), MPSInput::field5(), ExtNameMap::get(), INFINITY_VALUE, MPSInput::insertName(), ExtLPDSSet::mapRowName, MPSInput::MAX_LINE_LEN, MPSInput::RANGES, MPSInput::readLine(), REAL, ExtLPDSSet::setRhsName(), MPSInput::setRhsName(), MPSInput::setSection(), and MPSInput::syntaxError().
Referenced by readMPS().
static void ExtReadMPSUtil::readRhs (MPSInput & mps, ExtLPDSSet & extDataSet) [inline, static]
Process RHS section.
Definition at line 338 of file ExtReadMPSUtil.h.
References ExtLPDSSet::A, MPSInput::BOUNDS, ExtNameMap::contains(), DEBUG_PARSER, MPSInput::ENDATA, MPSInput::entryIgnored(), MPSInput::field0(), MPSInput::field1(), MPSInput::field2(), MPSInput::field3(), MPSInput::field4(), MPSInput::field5(), ExtNameMap::get(), ExtMatrixA::get_row_attr(), INFINITY_VALUE, MPSInput::insertName(), ExtLPDSSet::mapRowName, MPSInput::MAX_LINE_LEN, MPSInput::RANGES, MPSInput::readLine(), REAL, MatrixARowAttr::set_rhs_value(), ExtMatrixA::set_row_attr(), ExtLPDSSet::setRhsName(), MPSInput::setRhsName(), MPSInput::setSection(), and MPSInput::syntaxError().
static void ExtReadMPSUtil::readRows (MPSInput & mps, ExtLPDSSet & extDataSet) [inline, static]
Process ROWS section.
Definition at line 91 of file ExtReadMPSUtil.h.
References ExtLPDSSet::A, ExtMatrixA::add_row(), MPSInput::COLUMNS, ExtNameMap::contains(), MPSInput::field0(), MPSInput::field1(), MPSInput::field2(), INFINITY_VALUE, ExtLPDSSet::mapRowName, MPSInput::objName(), MPSInput::readLine(), ExtNameMap::set(), PackedRowVector::set_lhs(), PackedRowVector::set_name(), PackedRowVector::set_rhs(), ExtLPDSSet::setObjName(), MPSInput::setObjName(), MPSInput::setSection(), and MPSInput::syntaxError().
static void ExtReadMPSUtil::readRows (MPSInput & mps, ExtLPDSSet & extDataSet) [inline, static]
Process ROWS section.
Definition at line 107 of file ExtReadMPSUtil.h.
References MPSInput::COLUMNS, ExtNameMap::contains(), DEBUG_PARSER, MPSInput::field0(), MPSInput::field1(), MPSInput::field2(), INFINITY_VALUE, ExtLPDSSet::mapRowName, MPSInput::objName(), MPSInput::readLine(), ExtNameMap::set(), PackedRowVector::set_lhs(), PackedRowVector::set_name(), PackedRowVector::set_rhs(), ExtLPDSSet::setObjName(), MPSInput::setObjName(), MPSInput::setSection(), and MPSInput::syntaxError().
Referenced by readMPS().
The documentation for this class was generated from the following files:
local/deprecated/ExtReadMPSUtil.h
local/ExtReadMPSUtil.h