ExtLP: MPSInput Class Reference
MPSInput Class Reference
Detailed Description
Reads MPS input files. A right-hand side for the objective function is allowed but ignored.
Definition at line 45 of file mpsinput.h.
Public Types
Types
enum Section {
NAME, OBJSEN, OBJNAME, ROWS,
COLUMNS, RHS, RANGES, BOUNDS,
ENDATA
}
enum { MAX_LINE_LEN = 256 }
Public Member Functions
Construction / destruction
MPSInput (std::istream &p_input)
virtual ~MPSInput ()
Access
Section section () const
int lineno () const
const char * field0 () const
const char * field1 () const
const char * field2 () const
const char * field3 () const
const char * field4 () const
const char * field5 () const
const char * probName () const
const char * objName () const
bool objSense () const
bool hasError () const
bool isInteger () const
const char * rhsName () const
Modification
void setSection (Section p_section)
void setProbName (const char *p_probname)
void setObjName (const char *p_objname)
void setObjSense (bool sense)
void setRhsName (const char *p_rhsname)
Warnings and Errors
void syntaxError ()
void entryIgnored (const char *what, const char *what_name, const char *entity, const char *entity_name)
Helpers
void clear_from (char *buf, int pos)
fill the line from pos up to column 80 with blanks.
void patch_field (char *buf, int beg, int end)
change all blanks inside a field to PATCH_CHAR.
bool readLine ()
read a MPS format data line and parse the fields.
void insertName (const char *name, bool second=false)
Insert name as field 1 and shift all other fields up.
Private data
Section m_section
std::istream & m_input
the input stream from which the file is read
int m_lineno
line number
bool m_objsense
objctive sense (maximization or minimization)
bool m_has_error
is set to true upon a syntax error
char m_buf [MAX_LINE_LEN]
the line buffer
const char * m_f0
first field in a line
const char * m_f1
second field in a line
const char * m_f2
third field in a line
const char * m_f3
fourth field in a line
const char * m_f4
fifth field in a line
const char * m_f5
sixth field in a line
char m_probname [MAX_LINE_LEN]
problem name
char m_objname [MAX_LINE_LEN]
objective name
char m_rhsname [MAX_LINE_LEN]
rhs column name
bool m_is_integer
bool m_is_new_format
new MPS format?
int m_ignored
Number of already ignored entries.
static const int m_max_ignore = 1000
Maximal number ofp ignored entries for which a warning will be issued.
Member Enumeration Documentation
anonymous enum
Enumerator:
MAX_LINE_LEN
Definition at line 56 of file mpsinput.h.
enum MPSInput::Section
Enumerator:
NAME
OBJSEN
OBJNAME
ROWS
COLUMNS
RHS
RANGES
BOUNDS
ENDATA
Definition at line 52 of file mpsinput.h.
Constructor & Destructor Documentation
MPSInput::MPSInput (std::istream & p_input) [inline, explicit]
Definition at line 114 of file mpsinput.h.
References m_buf, m_f0, m_f1, m_f2, m_f3, m_f4, m_f5, m_objname, and m_probname.
virtual MPSInput::~MPSInput () [inline, virtual]
Definition at line 131 of file mpsinput.h.
References m_f0, m_f1, m_f2, m_f3, m_f4, and m_f5.
Member Function Documentation
void MPSInput::clear_from (char * buf, int pos) [inline]
fill the line from pos up to column 80 with blanks.
Definition at line 259 of file mpsinput.h.
References BLANK.
Referenced by readLine().
void MPSInput::entryIgnored (const char * what, const char * what_name, const char * entity, const char * entity_name) [inline]
Definition at line 237 of file mpsinput.h.
References DEBUG_SIMPLE, m_ignored, m_lineno, and m_max_ignore.
Referenced by ExtReadMPSUtil::readCols(), ReadMPSUtil::readCols(), ReadMPSUtil::readRhs(), and ExtReadMPSUtil::readRhs().
const char* MPSInput::field0 () const [inline]
Definition at line 150 of file mpsinput.h.
References m_f0.
Referenced by ExtReadMPSUtil::readCols(), ReadMPSUtil::readCols(), ExtReadMPSUtil::readName(), ReadMPSUtil::readName(), ExtReadMPSUtil::readObjname(), ReadMPSUtil::readObjname(), ExtReadMPSUtil::readObjsen(), ReadMPSUtil::readObjsen(), ReadMPSUtil::readRhs(), ExtReadMPSUtil::readRhs(), ExtReadMPSUtil::readRows(), and ReadMPSUtil::readRows().
const char* MPSInput::field1 () const [inline]
Definition at line 154 of file mpsinput.h.
References m_f1.
Referenced by ExtReadMPSUtil::readCols(), ReadMPSUtil::readCols(), ExtReadMPSUtil::readName(), ReadMPSUtil::readName(), ExtReadMPSUtil::readObjname(), ReadMPSUtil::readObjname(), ExtReadMPSUtil::readObjsen(), ReadMPSUtil::readObjsen(), ReadMPSUtil::readRhs(), ExtReadMPSUtil::readRhs(), ExtReadMPSUtil::readRows(), and ReadMPSUtil::readRows().
const char* MPSInput::field2 () const [inline]
Definition at line 158 of file mpsinput.h.
References m_f2.
Referenced by ExtReadMPSUtil::readCols(), ReadMPSUtil::readCols(), ReadMPSUtil::readRhs(), ExtReadMPSUtil::readRhs(), ExtReadMPSUtil::readRows(), and ReadMPSUtil::readRows().
const char* MPSInput::field3 () const [inline]
Definition at line 162 of file mpsinput.h.
References m_f3.
Referenced by ExtReadMPSUtil::readCols(), ReadMPSUtil::readCols(), ReadMPSUtil::readRhs(), and ExtReadMPSUtil::readRhs().
const char* MPSInput::field4 () const [inline]
Definition at line 166 of file mpsinput.h.
References m_f4.
Referenced by ExtReadMPSUtil::readCols(), ReadMPSUtil::readCols(), ReadMPSUtil::readRhs(), and ExtReadMPSUtil::readRhs().
const char* MPSInput::field5 () const [inline]
Definition at line 170 of file mpsinput.h.
References m_f5.
Referenced by ExtReadMPSUtil::readCols(), ReadMPSUtil::readCols(), ReadMPSUtil::readRhs(), and ExtReadMPSUtil::readRhs().
bool MPSInput::hasError () const [inline]
Definition at line 186 of file mpsinput.h.
References m_has_error.
void MPSInput::insertName (const char * name, bool second = false) [inline]
Insert name as field 1 and shift all other fields up.
Definition at line 443 of file mpsinput.h.
References m_f1, m_f2, m_f3, m_f4, and m_f5.
Referenced by ReadMPSUtil::readRhs(), and ExtReadMPSUtil::readRhs().
bool MPSInput::isInteger () const [inline]
Definition at line 190 of file mpsinput.h.
References m_is_integer.
int MPSInput::lineno () const [inline]
Definition at line 146 of file mpsinput.h.
References m_lineno.
const char* MPSInput::objName () const [inline]
Definition at line 178 of file mpsinput.h.
References m_objname.
Referenced by ExtReadMPSUtil::readCols(), ReadMPSUtil::readCols(), ReadMPSUtil::readMPS(), ExtReadMPSUtil::readMPS(), ExtReadMPSUtil::readRows(), and ReadMPSUtil::readRows().
bool MPSInput::objSense () const [inline]
Definition at line 182 of file mpsinput.h.
References m_objsense.
Referenced by ExtReadMPSUtil::readMPS().
void MPSInput::patch_field (char * buf, int beg, int end) [inline]
change all blanks inside a field to PATCH_CHAR.
Definition at line 266 of file mpsinput.h.
References BLANK, and PATCH_CHAR.
Referenced by readLine().
const char* MPSInput::probName () const [inline]
Definition at line 174 of file mpsinput.h.
References m_probname.
Referenced by ReadMPSUtil::readMPS(), and ExtReadMPSUtil::readMPS().
bool MPSInput::readLine () [inline]
read a MPS format data line and parse the fields.
Definition at line 279 of file mpsinput.h.
References BLANK, BOUNDS, clear_from(), COLUMNS, m_buf, m_f0, m_f1, m_f2, m_f3, m_f4, m_f5, m_input, m_is_integer, m_is_new_format, m_lineno, m_section, patch_field(), RANGES, and RHS.
Referenced by ExtReadMPSUtil::readCols(), ReadMPSUtil::readCols(), ExtReadMPSUtil::readName(), ReadMPSUtil::readName(), ExtReadMPSUtil::readObjname(), ReadMPSUtil::readObjname(), ExtReadMPSUtil::readObjsen(), ReadMPSUtil::readObjsen(), ReadMPSUtil::readRhs(), ExtReadMPSUtil::readRhs(), ExtReadMPSUtil::readRows(), and ReadMPSUtil::readRows().
const char* MPSInput::rhsName () const [inline]
Definition at line 194 of file mpsinput.h.
References m_rhsname.
Referenced by ReadMPSUtil::readMPS().
Section MPSInput::section () const [inline]
Definition at line 142 of file mpsinput.h.
References m_section.
Referenced by ReadMPSUtil::readMPS(), and ExtReadMPSUtil::readMPS().
void MPSInput::setObjName (const char * p_objname) [inline]
Definition at line 212 of file mpsinput.h.
References m_objname, and MAX_LINE_LEN.
Referenced by ExtReadMPSUtil::readObjname(), ReadMPSUtil::readObjname(), ExtReadMPSUtil::readRows(), and ReadMPSUtil::readRows().
void MPSInput::setObjSense (bool sense) [inline]
Definition at line 217 of file mpsinput.h.
References m_objsense.
Referenced by ExtReadMPSUtil::readObjsen(), and ReadMPSUtil::readObjsen().
void MPSInput::setProbName (const char * p_probname) [inline]
Definition at line 207 of file mpsinput.h.
References m_probname, and MAX_LINE_LEN.
Referenced by ExtReadMPSUtil::readName(), and ReadMPSUtil::readName().
void MPSInput::setRhsName (const char * p_rhsname) [inline]
Definition at line 221 of file mpsinput.h.
References m_rhsname, and MAX_LINE_LEN.
Referenced by ReadMPSUtil::readRhs(), and ExtReadMPSUtil::readRhs().
void MPSInput::setSection (Section p_section) [inline]
Definition at line 203 of file mpsinput.h.
References m_section.
Referenced by ExtReadMPSUtil::readCols(), ReadMPSUtil::readCols(), ExtReadMPSUtil::readName(), ReadMPSUtil::readName(), ExtReadMPSUtil::readObjname(), ReadMPSUtil::readObjname(), ExtReadMPSUtil::readObjsen(), ReadMPSUtil::readObjsen(), ReadMPSUtil::readRhs(), ExtReadMPSUtil::readRhs(), ExtReadMPSUtil::readRows(), and ReadMPSUtil::readRows().
void MPSInput::syntaxError () [inline]
Definition at line 231 of file mpsinput.h.
References ENDATA, m_has_error, and m_section.
Referenced by ExtReadMPSUtil::readCols(), ReadMPSUtil::readCols(), ExtReadMPSUtil::readName(), ReadMPSUtil::readName(), ExtReadMPSUtil::readObjname(), ReadMPSUtil::readObjname(), ExtReadMPSUtil::readObjsen(), ReadMPSUtil::readObjsen(), ReadMPSUtil::readRhs(), ExtReadMPSUtil::readRhs(), ExtReadMPSUtil::readRows(), and ReadMPSUtil::readRows().
Member Data Documentation
char MPSInput::m_buf[MAX_LINE_LEN] [private]
the line buffer
Definition at line 78 of file mpsinput.h.
Referenced by MPSInput(), and readLine().
const char* MPSInput::m_f0 [private]
first field in a line
Definition at line 80 of file mpsinput.h.
Referenced by field0(), MPSInput(), readLine(), and ~MPSInput().
const char* MPSInput::m_f1 [private]
second field in a line
Definition at line 82 of file mpsinput.h.
Referenced by field1(), insertName(), MPSInput(), readLine(), and ~MPSInput().
const char* MPSInput::m_f2 [private]
third field in a line
Definition at line 84 of file mpsinput.h.
Referenced by field2(), insertName(), MPSInput(), readLine(), and ~MPSInput().
const char* MPSInput::m_f3 [private]
fourth field in a line
Definition at line 86 of file mpsinput.h.
Referenced by field3(), insertName(), MPSInput(), readLine(), and ~MPSInput().
const char* MPSInput::m_f4 [private]
fifth field in a line
Definition at line 88 of file mpsinput.h.
Referenced by field4(), insertName(), MPSInput(), readLine(), and ~MPSInput().
const char* MPSInput::m_f5 [private]
sixth field in a line
Definition at line 90 of file mpsinput.h.
Referenced by field5(), insertName(), MPSInput(), readLine(), and ~MPSInput().
bool MPSInput::m_has_error [private]
is set to true upon a syntax error
Definition at line 76 of file mpsinput.h.
Referenced by hasError(), and syntaxError().
int MPSInput::m_ignored [private]
Number of already ignored entries.
Definition at line 102 of file mpsinput.h.
Referenced by entryIgnored().
std::istream& MPSInput::m_input [private]
the input stream from which the file is read
Definition at line 69 of file mpsinput.h.
Referenced by readLine().
bool MPSInput::m_is_integer [private]
Definition at line 98 of file mpsinput.h.
Referenced by isInteger(), and readLine().
bool MPSInput::m_is_new_format [private]
new MPS format?
Definition at line 100 of file mpsinput.h.
Referenced by readLine().
int MPSInput::m_lineno [private]
line number
Definition at line 71 of file mpsinput.h.
Referenced by entryIgnored(), lineno(), and readLine().
const int MPSInput::m_max_ignore = 1000 [static, private]
Maximal number ofp ignored entries for which a warning will be issued.
Definition at line 104 of file mpsinput.h.
Referenced by entryIgnored().
char MPSInput::m_objname[MAX_LINE_LEN] [private]
objective name
Definition at line 94 of file mpsinput.h.
Referenced by MPSInput(), objName(), and setObjName().
bool MPSInput::m_objsense [private]
objctive sense (maximization or minimization)
Definition at line 74 of file mpsinput.h.
Referenced by objSense(), and setObjSense().
char MPSInput::m_probname[MAX_LINE_LEN] [private]
problem name
Definition at line 92 of file mpsinput.h.
Referenced by MPSInput(), probName(), and setProbName().
char MPSInput::m_rhsname[MAX_LINE_LEN] [private]
rhs column name
Definition at line 96 of file mpsinput.h.
Referenced by rhsName(), and setRhsName().
Section MPSInput::m_section [private]
Definition at line 67 of file mpsinput.h.
Referenced by readLine(), section(), setSection(), and syntaxError().
The documentation for this class was generated from the following file:
local/mpsinput.h