ExtLP: ExtFixedMatrix Class Reference
ExtFixedMatrix Class Reference
Detailed Description
Storage Container for Fixed Matrix The contents of the matrix do not change after assignment/initialization Storage is done in column-wise fashion.
Definition at line 40 of file ExtFixedMatrix.h.
Public Member Functions
void add_column (PackedVector p_packed_col)
Adds a new Column into the matrix.
void add_slack_columns (unsigned int n)
Adds n number of slack variables as singleton columns.
PackedVector get_column (unsigned int p_column_idx)
Get an Entire column Send by value... Hence new PackedVector will be created after call.
void store_column (unsigned int p_column_idx, PackedVector &p_packed_col)
Store an Entire column Send by Reference... Hence parameter PackedVector will be affected.
Private Types
typedef
stxxl::VECTOR_GENERATOR
< PackedElement, 1, 1, 10 *1024 *1024 >
::result item_vector
Vector to store the Items onto external memory 10MB page/block size.
Private Attributes
std::vector< ColAttr > m_vct_col_limits
Vector to keep track of columns in the matrix.
item_vector m_vct_disk
std::vector< PackedElement > m_vct_singleton_columns
Vector to keep singleton columns in the matrix.
Member Typedef Documentation
typedef stxxl::VECTOR_GENERATOR<PackedElement, 1, 1, 10 * 1024 * 1024>::result ExtFixedMatrix::item_vector [private]
Vector to store the Items onto external memory 10MB page/block size.
Definition at line 44 of file ExtFixedMatrix.h.
Member Function Documentation
void ExtFixedMatrix::add_column (PackedVector p_packed_col) [inline]
Adds a new Column into the matrix.
Definition at line 53 of file ExtFixedMatrix.h.
References PackedVector< ItemClass >::begin(), PackedVector< ItemClass >::end(), PackedVector< ItemClass >::get_nnz(), m_vct_col_limits, and m_vct_disk.
void ExtFixedMatrix::add_slack_columns (unsigned int n) [inline]
Adds n number of slack variables as singleton columns.
Definition at line 65 of file ExtFixedMatrix.h.
References m_vct_singleton_columns.
PackedVector ExtFixedMatrix::get_column (unsigned int p_column_idx) [inline]
Get an Entire column Send by value... Hence new PackedVector will be created after call.
Limits of the requested column
Definition at line 74 of file ExtFixedMatrix.h.
References PackedVector< ItemClass >::add(), ColAttr::get_end(), PackedElement< ItemClass >::get_index(), ColAttr::get_start(), PackedElement< ItemClass >::get_value(), m_vct_col_limits, and m_vct_disk.
void ExtFixedMatrix::store_column (unsigned int p_column_idx, PackedVector & p_packed_col) [inline]
Store an Entire column Send by Reference... Hence parameter PackedVector will be affected.
Limits of the requested column
Definition at line 88 of file ExtFixedMatrix.h.
References PackedVector< ItemClass >::add(), ColAttr::get_end(), PackedElement< ItemClass >::get_index(), ColAttr::get_start(), PackedElement< ItemClass >::get_value(), m_vct_col_limits, and m_vct_disk.
Member Data Documentation
std::vector<ColAttr> ExtFixedMatrix::m_vct_col_limits [private]
Vector to keep track of columns in the matrix.
Definition at line 48 of file ExtFixedMatrix.h.
Referenced by add_column(), get_column(), and store_column().
item_vector ExtFixedMatrix::m_vct_disk [private]
Definition at line 45 of file ExtFixedMatrix.h.
Referenced by add_column(), get_column(), and store_column().
std::vector< PackedElement > ExtFixedMatrix::m_vct_singleton_columns [private]
Vector to keep singleton columns in the matrix.
Definition at line 50 of file ExtFixedMatrix.h.
Referenced by add_slack_columns().
The documentation for this class was generated from the following file:
local/deprecated/ExtFixedMatrix.h