ExtLP: ColAttr Class Reference
ColAttr Class Reference
Detailed Description
Limits for the start and end of the column in ExtFixedMatrix container The limits to the column is [start, end) start includes and end excludes.
Definition at line 15 of file ExtFixedMatrix.h.
Public Member Functions
ColAttr (unsigned int start, unsigned int end)
unsigned int get_end ()
unsigned int get_start ()
void set_end (unsigned int end)
void set_start (unsigned int start)
Private Attributes
unsigned int end
unsigned int start
Constructor & Destructor Documentation
ColAttr::ColAttr (unsigned int start, unsigned int end) [inline]
Definition at line 19 of file ExtFixedMatrix.h.
References end, and start.
Member Function Documentation
unsigned int ColAttr::get_end () [inline]
Definition at line 32 of file ExtFixedMatrix.h.
References end.
Referenced by ExtFixedMatrix::get_column(), and ExtFixedMatrix::store_column().
unsigned int ColAttr::get_start () [inline]
Definition at line 29 of file ExtFixedMatrix.h.
References start.
Referenced by ExtFixedMatrix::get_column(), and ExtFixedMatrix::store_column().
void ColAttr::set_end (unsigned int end) [inline]
Definition at line 26 of file ExtFixedMatrix.h.
References end.
void ColAttr::set_start (unsigned int start) [inline]
Definition at line 23 of file ExtFixedMatrix.h.
References start.
Member Data Documentation
unsigned int ColAttr::end [private]
Definition at line 17 of file ExtFixedMatrix.h.
Referenced by ColAttr(), get_end(), and set_end().
unsigned int ColAttr::start [private]
Definition at line 17 of file ExtFixedMatrix.h.
Referenced by ColAttr(), get_start(), and set_start().
The documentation for this class was generated from the following file:
local/deprecated/ExtFixedMatrix.h