ExtLP: PackedVector< ItemClass > Class Template Reference
PackedVector< ItemClass > Class Template Reference
Detailed Description
template<class ItemClass>
class PackedVector< ItemClass >
Checks if the vector has sparsity>0.5 and stores in packed form if it does otherwise it will store the complete vector This is the best form to store on disk to reduce the number of I/O(compressed storage)
Container for storing the packed form of the vector. Simple Vector of PackedElements.
Definition at line 49 of file PackedVectorTemplate.h.
Classes
class iterator
PackedVector Iterator for sequential iteration across the elements of the Vector. The Iterator dereferences to a PackedElement (<index, value> pair).
Public Types
typedef LinkedList
< PackedElement >::iterator iterator
typedef LinkedList
< PackedElement< ItemClass >
>::iterator llIterator_type
LinkedList iterator for iterating through Packed Vector.
Public Member Functions
PackedVector (PackedVector &p_packed_vector)
Copy Construction - to check Memory Leak. Do not allow copy constructor. May lead to shallow copy of linked list. This might lead to clearing linked list twice leading to error while freeing.
PackedVector (unsigned int p_size, bool p_is_sorted_by_index=true)
Simple initialization Sorted PackedVector by default.
PackedVector (std::vector< double > &vct)
Complete initialization from std::vector. No more modifications to the existing input vector of elements.
PackedVector (SimpleVector< double > &vct)
Complete initialization from Simple Vector.
PackedVector (int p_realSize, ItemClass p_nullItem)
Packed Vector is Packed by default. Can convert to be unpacked automatically based on sparsity.
PackedVector (int p_realSize, bool p_isPacked, ItemClass p_nullItem)
Forced instantiation of PackedVector This will force the vector to be packed/unpacked.
PackedVector (std::vector< ItemClass > &vct, ItemClass p_nullItem)
Complete initialization. No more modifications to the existing input vector of elements.
~PackedVector ()
Destroying PackedVector.
~PackedVector ()
Destroying PackedVector.
void add (unsigned int index, double value, bool p_index_duplication_check)
Adds the simple <index, value> pair into the vector. Also allows duplication check if given index already exists. Does not allow duplication by default. Ignores add of element if index already exists and index_duplication_check is true. Adds in sorted fashion if the PackedVector is sorted by index.
void add (unsigned int index, ItemClass value, bool p_autoConversion=true)
Adds <index, value> pair into the vector in packed/unpacked form autoConversion can be set or unset to convert among packed and unpacked forms While adding in packed form, it does not check if the index already exists While adding in unpacked form, it overrides the existing value in the index.
iterator begin ()
iterator begin ()
Returns iterator to the beginning(first) element in the vector.
void clear ()
Clear all the elements in the packed vector. Initialize to defaults.
void clear ()
void convertForDiskWrite ()
Best for performing disk read Main intution is to reduce disk I/O.
void convertToPacked ()
Forced conversion to Packed Form.
void convertToUnPacked ()
Forced conversion to Unpacked Form.
void deallocateUnpackedVector ()
Deallocating/Destroying Unpacked Vector.
void displayVector ()
Simple display of vector elements.
void displayVector ()
iterator end ()
iterator end ()
Returns iterator to the ending(last) of the vector.
double get (unsigned int index) const
Not a Efficient operation to randomly access item from Packed Vector. Only need to be done if very much necessary.
unsigned int get_nnz ()
Get the total number of non zeros in the vector.
unsigned int get_real_size ()
Get the max capacity of the vector including the zeros.
float get_sparsity ()
Get the sparsity of the vector.
ItemClass getNullItem ()
Returns the nullItem value pertaining to this type vector.
unsigned int getPackedSize ()
Get the total number of non zeros in the vector.
float getSparsity ()
Get the sparsity of the vector.
int getUnPackedSize ()
Get the max capacity of the vector including the zeros.
void initializeDefaults (unsigned int p_realSize)
Initialization section. PackedVector need to know the real size of vector in advance.
void initializeDefaults (unsigned int p_realSize, ItemClass p_nullItem)
Initialization section PackedVector need to know the real size of vector in advance PackedVector needs to know the element to be ignored(Null Item)
void initializeUnpackedVector ()
Initializing Unpacked Vector Requires initialization with zeros.
bool is_sorted_by_index () const
Returns if the vector is sorted by index.
bool isPacked () const
Gets the packed or unpacked element present in the absolute index position input within corresponding vector When element index is returned to be -1, there is some error Which is either that vector is unintizlized, array out of bounds, or that vector status is unknown.
double operator[] (unsigned int index) const
ItemClass operator[] (unsigned int index) const
void remove (PackedElement packed_element)
Removes an element with given absolute index. Removal is done only if index is present.
void resize (unsigned int p_size)
Improve the size of the exising vector. Expand the vector. The size need to be extended only. the vector cannot shrink. TODO - Check the case in which we might mistakenly shrink the vector.
bool resize (unsigned int p_size)
Returns whether the vector was successfully resized or not.
unsigned int size () const
void sort_by_index ()
Sorts the Packed Vector based on the index. Selection sort is employed for simple implementation. TODO - Simply expand and compress incase it is less of a computation.
void store_from_vector (std::vector< double > &vct)
Complete Initialization. Override the existing vector.
void store_from_vector (SimpleVector< double > &vct)
Complete initialization from Simple Vector.
void storeUnpackedVector (std::vector< ItemClass > &vct)
Store unpacked vector externally into vctUnpack Override the existing vector.
Private Types
typedef LinkedList
< PackedElement< ItemClass > > ll_packedelement_type
Storage for packed compressed vector.
typedef LinkedList< PackedElement > ll_packedelement_type
Storage for packed compressed vector.
Private Attributes
bool m_is_sorted_by_index
Boolean Identifier to specify if the vector is sorted by index.
bool m_isPacked
Identifier for vector to qualify as Packed or Unpacked if true vector is in compressed form else vector is a full-length vector.
unsigned int m_nnz
Total Number of non zeros in the vector.
ItemClass m_nullItem
Null Item Value 0 in case of integer, float, double. Blank incase of string.
unsigned int m_real_size
Max size of the unpacked vector.
unsigned int m_realSize
Max size of the unpacked vector.
ll_packedelement_type m_vct_packed
ll_packedelement_type m_vctPacked
ItemClass * m_vctUnpacked
Storage for unpacked full length vector.
Member Typedef Documentation
template<class ItemClass> typedef LinkedList< PackedElement >::iterator PackedVector< ItemClass >::iterator
Definition at line 74 of file PackedVector.h.
template<class ItemClass> typedef LinkedList< PackedElement<ItemClass> > PackedVector< ItemClass >::ll_packedelement_type [private]
Storage for packed compressed vector.
Definition at line 58 of file PackedVectorTemplate.h.
template<class ItemClass> typedef LinkedList< PackedElement > PackedVector< ItemClass >::ll_packedelement_type [private]
Storage for packed compressed vector.
Definition at line 67 of file PackedVector.h.
template<class ItemClass> typedef LinkedList< PackedElement<ItemClass> >::iterator PackedVector< ItemClass >::llIterator_type
LinkedList iterator for iterating through Packed Vector.
Definition at line 68 of file PackedVectorTemplate.h.
Constructor & Destructor Documentation
template<class ItemClass> PackedVector< ItemClass >::PackedVector (int p_realSize, ItemClass p_nullItem) [inline]
Packed Vector is Packed by default. Can convert to be unpacked automatically based on sparsity.
Definition at line 164 of file PackedVectorTemplate.h.
References PackedVector< ItemClass >::initializeDefaults().
template<class ItemClass> PackedVector< ItemClass >::PackedVector (int p_realSize, bool p_isPacked, ItemClass p_nullItem) [inline]
Forced instantiation of PackedVector This will force the vector to be packed/unpacked.
Definition at line 170 of file PackedVectorTemplate.h.
References PackedVector< ItemClass >::initializeDefaults(), PackedVector< ItemClass >::initializeUnpackedVector(), and PackedVector< ItemClass >::m_isPacked.
template<class ItemClass> PackedVector< ItemClass >::PackedVector (std::vector< ItemClass > & vct, ItemClass p_nullItem) [inline]
Complete initialization. No more modifications to the existing input vector of elements.
Calculating the number of non-zeros Adding the elements into Packed form by default
Definition at line 179 of file PackedVectorTemplate.h.
References PackedVector< ItemClass >::add(), and PackedVector< ItemClass >::initializeDefaults().
template<class ItemClass> PackedVector< ItemClass >::~PackedVector () [inline]
Destroying PackedVector.
Definition at line 190 of file PackedVectorTemplate.h.
References PackedVector< ItemClass >::clear().
template<class ItemClass> PackedVector< ItemClass >::PackedVector (PackedVector< ItemClass > & p_packed_vector) [inline]
Copy Construction - to check Memory Leak. Do not allow copy constructor. May lead to shallow copy of linked list. This might lead to clearing linked list twice leading to error while freeing.
Definition at line 87 of file PackedVector.h.
References DEBUG_WARNING.
template<class ItemClass> PackedVector< ItemClass >::PackedVector (unsigned int p_size, bool p_is_sorted_by_index = true) [inline]
Simple initialization Sorted PackedVector by default.
Definition at line 95 of file PackedVector.h.
References PackedVector< ItemClass >::m_nnz.
template<class ItemClass> PackedVector< ItemClass >::PackedVector (std::vector< double > & vct) [inline]
Complete initialization from std::vector. No more modifications to the existing input vector of elements.
Definition at line 102 of file PackedVector.h.
References PackedVector< ItemClass >::add(), and PackedVector< ItemClass >::initializeDefaults().
template<class ItemClass> PackedVector< ItemClass >::PackedVector (SimpleVector< double > & vct) [inline]
Complete initialization from Simple Vector.
Definition at line 111 of file PackedVector.h.
References PackedVector< ItemClass >::add(), SimpleVector< ItemClass >::get_size(), and PackedVector< ItemClass >::initializeDefaults().
template<class ItemClass> PackedVector< ItemClass >::~PackedVector () [inline]
Destroying PackedVector.
Definition at line 120 of file PackedVector.h.
References PackedVector< ItemClass >::clear().
Member Function Documentation
template<class ItemClass> void PackedVector< ItemClass >::add (unsigned int index, double value, bool p_index_duplication_check) [inline]
Adds the simple <index, value> pair into the vector. Also allows duplication check if given index already exists. Does not allow duplication by default. Ignores add of element if index already exists and index_duplication_check is true. Adds in sorted fashion if the PackedVector is sorted by index.
Definition at line 168 of file PackedVector.h.
References LinkedList< ItemClass >::add(), LinkedList< ItemClass >::add_sorted(), LinkedList< ItemClass >::begin(), DEBUG_WARNING, LinkedList< ItemClass >::end(), PackedVector< ItemClass >::is_sorted_by_index(), PackedVector< ItemClass >::m_nnz, PackedVector< ItemClass >::m_vct_packed, PackedElement< ItemClass >::set_index(), and PackedElement< ItemClass >::set_value().
template<class ItemClass> void PackedVector< ItemClass >::add (unsigned int index, ItemClass value, bool p_autoConversion = true) [inline]
Adds <index, value> pair into the vector in packed/unpacked form autoConversion can be set or unset to convert among packed and unpacked forms While adding in packed form, it does not check if the index already exists While adding in unpacked form, it overrides the existing value in the index.
Definition at line 301 of file PackedVectorTemplate.h.
References LinkedList< ItemClass >::add(), PackedVector< ItemClass >::convertForDiskWrite(), PackedVector< ItemClass >::isPacked(), PackedVector< ItemClass >::m_nnz, PackedVector< ItemClass >::m_nullItem, PackedVector< ItemClass >::m_vctPacked, PackedVector< ItemClass >::m_vctUnpacked, PackedElement< ItemClass >::setIndex(), PackedElement< ItemClass >::setValue(), and PackedVector< ItemClass >::size().
Referenced by PackedVector< ItemClass >::convertToPacked(), PackedVector< ItemClass >::convertToUnPacked(), ExtFixedMatrix::get_column(), PackedVector< ItemClass >::PackedVector(), PackedColVector::set_col_vector(), ExtFixedMatrix::store_column(), ExtMatrixBInverse::store_column(), ExtMatrixA::store_column(), ExtVectorUtil::store_dot_product(), PackedVector< ItemClass >::store_from_vector(), ExtMatrixBInverse::store_row(), ExtVectorUtil::store_scalar_product(), ExtVectorUtil::store_sum(), PackedVector< ItemClass >::storeUnpackedVector(), Test::testExtPackedVector(), and Test::testPackedVector2().
template<class ItemClass> iterator PackedVector< ItemClass >::begin () [inline]
Definition at line 140 of file PackedVectorTemplate.h.
References LinkedList< ItemClass >::begin(), PackedVector< ItemClass >::iterator::initialize(), PackedVector< ItemClass >::m_isPacked, PackedVector< ItemClass >::m_vctPacked, and PackedVector< ItemClass >::m_vctUnpacked.
Referenced by EtaVector::_transform_for_b_inverse(), ExtFixedMatrix::add_column(), ExtMatrixBInverse::add_column(), ExtMatrixA::add_column(), ExtVectorUtil::append_scalar_product(), ExtMatrixBInverse::build_matrix_b_inverse(), ExtSimplex::debug_ak(), ExtSimplex::debug_b_inverse(), ExtSimplex::debug_eta(), ExtSimplex::debug_w(), ExtVectorUtil::sort_packed_vector_based_on_index(), ExtVectorUtil::store_dot_product(), ExtVectorUtil::store_scalar_product(), ExtVectorUtil::store_sum(), ExtPackedVector< ItemClass >::storeFromPackedVector(), ExtVector::storeFromPackedVector(), and Test::testMatrixBInverse().
template<class ItemClass> iterator PackedVector< ItemClass >::begin () [inline]
Returns iterator to the beginning(first) element in the vector.
Definition at line 287 of file PackedVector.h.
References LinkedList< ItemClass >::begin(), and PackedVector< ItemClass >::m_vct_packed.
template<class ItemClass> void PackedVector< ItemClass >::clear () [inline]
Clear all the elements in the packed vector. Initialize to defaults.
Definition at line 281 of file PackedVector.h.
References LinkedList< ItemClass >::clear(), PackedVector< ItemClass >::initializeDefaults(), PackedVector< ItemClass >::m_real_size, and PackedVector< ItemClass >::m_vct_packed.
template<class ItemClass> void PackedVector< ItemClass >::clear () [inline]
Definition at line 391 of file PackedVectorTemplate.h.
References LinkedList< ItemClass >::clear(), PackedVector< ItemClass >::deallocateUnpackedVector(), PackedVector< ItemClass >::initializeDefaults(), PackedVector< ItemClass >::isPacked(), PackedVector< ItemClass >::m_nullItem, PackedVector< ItemClass >::m_realSize, and PackedVector< ItemClass >::m_vctPacked.
Referenced by PackedColVector::set_col_vector(), ExtMatrixBInverse::store_column(), ExtMatrixA::store_column(), PackedVector< ItemClass >::store_from_vector(), ExtMatrixBInverse::store_row(), ExtVectorUtil::store_scalar_product(), and PackedVector< ItemClass >::~PackedVector().
template<class ItemClass> void PackedVector< ItemClass >::convertForDiskWrite () [inline]
Best for performing disk read Main intution is to reduce disk I/O.
Definition at line 289 of file PackedVectorTemplate.h.
References PackedVector< ItemClass >::convertToPacked(), PackedVector< ItemClass >::convertToUnPacked(), PackedVector< ItemClass >::m_nnz, and PackedVector< ItemClass >::m_realSize.
Referenced by PackedVector< ItemClass >::add().
template<class ItemClass> void PackedVector< ItemClass >::convertToPacked () [inline]
Forced conversion to Packed Form.
Definition at line 222 of file PackedVectorTemplate.h.
References PackedVector< ItemClass >::add(), LinkedList< ItemClass >::clear(), PackedVector< ItemClass >::isPacked(), PackedVector< ItemClass >::m_isPacked, PackedVector< ItemClass >::m_nnz, PackedVector< ItemClass >::m_realSize, PackedVector< ItemClass >::m_vctPacked, and PackedVector< ItemClass >::m_vctUnpacked.
Referenced by PackedVector< ItemClass >::convertForDiskWrite().
template<class ItemClass> void PackedVector< ItemClass >::convertToUnPacked () [inline]
Forced conversion to Unpacked Form.
Definition at line 251 of file PackedVectorTemplate.h.
References PackedVector< ItemClass >::add(), LinkedList< ItemClass >::begin(), LinkedList< ItemClass >::clear(), LinkedList< ItemClass >::end(), PackedElement< ItemClass >::getIndex(), PackedElement< ItemClass >::getValue(), PackedVector< ItemClass >::initializeUnpackedVector(), PackedVector< ItemClass >::isPacked(), PackedVector< ItemClass >::m_isPacked, PackedVector< ItemClass >::m_nnz, PackedVector< ItemClass >::m_vctPacked, and PackedVector< ItemClass >::m_vctUnpacked.
Referenced by PackedVector< ItemClass >::convertForDiskWrite().
template<class ItemClass> void PackedVector< ItemClass >::deallocateUnpackedVector () [inline]
Deallocating/Destroying Unpacked Vector.
Definition at line 245 of file PackedVectorTemplate.h.
References PackedVector< ItemClass >::m_vctUnpacked.
Referenced by PackedVector< ItemClass >::clear().
template<class ItemClass> void PackedVector< ItemClass >::displayVector () [inline]
Simple display of vector elements.
Definition at line 297 of file PackedVector.h.
References LinkedList< ItemClass >::begin(), CONSOLE_PRINTLN, LinkedList< ItemClass >::end(), PackedVector< ItemClass >::get_nnz(), PackedVector< ItemClass >::get_real_size(), PackedVector< ItemClass >::get_sparsity(), and PackedVector< ItemClass >::m_vct_packed.
template<class ItemClass> void PackedVector< ItemClass >::displayVector () [inline]
Definition at line 399 of file PackedVectorTemplate.h.
References LinkedList< ItemClass >::begin(), CONSOLE_PRINTLN, LinkedList< ItemClass >::end(), PackedVector< ItemClass >::getSparsity(), PackedVector< ItemClass >::isPacked(), PackedVector< ItemClass >::m_vctPacked, PackedVector< ItemClass >::m_vctUnpacked, and PackedVector< ItemClass >::size().
Referenced by Test::testPackedVector2().
template<class ItemClass> iterator PackedVector< ItemClass >::end () [inline]
Definition at line 145 of file PackedVectorTemplate.h.
References LinkedList< ItemClass >::end(), PackedVector< ItemClass >::iterator::initialize(), PackedVector< ItemClass >::m_isPacked, PackedVector< ItemClass >::m_realSize, PackedVector< ItemClass >::m_vctPacked, and PackedVector< ItemClass >::m_vctUnpacked.
Referenced by EtaVector::_transform_for_b_inverse(), ExtFixedMatrix::add_column(), ExtMatrixBInverse::add_column(), ExtMatrixA::add_column(), ExtVectorUtil::append_scalar_product(), ExtMatrixBInverse::build_matrix_b_inverse(), ExtSimplex::debug_ak(), ExtSimplex::debug_b_inverse(), ExtSimplex::debug_eta(), ExtSimplex::debug_w(), ExtVectorUtil::sort_packed_vector_based_on_index(), ExtVectorUtil::store_dot_product(), ExtVectorUtil::store_scalar_product(), ExtVectorUtil::store_sum(), ExtPackedVector< ItemClass >::storeFromPackedVector(), ExtVector::storeFromPackedVector(), and Test::testMatrixBInverse().
template<class ItemClass> iterator PackedVector< ItemClass >::end () [inline]
Returns iterator to the ending(last) of the vector.
Definition at line 292 of file PackedVector.h.
References LinkedList< ItemClass >::end(), and PackedVector< ItemClass >::m_vct_packed.
template<class ItemClass> double PackedVector< ItemClass >::get (unsigned int index) const [inline]
Not a Efficient operation to randomly access item from Packed Vector. Only need to be done if very much necessary.
Definition at line 218 of file PackedVector.h.
References LinkedList< ItemClass >::begin(), LinkedList< ItemClass >::end(), PackedVector< ItemClass >::is_sorted_by_index(), and PackedVector< ItemClass >::m_vct_packed.
Referenced by PackedColVector::get_row_element().
template<class ItemClass> unsigned int PackedVector< ItemClass >::get_nnz () [inline]
Get the total number of non zeros in the vector.
Definition at line 125 of file PackedVector.h.
References PackedVector< ItemClass >::m_nnz.
Referenced by ExtFixedMatrix::add_column(), ExtMatrixBInverse::add_column(), ExtMatrixA::add_column(), PackedVector< ItemClass >::displayVector(), and ExtPackedVector< ItemClass >::storeFromPackedVector().
template<class ItemClass> unsigned int PackedVector< ItemClass >::get_real_size () [inline]
Get the max capacity of the vector including the zeros.
Definition at line 130 of file PackedVector.h.
References PackedVector< ItemClass >::m_real_size.
Referenced by ExtSimplex::debug_ak(), ExtSimplex::debug_eta(), ExtSimplex::debug_w(), PackedVector< ItemClass >::displayVector(), ExtVectorUtil::sort_packed_vector_based_on_index(), ExtVectorUtil::store_dot_product(), ExtVectorUtil::store_scalar_product(), ExtPackedVector< ItemClass >::storeFromPackedVector(), and ExtVector::storeFromPackedVector().
template<class ItemClass> float PackedVector< ItemClass >::get_sparsity () [inline]
Get the sparsity of the vector.
Definition at line 135 of file PackedVector.h.
References PackedVector< ItemClass >::m_nnz, and PackedVector< ItemClass >::m_real_size.
Referenced by PackedVector< ItemClass >::displayVector(), and ExtVectorUtil::store_dot_product().
template<class ItemClass> ItemClass PackedVector< ItemClass >::getNullItem () [inline]
Returns the nullItem value pertaining to this type vector.
Definition at line 195 of file PackedVectorTemplate.h.
References PackedVector< ItemClass >::m_nullItem.
Referenced by ExtPackedVector< ItemClass >::storeFromPackedVector().
template<class ItemClass> unsigned int PackedVector< ItemClass >::getPackedSize () [inline]
Get the total number of non zeros in the vector.
Definition at line 200 of file PackedVectorTemplate.h.
References PackedVector< ItemClass >::m_nnz.
template<class ItemClass> float PackedVector< ItemClass >::getSparsity () [inline]
Get the sparsity of the vector.
Definition at line 210 of file PackedVectorTemplate.h.
References PackedVector< ItemClass >::m_nnz, and PackedVector< ItemClass >::m_realSize.
Referenced by PackedVector< ItemClass >::displayVector().
template<class ItemClass> int PackedVector< ItemClass >::getUnPackedSize () [inline]
Get the max capacity of the vector including the zeros.
Definition at line 205 of file PackedVectorTemplate.h.
References PackedVector< ItemClass >::m_realSize.
Referenced by ExtPackedVector< ItemClass >::storeFromPackedVector().
template<class ItemClass> void PackedVector< ItemClass >::initializeDefaults (unsigned int p_realSize) [inline]
Initialization section. PackedVector need to know the real size of vector in advance.
Definition at line 78 of file PackedVector.h.
References PackedVector< ItemClass >::m_is_sorted_by_index, PackedVector< ItemClass >::m_nnz, and PackedVector< ItemClass >::m_real_size.
template<class ItemClass> void PackedVector< ItemClass >::initializeDefaults (unsigned int p_realSize, ItemClass p_nullItem) [inline]
Initialization section PackedVector need to know the real size of vector in advance PackedVector needs to know the element to be ignored(Null Item)
Definition at line 154 of file PackedVectorTemplate.h.
References PackedVector< ItemClass >::m_isPacked, PackedVector< ItemClass >::m_nnz, PackedVector< ItemClass >::m_nullItem, PackedVector< ItemClass >::m_realSize, and PackedVector< ItemClass >::m_vctUnpacked.
Referenced by PackedVector< ItemClass >::clear(), PackedVector< ItemClass >::PackedVector(), PackedVector< ItemClass >::store_from_vector(), and PackedVector< ItemClass >::storeUnpackedVector().
template<class ItemClass> void PackedVector< ItemClass >::initializeUnpackedVector () [inline]
Initializing Unpacked Vector Requires initialization with zeros.
Definition at line 238 of file PackedVectorTemplate.h.
References PackedVector< ItemClass >::isPacked(), PackedVector< ItemClass >::m_realSize, and PackedVector< ItemClass >::m_vctUnpacked.
Referenced by PackedVector< ItemClass >::convertToUnPacked(), PackedVector< ItemClass >::PackedVector(), PackedVector< ItemClass >::resize(), and PackedVector< ItemClass >::storeUnpackedVector().
template<class ItemClass> bool PackedVector< ItemClass >::is_sorted_by_index () const [inline]
Returns if the vector is sorted by index.
Definition at line 159 of file PackedVector.h.
References PackedVector< ItemClass >::m_is_sorted_by_index.
Referenced by PackedVector< ItemClass >::add(), and PackedVector< ItemClass >::get().
template<class ItemClass> bool PackedVector< ItemClass >::isPacked () const [inline]
Gets the packed or unpacked element present in the absolute index position input within corresponding vector When element index is returned to be -1, there is some error Which is either that vector is unintizlized, array out of bounds, or that vector status is unknown.
Returns if the status of the vector is packed
Definition at line 365 of file PackedVectorTemplate.h.
References PackedVector< ItemClass >::m_isPacked.
Referenced by PackedVector< ItemClass >::add(), PackedVector< ItemClass >::clear(), PackedVector< ItemClass >::convertToPacked(), PackedVector< ItemClass >::convertToUnPacked(), PackedVector< ItemClass >::displayVector(), PackedVector< ItemClass >::initializeUnpackedVector(), PackedVector< ItemClass >::operator[](), PackedVector< ItemClass >::resize(), PackedVector< ItemClass >::size(), ExtPackedVector< ItemClass >::storeFromPackedVector(), and PackedVector< ItemClass >::storeUnpackedVector().
template<class ItemClass> double PackedVector< ItemClass >::operator[] (unsigned int index) const [inline]
Definition at line 241 of file PackedVector.h.
template<class ItemClass> ItemClass PackedVector< ItemClass >::operator[] (unsigned int index) const [inline]
Definition at line 319 of file PackedVectorTemplate.h.
References LinkedList< ItemClass >::begin(), LinkedList< ItemClass >::end(), PackedVector< ItemClass >::isPacked(), PackedVector< ItemClass >::m_nullItem, PackedVector< ItemClass >::m_realSize, PackedVector< ItemClass >::m_vctPacked, and PackedVector< ItemClass >::m_vctUnpacked.
template<class ItemClass> void PackedVector< ItemClass >::remove (PackedElement packed_element) [inline]
Removes an element with given absolute index. Removal is done only if index is present.
Definition at line 233 of file PackedVector.h.
References PackedVector< ItemClass >::m_nnz, PackedVector< ItemClass >::m_vct_packed, and LinkedList< ItemClass >::remove().
template<class ItemClass> void PackedVector< ItemClass >::resize (unsigned int p_size) [inline]
Improve the size of the exising vector. Expand the vector. The size need to be extended only. the vector cannot shrink. TODO - Check the case in which we might mistakenly shrink the vector.
Definition at line 248 of file PackedVector.h.
References PackedVector< ItemClass >::m_real_size.
template<class ItemClass> bool PackedVector< ItemClass >::resize (unsigned int p_size) [inline]
Returns whether the vector was successfully resized or not.
Definition at line 370 of file PackedVectorTemplate.h.
References DEBUG_ERROR, PackedVector< ItemClass >::initializeUnpackedVector(), PackedVector< ItemClass >::isPacked(), PackedVector< ItemClass >::m_realSize, and PackedVector< ItemClass >::m_vctUnpacked.
Referenced by PackedColVector::set_col_vector(), ExtMatrixBInverse::store_column(), ExtMatrixA::store_column(), ExtMatrixBInverse::store_row(), and ExtVectorUtil::store_scalar_product().
template<class ItemClass> unsigned int PackedVector< ItemClass >::size () const [inline]
Definition at line 213 of file PackedVectorTemplate.h.
References PackedVector< ItemClass >::isPacked(), PackedVector< ItemClass >::m_nnz, and PackedVector< ItemClass >::m_realSize.
Referenced by PackedVector< ItemClass >::add(), PackedVector< ItemClass >::displayVector(), and ExtPackedVector< ItemClass >::storeFromPackedVector().
template<class ItemClass> void PackedVector< ItemClass >::sort_by_index () [inline]
Sorts the Packed Vector based on the index. Selection sort is employed for simple implementation. TODO - Simply expand and compress incase it is less of a computation.
Definition at line 257 of file PackedVector.h.
References LinkedList< ItemClass >::begin(), LinkedList< ItemClass >::end(), and PackedVector< ItemClass >::m_vct_packed.
template<class ItemClass> void PackedVector< ItemClass >::store_from_vector (std::vector< double > & vct) [inline]
Complete Initialization. Override the existing vector.
Definition at line 141 of file PackedVector.h.
References PackedVector< ItemClass >::add(), PackedVector< ItemClass >::clear(), and PackedVector< ItemClass >::initializeDefaults().
template<class ItemClass> void PackedVector< ItemClass >::store_from_vector (SimpleVector< double > & vct) [inline]
Complete initialization from Simple Vector.
Definition at line 150 of file PackedVector.h.
References PackedVector< ItemClass >::add(), PackedVector< ItemClass >::clear(), SimpleVector< ItemClass >::get_size(), and PackedVector< ItemClass >::initializeDefaults().
template<class ItemClass> void PackedVector< ItemClass >::storeUnpackedVector (std::vector< ItemClass > & vct) [inline]
Store unpacked vector externally into vctUnpack Override the existing vector.
Definition at line 272 of file PackedVectorTemplate.h.
References PackedVector< ItemClass >::add(), LinkedList< ItemClass >::clear(), PackedVector< ItemClass >::initializeDefaults(), PackedVector< ItemClass >::initializeUnpackedVector(), PackedVector< ItemClass >::isPacked(), PackedVector< ItemClass >::m_isPacked, PackedVector< ItemClass >::m_nullItem, PackedVector< ItemClass >::m_vctPacked, and PackedVector< ItemClass >::m_vctUnpacked.
Member Data Documentation
template<class ItemClass> bool PackedVector< ItemClass >::m_is_sorted_by_index [private]
Boolean Identifier to specify if the vector is sorted by index.
Definition at line 70 of file PackedVector.h.
Referenced by PackedVector< ItemClass >::initializeDefaults(), and PackedVector< ItemClass >::is_sorted_by_index().
template<class ItemClass> bool PackedVector< ItemClass >::m_isPacked [private]
Identifier for vector to qualify as Packed or Unpacked if true vector is in compressed form else vector is a full-length vector.
Definition at line 63 of file PackedVectorTemplate.h.
Referenced by PackedVector< ItemClass >::begin(), PackedVector< ItemClass >::convertToPacked(), PackedVector< ItemClass >::convertToUnPacked(), PackedVector< ItemClass >::end(), PackedVector< ItemClass >::initializeDefaults(), PackedVector< ItemClass >::isPacked(), PackedVector< ItemClass >::PackedVector(), and PackedVector< ItemClass >::storeUnpackedVector().
template<class ItemClass> unsigned int PackedVector< ItemClass >::m_nnz [private]
Total Number of non zeros in the vector.
Definition at line 52 of file PackedVectorTemplate.h.
Referenced by PackedVector< ItemClass >::add(), PackedVector< ItemClass >::convertForDiskWrite(), PackedVector< ItemClass >::convertToPacked(), PackedVector< ItemClass >::convertToUnPacked(), PackedVector< ItemClass >::get_nnz(), PackedVector< ItemClass >::get_sparsity(), PackedVector< ItemClass >::getPackedSize(), PackedVector< ItemClass >::getSparsity(), PackedVector< ItemClass >::initializeDefaults(), PackedVector< ItemClass >::PackedVector(), PackedVector< ItemClass >::remove(), and PackedVector< ItemClass >::size().
template<class ItemClass> ItemClass PackedVector< ItemClass >::m_nullItem [private]
Null Item Value 0 in case of integer, float, double. Blank incase of string.
Definition at line 65 of file PackedVectorTemplate.h.
Referenced by PackedVector< ItemClass >::add(), PackedVector< ItemClass >::clear(), PackedVector< ItemClass >::getNullItem(), PackedVector< ItemClass >::initializeDefaults(), PackedVector< ItemClass >::operator[](), and PackedVector< ItemClass >::storeUnpackedVector().
template<class ItemClass> unsigned int PackedVector< ItemClass >::m_real_size [private]
Max size of the unpacked vector.
Definition at line 65 of file PackedVector.h.
Referenced by PackedVector< ItemClass >::clear(), PackedVector< ItemClass >::get_real_size(), PackedVector< ItemClass >::get_sparsity(), PackedVector< ItemClass >::initializeDefaults(), and PackedVector< ItemClass >::resize().
template<class ItemClass> unsigned int PackedVector< ItemClass >::m_realSize [private]
Max size of the unpacked vector.
Definition at line 54 of file PackedVectorTemplate.h.
Referenced by PackedVector< ItemClass >::clear(), PackedVector< ItemClass >::convertForDiskWrite(), PackedVector< ItemClass >::convertToPacked(), PackedVector< ItemClass >::end(), PackedVector< ItemClass >::getSparsity(), PackedVector< ItemClass >::getUnPackedSize(), PackedVector< ItemClass >::initializeDefaults(), PackedVector< ItemClass >::initializeUnpackedVector(), PackedVector< ItemClass >::operator[](), PackedVector< ItemClass >::resize(), and PackedVector< ItemClass >::size().
template<class ItemClass> ll_packedelement_type PackedVector< ItemClass >::m_vct_packed [private]
Definition at line 68 of file PackedVector.h.
Referenced by PackedVector< ItemClass >::add(), PackedVector< ItemClass >::begin(), PackedVector< ItemClass >::clear(), PackedVector< ItemClass >::displayVector(), PackedVector< ItemClass >::end(), PackedVector< ItemClass >::get(), PackedVector< ItemClass >::remove(), and PackedVector< ItemClass >::sort_by_index().
template<class ItemClass> ll_packedelement_type PackedVector< ItemClass >::m_vctPacked [private]
Definition at line 59 of file PackedVectorTemplate.h.
Referenced by PackedVector< ItemClass >::add(), PackedVector< ItemClass >::begin(), PackedVector< ItemClass >::clear(), PackedVector< ItemClass >::convertToPacked(), PackedVector< ItemClass >::convertToUnPacked(), PackedVector< ItemClass >::displayVector(), PackedVector< ItemClass >::end(), PackedVector< ItemClass >::operator[](), and PackedVector< ItemClass >::storeUnpackedVector().
template<class ItemClass> ItemClass* PackedVector< ItemClass >::m_vctUnpacked [private]
Storage for unpacked full length vector.
Definition at line 56 of file PackedVectorTemplate.h.
Referenced by PackedVector< ItemClass >::add(), PackedVector< ItemClass >::begin(), PackedVector< ItemClass >::convertToPacked(), PackedVector< ItemClass >::convertToUnPacked(), PackedVector< ItemClass >::deallocateUnpackedVector(), PackedVector< ItemClass >::displayVector(), PackedVector< ItemClass >::end(), PackedVector< ItemClass >::initializeDefaults(), PackedVector< ItemClass >::initializeUnpackedVector(), PackedVector< ItemClass >::operator[](), PackedVector< ItemClass >::resize(), and PackedVector< ItemClass >::storeUnpackedVector().
The documentation for this class was generated from the following files:
local/deprecated/PackedVectorTemplate.h
local/PackedVector.h