ExtLP: ExtMatrixBInverse Class Reference
ExtMatrixBInverse Class Reference
Detailed Description
Storage Container for Fixed Matrix The contents of the matrix do not change after assignment/initialization Storage is done in both column-wise and row-wise fashion.
Definition at line 98 of file ExtMatrixBInverse.h.
Public Types
typedef MatrixBInverseColAttr ColAttr
typedef MatrixBInverseRowAttr RowAttr
Public Member Functions
ExtMatrixBInverse (bool p_is_row_build_necessary=false)
Simple Initialization.
void add_column (PackedVector &p_packed_vector, unsigned int p_column_index)
Adds a new column into the matrix Input column parameters include the Matrix A column index and the column values.
void add_row_element (unsigned int row_index, PackedElement packed_element)
Adds a new row element into the matrix Clumsy operation - Might involve random block fetching without any locality of reference.
void build_matrix_b_inverse (ExtMatrixA &A, SimpleVector< unsigned int > base_col_indices)
Building the matrix from Matrix A and the basis col matrix Initial Assumption AX + S = b making S (Identity matrix)to be the B and B inverse TODO - Always it is not fair to choose identity matrix as base. Choose wisely.
void clear_matrix_b_inverse ()
Clearing the whole BInverse container.
ColAttr get_col_attr (unsigned int p_col_index)
Returns the column attributes associated with the p_col_index.
float get_col_density (unsigned int p_col_index)
Returns the density of given p_col_index column. Use this to get sparsity instead of fetching entire column.
unsigned int get_col_nnz (unsigned int p_col_index)
Returns the number of non-zeros for a given p_col_index column Use this to get nnz instead of fetching entire column.
float get_col_sparsity (unsigned int p_col_index)
Returns the sparsity of given p_col_index column. Use this to get sparsity instead of fetching entire column.
unsigned int get_columns_count ()
Returns the columns count - Total number of columns in the matrix.
unsigned int get_element_size ()
float get_overall_density ()
Returns the overall density of the matrix.
float get_overall_nnz ()
Returns the overall number of nonzeros of the matrix.
float get_overall_sparsity ()
Returns the overall sparsity of the matrix.
RowAttr get_row_attr (unsigned int p_row_index)
gets the row attributes specific to a column
unsigned int get_rows_count ()
Returns the rows count - Total number of rows in the matrix.
void pre_calculate_row_structure ()
PreCalculation of row-wise matrix storage structure The capacity_end refers to the end index till which the column can be reached start and end by default refer to the start index of column. (empty column)
void set_col_attr (unsigned int p_col_index, ColAttr p_col_attr)
Sets the input column attributes associated with the p_col_index.
void set_row_attr (unsigned int p_row_index, RowAttr p_row_attr)
sets the row attributes of a column
void store_column (unsigned int p_column_idx, PackedVector &p_packed_col)
Store an Entire column of basis inverse matrix Send by Reference... Hence parameter PackedVector will be affected.
void store_row (unsigned int p_row_idx, PackedVector &p_packed_row)
Store an Entire row of the Basis inverse matrix Send by Reference... Hence parameter PackedVector will be affected.
void swap (ExtMatrixBInverse &other)
Private Types
typedef
stxxl::VECTOR_GENERATOR
< MatrixBInverseColAttr, 1, 1,(10 *1024 *1024) >
::resul col_data_vector)
Vector to keep track of columns in the matrix.
typedef
stxxl::VECTOR_GENERATOR
< PackedElement, 1, 10,(10 *1024 *1024) >
::resul item_col_vector)
Vector to store the Items onto external memory template parameters<ValueType, PageSize, CachePages, BlockSize, AllocStratg>
typedef
stxxl::VECTOR_GENERATOR
< PackedElement, 1, 10,(10 *1024 *1024) >
::resul item_row_vector)
typedef
stxxl::VECTOR_GENERATOR
< MatrixBInverseRowAttr, 1, 1,(10 *1024 *1024) >
::resul row_data_vector)
Vector to keep track of rows in the matrix.
Private Attributes
bool m_is_row_build_necessary
Indicator whether row-wise storage is necessary.
col_data_vector m_vct_col_attr
item_col_vector m_vct_col_disk
Storage for column-wise representation.
const col_data_vector & m_vct_read_only_col_attr
const item_col_vector & m_vct_read_only_col_disk
const row_data_vector & m_vct_read_only_row_attr
const item_row_vector & m_vct_read_only_row_disk
row_data_vector m_vct_row_attr
item_row_vector m_vct_row_disk
Storage for row-wise representation.
Member Typedef Documentation
typedef stxxl::VECTOR_GENERATOR<MatrixBInverseColAttr, 1, 1, (10*1024*1024) >::resul ExtMatrixBInverse::col_data_vector) [private]
Vector to keep track of columns in the matrix.
Definition at line 111 of file ExtMatrixBInverse.h.
typedef MatrixBInverseColAttr ExtMatrixBInverse::ColAttr
Definition at line 123 of file ExtMatrixBInverse.h.
typedef stxxl::VECTOR_GENERATOR<PackedElement, 1 , 10 , (10*1024*1024) >::resul ExtMatrixBInverse::item_col_vector) [private]
Vector to store the Items onto external memory template parameters<ValueType, PageSize, CachePages, BlockSize, AllocStratg>
Definition at line 102 of file ExtMatrixBInverse.h.
typedef stxxl::VECTOR_GENERATOR<PackedElement, 1 , 10 , (10*1024*1024) >::resul ExtMatrixBInverse::item_row_vector) [private]
Definition at line 103 of file ExtMatrixBInverse.h.
typedef stxxl::VECTOR_GENERATOR<MatrixBInverseRowAttr, 1, 1, (10*1024*1024) >::resul ExtMatrixBInverse::row_data_vector) [private]
Vector to keep track of rows in the matrix.
Definition at line 115 of file ExtMatrixBInverse.h.
typedef MatrixBInverseRowAttr ExtMatrixBInverse::RowAttr
Definition at line 125 of file ExtMatrixBInverse.h.
Constructor & Destructor Documentation
ExtMatrixBInverse::ExtMatrixBInverse (bool p_is_row_build_necessary = false) [inline]
Simple Initialization.
Definition at line 128 of file ExtMatrixBInverse.h.
Member Function Documentation
void ExtMatrixBInverse::add_column (PackedVector & p_packed_vector, unsigned int p_column_index) [inline]
Adds a new column into the matrix Input column parameters include the Matrix A column index and the column values.
Definition at line 142 of file ExtMatrixBInverse.h.
References PackedVector< ItemClass >::begin(), PackedVector< ItemClass >::end(), get_columns_count(), MatrixBInverseColAttr::get_end(), PackedElement< ItemClass >::get_index(), PackedVector< ItemClass >::get_nnz(), get_rows_count(), m_is_row_build_necessary, m_vct_col_attr, m_vct_col_disk, m_vct_row_attr, and MatrixBInverseColAttr::set_a_col_index().
Referenced by build_matrix_b_inverse(), and ExtVectorUtil::update_basis_inverse().
void ExtMatrixBInverse::add_row_element (unsigned int row_index, PackedElement packed_element) [inline]
Adds a new row element into the matrix Clumsy operation - Might involve random block fetching without any locality of reference.
Definition at line 243 of file ExtMatrixBInverse.h.
References MatrixBInverseRowAttr::get_capacity_end(), MatrixBInverseRowAttr::get_end(), m_vct_row_attr, m_vct_row_disk, and MatrixBInverseRowAttr::set_end().
Referenced by build_matrix_b_inverse().
void ExtMatrixBInverse::build_matrix_b_inverse (ExtMatrixA & A, SimpleVector< unsigned int > base_col_indices) [inline]
Building the matrix from Matrix A and the basis col matrix Initial Assumption AX + S = b making S (Identity matrix)to be the B and B inverse TODO - Always it is not fair to choose identity matrix as base. Choose wisely.
Definition at line 338 of file ExtMatrixBInverse.h.
References add_column(), add_row_element(), PackedVector< ItemClass >::begin(), PackedVector< ItemClass >::end(), get_columns_count(), ExtMatrixA::get_rows_count(), get_rows_count(), SimpleVector< ItemClass >::get_size(), m_is_row_build_necessary, pre_calculate_row_structure(), PackedElement< ItemClass >::set_index(), PackedElement< ItemClass >::set_value(), store_column(), and ExtMatrixA::store_column().
Referenced by ExtSimplex::init_simplex().
void ExtMatrixBInverse::clear_matrix_b_inverse () [inline]
Clearing the whole BInverse container.
Definition at line 301 of file ExtMatrixBInverse.h.
References m_is_row_build_necessary, m_vct_col_attr, m_vct_col_disk, m_vct_row_attr, and m_vct_row_disk.
Referenced by ExtVectorUtil::update_basis_inverse().
ColAttr ExtMatrixBInverse::get_col_attr (unsigned int p_col_index) [inline]
Returns the column attributes associated with the p_col_index.
Definition at line 184 of file ExtMatrixBInverse.h.
References m_vct_read_only_col_attr.
Referenced by ExtSimplex::debug_b_inverse(), Test::testMatrixBInverse(), ExtVectorUtil::update_basis_inverse(), and ExtSimplex::update_simplex_iteration().
float ExtMatrixBInverse::get_col_density (unsigned int p_col_index) [inline]
Returns the density of given p_col_index column. Use this to get sparsity instead of fetching entire column.
Definition at line 210 of file ExtMatrixBInverse.h.
References get_col_nnz(), and get_rows_count().
unsigned int ExtMatrixBInverse::get_col_nnz (unsigned int p_col_index) [inline]
Returns the number of non-zeros for a given p_col_index column Use this to get nnz instead of fetching entire column.
Definition at line 195 of file ExtMatrixBInverse.h.
References MatrixBInverseColAttr::get_end(), MatrixBInverseColAttr::get_start(), and m_vct_read_only_col_attr.
Referenced by get_col_density(), get_col_sparsity(), and get_overall_nnz().
float ExtMatrixBInverse::get_col_sparsity (unsigned int p_col_index) [inline]
Returns the sparsity of given p_col_index column. Use this to get sparsity instead of fetching entire column.
Definition at line 202 of file ExtMatrixBInverse.h.
References get_col_nnz(), and get_rows_count().
unsigned int ExtMatrixBInverse::get_columns_count () [inline]
Returns the columns count - Total number of columns in the matrix.
Definition at line 189 of file ExtMatrixBInverse.h.
References m_vct_read_only_col_attr.
Referenced by add_column(), build_matrix_b_inverse(), ExtSimplex::debug_b_inverse(), get_overall_density(), get_overall_nnz(), get_overall_sparsity(), ExtVectorUtil::store_dot_product(), store_row(), Test::testMatrixBInverse(), and ExtVectorUtil::update_basis_inverse().
unsigned int ExtMatrixBInverse::get_element_size () [inline]
Definition at line 296 of file ExtMatrixBInverse.h.
References m_vct_read_only_col_disk.
Referenced by ExtSimplex::get_expected_io_currently(), ExtSimplex::get_expected_read_io_currently(), and ExtSimplex::get_expected_write_io_currently().
float ExtMatrixBInverse::get_overall_density () [inline]
Returns the overall density of the matrix.
Definition at line 328 of file ExtMatrixBInverse.h.
References get_columns_count(), get_overall_nnz(), and get_rows_count().
Referenced by ExtSimplex::print_io_statistics().
float ExtMatrixBInverse::get_overall_nnz () [inline]
Returns the overall number of nonzeros of the matrix.
Definition at line 311 of file ExtMatrixBInverse.h.
References get_col_nnz(), and get_columns_count().
Referenced by ExtSimplex::get_expected_io_currently(), ExtSimplex::get_expected_read_io_currently(), ExtSimplex::get_expected_write_io_currently(), get_overall_density(), get_overall_sparsity(), and ExtSimplex::print_io_statistics().
float ExtMatrixBInverse::get_overall_sparsity () [inline]
Returns the overall sparsity of the matrix.
Definition at line 321 of file ExtMatrixBInverse.h.
References get_columns_count(), get_overall_nnz(), and get_rows_count().
RowAttr ExtMatrixBInverse::get_row_attr (unsigned int p_row_index) [inline]
gets the row attributes specific to a column
Definition at line 281 of file ExtMatrixBInverse.h.
References m_vct_read_only_row_attr.
unsigned int ExtMatrixBInverse::get_rows_count () [inline]
Returns the rows count - Total number of rows in the matrix.
Definition at line 272 of file ExtMatrixBInverse.h.
References m_is_row_build_necessary, m_vct_read_only_col_attr, and m_vct_read_only_row_attr.
Referenced by add_column(), build_matrix_b_inverse(), ExtSimplex::debug_b_inverse(), get_col_density(), get_col_sparsity(), get_overall_density(), get_overall_sparsity(), store_column(), ExtVectorUtil::store_dot_product(), Test::testMatrixBInverse(), and ExtVectorUtil::update_basis_inverse().
void ExtMatrixBInverse::pre_calculate_row_structure () [inline]
PreCalculation of row-wise matrix storage structure The capacity_end refers to the end index till which the column can be reached start and end by default refer to the start index of column. (empty column)
Definition at line 227 of file ExtMatrixBInverse.h.
References m_vct_row_attr, MatrixBInverseRowAttr::set_capacity_end(), MatrixBInverseRowAttr::set_end(), set_row_attr(), and MatrixBInverseRowAttr::set_start().
Referenced by build_matrix_b_inverse().
void ExtMatrixBInverse::set_col_attr (unsigned int p_col_index, ColAttr p_col_attr) [inline]
Sets the input column attributes associated with the p_col_index.
Definition at line 217 of file ExtMatrixBInverse.h.
References m_vct_col_attr.
Referenced by ExtSimplex::update_simplex_iteration().
void ExtMatrixBInverse::set_row_attr (unsigned int p_row_index, RowAttr p_row_attr) [inline]
sets the row attributes of a column
Definition at line 287 of file ExtMatrixBInverse.h.
References m_vct_row_attr.
Referenced by pre_calculate_row_structure().
void ExtMatrixBInverse::store_column (unsigned int p_column_idx, PackedVector & p_packed_col) [inline]
Store an Entire column of basis inverse matrix Send by Reference... Hence parameter PackedVector will be affected.
Definition at line 170 of file ExtMatrixBInverse.h.
References PackedVector< ItemClass >::add(), PackedVector< ItemClass >::clear(), MatrixBInverseColAttr::get_end(), PackedElement< ItemClass >::get_index(), get_rows_count(), MatrixBInverseColAttr::get_start(), PackedElement< ItemClass >::get_value(), m_vct_read_only_col_attr, m_vct_read_only_col_disk, and PackedVector< ItemClass >::resize().
Referenced by build_matrix_b_inverse(), ExtSimplex::debug_b_inverse(), ExtVectorUtil::store_dot_product(), Test::testMatrixBInverse(), and ExtVectorUtil::update_basis_inverse().
void ExtMatrixBInverse::store_row (unsigned int p_row_idx, PackedVector & p_packed_row) [inline]
Store an Entire row of the Basis inverse matrix Send by Reference... Hence parameter PackedVector will be affected.
Definition at line 258 of file ExtMatrixBInverse.h.
References PackedVector< ItemClass >::add(), PackedVector< ItemClass >::clear(), get_columns_count(), MatrixBInverseRowAttr::get_end(), PackedElement< ItemClass >::get_index(), MatrixBInverseRowAttr::get_start(), PackedElement< ItemClass >::get_value(), m_vct_read_only_row_attr, m_vct_read_only_row_disk, and PackedVector< ItemClass >::resize().
void ExtMatrixBInverse::swap (ExtMatrixBInverse & other) [inline]
Definition at line 369 of file ExtMatrixBInverse.h.
References m_is_row_build_necessary, m_vct_col_attr, m_vct_col_disk, m_vct_row_attr, and m_vct_row_disk.
Referenced by ExtVectorUtil::update_basis_inverse().
Member Data Documentation
bool ExtMatrixBInverse::m_is_row_build_necessary [private]
Indicator whether row-wise storage is necessary.
Definition at line 119 of file ExtMatrixBInverse.h.
Referenced by add_column(), build_matrix_b_inverse(), clear_matrix_b_inverse(), get_rows_count(), and swap().
col_data_vector ExtMatrixBInverse::m_vct_col_attr [private]
Definition at line 112 of file ExtMatrixBInverse.h.
Referenced by add_column(), clear_matrix_b_inverse(), set_col_attr(), and swap().
item_col_vector ExtMatrixBInverse::m_vct_col_disk [private]
Storage for column-wise representation.
Definition at line 105 of file ExtMatrixBInverse.h.
Referenced by add_column(), clear_matrix_b_inverse(), and swap().
const col_data_vector& ExtMatrixBInverse::m_vct_read_only_col_attr [private]
Definition at line 113 of file ExtMatrixBInverse.h.
Referenced by get_col_attr(), get_col_nnz(), get_columns_count(), get_rows_count(), and store_column().
const item_col_vector& ExtMatrixBInverse::m_vct_read_only_col_disk [private]
Definition at line 106 of file ExtMatrixBInverse.h.
Referenced by get_element_size(), and store_column().
const row_data_vector& ExtMatrixBInverse::m_vct_read_only_row_attr [private]
Definition at line 117 of file ExtMatrixBInverse.h.
Referenced by get_row_attr(), get_rows_count(), and store_row().
const item_row_vector& ExtMatrixBInverse::m_vct_read_only_row_disk [private]
Definition at line 109 of file ExtMatrixBInverse.h.
Referenced by store_row().
row_data_vector ExtMatrixBInverse::m_vct_row_attr [private]
Definition at line 116 of file ExtMatrixBInverse.h.
Referenced by add_column(), add_row_element(), clear_matrix_b_inverse(), pre_calculate_row_structure(), set_row_attr(), and swap().
item_row_vector ExtMatrixBInverse::m_vct_row_disk [private]
Storage for row-wise representation.
Definition at line 108 of file ExtMatrixBInverse.h.
Referenced by add_row_element(), clear_matrix_b_inverse(), and swap().
The documentation for this class was generated from the following file:
local/ExtMatrixBInverse.h