ExtLP: ExtStringVector Class Reference
ExtStringVector Class Reference
Detailed Description
Definition at line 13 of file ExtStringVector.h.
Public Member Functions
ExtStringVector ()
void add (unsigned int i, std::string str)
std::string get (unsigned int i)
void setSize (unsigned int p_size)
unsigned int size ()
Static Public Member Functions
static void test ()
Private Attributes
string_vector vctDisk
Constructor & Destructor Documentation
ExtStringVector::ExtStringVector () [inline]
Definition at line 17 of file ExtStringVector.h.
Member Function Documentation
void ExtStringVector::add (unsigned int i, std::string str) [inline]
Definition at line 19 of file ExtStringVector.h.
References vctDisk.
Referenced by test().
std::string ExtStringVector::get (unsigned int i) [inline]
Definition at line 24 of file ExtStringVector.h.
References vctDisk.
Referenced by test().
void ExtStringVector::setSize (unsigned int p_size) [inline]
Definition at line 30 of file ExtStringVector.h.
References vctDisk.
Referenced by test().
unsigned int ExtStringVector::size () [inline]
Definition at line 27 of file ExtStringVector.h.
References vctDisk.
static void ExtStringVector::test () [inline, static]
Definition at line 33 of file ExtStringVector.h.
References add(), DEBUG, get(), and setSize().
Member Data Documentation
string_vector ExtStringVector::vctDisk [private]
Definition at line 15 of file ExtStringVector.h.
Referenced by add(), get(), setSize(), and size().
The documentation for this class was generated from the following file:
local/deprecated/ExtStringVector.h