ExtLP: SimpleVector< ItemClass > Class Template Reference
SimpleVector< ItemClass > Class Template Reference
Detailed Description
template<class ItemClass>
class SimpleVector< ItemClass >
Simple Vector container for better storage allocation and deallocation Generic Vector to store any type of data.
Definition at line 15 of file SimpleVector.h.
Public Member Functions
SimpleVector (unsigned int p_size)
Basic initialization with empty vector.
SimpleVector (SimpleVector &other)
Deep copy for SimpleVector copy constructor Shallow copy would cause problems for SimpleVector.
~SimpleVector ()
Simple Deallocation.
void add (unsigned int p_index, ItemClass p_value, bool p_allow_expansion=false)
Adds an given element at specified index location Expansion is not allowed by default.
void clear ()
Remove/Clear all the elements of the vector.
ItemClass get_element (unsigned int p_index) const
Gets the item present at the given p_index.
unsigned int get_size () const
Gets the size of the vector.
void nullify ()
void operator= (const SimpleVector &other)
Deep copy when during assignment.
ItemClass & operator[] (unsigned int p_index)
operator[] overriding for fetching a value
void resize (unsigned int p_size, bool p_allow_shrink=false)
Resizes the vector with an option to allow shrinking if necessary Shrinking is not allowed by default.
Private Attributes
unsigned int m_size
Size of the vector.
ItemClass * m_vct_values
Fixed array of ItemClass values.
Constructor & Destructor Documentation
template<class ItemClass> SimpleVector< ItemClass >::SimpleVector (unsigned int p_size) [inline]
Basic initialization with empty vector.
Basic initialization with fixed size
Definition at line 30 of file SimpleVector.h.
template<class ItemClass> SimpleVector< ItemClass >::SimpleVector (SimpleVector< ItemClass > & other) [inline]
Deep copy for SimpleVector copy constructor Shallow copy would cause problems for SimpleVector.
Definition at line 39 of file SimpleVector.h.
template<class ItemClass> SimpleVector< ItemClass >::~SimpleVector () [inline]
Simple Deallocation.
Definition at line 48 of file SimpleVector.h.
Member Function Documentation
template<class ItemClass> void SimpleVector< ItemClass >::add (unsigned int p_index, ItemClass p_value, bool p_allow_expansion = false) [inline]
Adds an given element at specified index location Expansion is not allowed by default.
Definition at line 95 of file SimpleVector.h.
Referenced by ExtVectorUtil::append_scalar_product(), ExtMatrixA::standardize_matrix(), and ExtVectorUtil::store_sum().
template<class ItemClass> void SimpleVector< ItemClass >::clear () [inline]
Remove/Clear all the elements of the vector.
Definition at line 123 of file SimpleVector.h.
Referenced by SimpleVector< unsigned int >::operator=(), ExtMatrixA::store_col_objective_values(), ExtMatrixA::store_row_rhs_values(), and SimpleVector< unsigned int >::~SimpleVector().
template<class ItemClass> ItemClass SimpleVector< ItemClass >::get_element (unsigned int p_index) const [inline]
Gets the item present at the given p_index.
Definition at line 106 of file SimpleVector.h.
Referenced by ExtVectorUtil::append_scalar_product(), and SimpleVector< unsigned int >::operator=().
template<class ItemClass> unsigned int SimpleVector< ItemClass >::get_size () const [inline]
Gets the size of the vector.
Definition at line 112 of file SimpleVector.h.
Referenced by ExtMatrixBInverse::build_matrix_b_inverse(), ExtSimplex::debug_base_col_indices(), ExtSimplex::debug_objective_values(), ExtSimplex::debug_rhs(), ExtSimplex::debug_rhs_values(), ExtSimplex::debug_y(), ExtSimplex::get_basis_dimension(), SimpleVector< unsigned int >::operator=(), PackedVector< ItemClass >::PackedVector(), SimpleVector< unsigned int >::SimpleVector(), ExtMatrixA::store_col_objective_values(), ExtVectorUtil::store_dot_product(), PackedVector< ItemClass >::store_from_vector(), and ExtSimplex::update_simplex_iteration().
template<class ItemClass> void SimpleVector< ItemClass >::nullify () [inline]
Definition at line 87 of file SimpleVector.h.
template<class ItemClass> void SimpleVector< ItemClass >::operator= (const SimpleVector< ItemClass > & other) [inline]
Deep copy when during assignment.
Definition at line 53 of file SimpleVector.h.
template<class ItemClass> ItemClass& SimpleVector< ItemClass >::operator[] (unsigned int p_index) [inline]
operator[] overriding for fetching a value
Definition at line 117 of file SimpleVector.h.
template<class ItemClass> void SimpleVector< ItemClass >::resize (unsigned int p_size, bool p_allow_shrink = false) [inline]
Resizes the vector with an option to allow shrinking if necessary Shrinking is not allowed by default.
Definition at line 64 of file SimpleVector.h.
Referenced by SimpleVector< unsigned int >::add(), ExtMatrixA::store_col_objective_values(), and ExtMatrixA::store_row_rhs_values().
Member Data Documentation
template<class ItemClass> unsigned int SimpleVector< ItemClass >::m_size [private]
Size of the vector.
Definition at line 20 of file SimpleVector.h.
Referenced by SimpleVector< unsigned int >::add(), SimpleVector< unsigned int >::clear(), SimpleVector< unsigned int >::get_element(), SimpleVector< unsigned int >::get_size(), SimpleVector< unsigned int >::nullify(), SimpleVector< unsigned int >::operator=(), SimpleVector< unsigned int >::operator[](), SimpleVector< unsigned int >::resize(), and SimpleVector< unsigned int >::SimpleVector().
template<class ItemClass> ItemClass* SimpleVector< ItemClass >::m_vct_values [private]
Fixed array of ItemClass values.
Definition at line 18 of file SimpleVector.h.
Referenced by SimpleVector< unsigned int >::add(), SimpleVector< unsigned int >::clear(), SimpleVector< unsigned int >::get_element(), SimpleVector< unsigned int >::nullify(), SimpleVector< unsigned int >::operator=(), SimpleVector< unsigned int >::operator[](), SimpleVector< unsigned int >::resize(), and SimpleVector< unsigned int >::SimpleVector().
The documentation for this class was generated from the following file:
local/SimpleVector.h