ExtLP: ExtSimplex Class Reference
ExtSimplex Class Reference
Detailed Description
Simplex Algorithm. // Performs simplex algorithm over the external memory // ////////////////////////////////////////////////////////.
Definition at line 23 of file ExtSimplex.h.
Public Member Functions
ExtSimplex (ExtLPDSSet &p_extDataSet)
Simple Initialization. Note that A matrix in the dataset is already filled from MPS file.
void debug_ak (PackedVector &ak)
void debug_b_inverse ()
void debug_base_col_indices ()
Debugging base column storage.
void debug_eta (EtaVector &eta)
void debug_objective_values ()
Debugging the Objective values retained.
void debug_rhs ()
void debug_rhs_values ()
Debugging the Rhs values retained.
void debug_w (PackedVector &w)
void debug_y (SimpleVector< double > y)
Debugging the y values retained.
unsigned int get_basis_dimension ()
Returns the dimension m from the mxm base matrix.
unsigned int get_expected_io_currently (ExtLPDSSet &extDataSet)
unsigned int get_expected_read_io_currently (ExtLPDSSet &extDataSet)
unsigned int get_expected_write_io_currently (ExtLPDSSet &extDataSet)
double get_objective_function_value ()
void init_simplex ()
Initializing/Loading simplex. involves standardization of matrix A and initialization of B Inverse. TODO - Need to find a proper base using pre-solve rather than Identity matrix every time.
void print_io_statistics (stxxl::stats_data diff_data, ExtLPDSSet &extDataSet, unsigned int expected_read_io, unsigned int expected_write_io, bool print_header=false, bool is_objective_reqd=false)
void print_solution ()
Performs the Cb*b.
void solve ()
solving the linear program
unsigned int update_simplex_iteration ()
Simplex iteration process.
Private Attributes
ExtLPDSSet & extDataSet
Storage spaced of Matrix Data structures A and BInverse.
SimpleVector< unsigned int > m_base_col_indices
unsigned int m_iteration_count
Count of number of iterations sofar.
SimpleVector< double > m_vct_obj
Objective Vector - Stores the Objective coefficients of base matrix.
SimpleVector< double > m_vct_rhs
RHS vector to be stored in memory for better functionality. This vector is updated at every iteration of simplex.
Constructor & Destructor Documentation
ExtSimplex::ExtSimplex (ExtLPDSSet & p_extDataSet) [inline]
Simple Initialization. Note that A matrix in the dataset is already filled from MPS file.
Definition at line 38 of file ExtSimplex.h.
Member Function Documentation
void ExtSimplex::debug_ak (PackedVector & ak) [inline]
Definition at line 367 of file ExtSimplex.h.
References PackedVector< ItemClass >::begin(), DEBUG, DEBUG_SIMPLE, PackedVector< ItemClass >::end(), PackedElement< ItemClass >::get_index(), PackedVector< ItemClass >::get_real_size(), and PackedElement< ItemClass >::get_value().
void ExtSimplex::debug_b_inverse () [inline]
Definition at line 423 of file ExtSimplex.h.
References ExtLPDSSet::A, PackedVector< ItemClass >::begin(), ExtLPDSSet::BInverse, DEBUG, DEBUG_SIMPLE, PackedVector< ItemClass >::end(), extDataSet, MatrixBInverseColAttr::get_a_col_index(), ExtMatrixBInverse::get_col_attr(), ExtMatrixA::get_col_attr(), MatrixAColAttr::get_col_name(), ExtMatrixBInverse::get_columns_count(), PackedElement< ItemClass >::get_index(), ExtMatrixA::get_row_attr(), MatrixARowAttr::get_row_name(), ExtMatrixBInverse::get_rows_count(), PackedElement< ItemClass >::get_value(), MAX_KEY_LEN, and ExtMatrixBInverse::store_column().
void ExtSimplex::debug_base_col_indices () [inline]
Debugging base column storage.
Definition at line 305 of file ExtSimplex.h.
References ExtLPDSSet::A, DEBUG, DEBUG_SIMPLE, extDataSet, ExtMatrixA::get_col_attr(), MatrixAColAttr::get_col_name(), SimpleVector< ItemClass >::get_size(), and m_base_col_indices.
void ExtSimplex::debug_eta (EtaVector & eta) [inline]
Definition at line 398 of file ExtSimplex.h.
References PackedVector< ItemClass >::begin(), DEBUG, DEBUG_SIMPLE, PackedVector< ItemClass >::end(), EtaVector::get_col_index(), EtaVector::get_col_vector(), PackedElement< ItemClass >::get_index(), PackedVector< ItemClass >::get_real_size(), and PackedElement< ItemClass >::get_value().
void ExtSimplex::debug_objective_values () [inline]
Debugging the Objective values retained.
Definition at line 326 of file ExtSimplex.h.
References DEBUG, DEBUG_SIMPLE, SimpleVector< ItemClass >::get_size(), and m_vct_obj.
void ExtSimplex::debug_rhs () [inline]
Definition at line 390 of file ExtSimplex.h.
References DEBUG, DEBUG_SIMPLE, SimpleVector< ItemClass >::get_size(), and m_vct_rhs.
void ExtSimplex::debug_rhs_values () [inline]
Debugging the Rhs values retained.
Definition at line 316 of file ExtSimplex.h.
References DEBUG, DEBUG_SIMPLE, SimpleVector< ItemClass >::get_size(), and m_vct_rhs.
void ExtSimplex::debug_w (PackedVector & w) [inline]
Definition at line 334 of file ExtSimplex.h.
References PackedVector< ItemClass >::begin(), DEBUG, DEBUG_SIMPLE, PackedVector< ItemClass >::end(), PackedElement< ItemClass >::get_index(), PackedVector< ItemClass >::get_real_size(), and PackedElement< ItemClass >::get_value().
void ExtSimplex::debug_y (SimpleVector< double > y) [inline]
Debugging the y values retained.
Definition at line 359 of file ExtSimplex.h.
References DEBUG, DEBUG_SIMPLE, and SimpleVector< ItemClass >::get_size().
unsigned int ExtSimplex::get_basis_dimension () [inline]
Returns the dimension m from the mxm base matrix.
Definition at line 91 of file ExtSimplex.h.
References SimpleVector< ItemClass >::get_size(), and m_base_col_indices.
Referenced by update_simplex_iteration().
unsigned int ExtSimplex::get_expected_io_currently (ExtLPDSSet & extDataSet) [inline]
Definition at line 94 of file ExtSimplex.h.
References ExtLPDSSet::A, ExtLPDSSet::BInverse, ExtMatrixBInverse::get_element_size(), ExtMatrixA::get_element_size(), ExtMatrixBInverse::get_overall_nnz(), ExtMatrixA::get_overall_nnz(), MATRIX_A_BLOCK_SIZE, and MATRIX_B_COL_BLOCK_SIZE.
unsigned int ExtSimplex::get_expected_read_io_currently (ExtLPDSSet & extDataSet) [inline]
Definition at line 99 of file ExtSimplex.h.
References ExtLPDSSet::A, ExtLPDSSet::BInverse, ExtMatrixBInverse::get_element_size(), ExtMatrixA::get_element_size(), ExtMatrixBInverse::get_overall_nnz(), ExtMatrixA::get_overall_nnz(), MATRIX_A_BLOCK_SIZE, and MATRIX_B_COL_BLOCK_SIZE.
Referenced by solve().
unsigned int ExtSimplex::get_expected_write_io_currently (ExtLPDSSet & extDataSet) [inline]
Definition at line 113 of file ExtSimplex.h.
References ExtLPDSSet::BInverse, ExtMatrixBInverse::get_element_size(), ExtMatrixBInverse::get_overall_nnz(), and MATRIX_B_COL_BLOCK_SIZE.
Referenced by solve().
double ExtSimplex::get_objective_function_value () [inline]
Definition at line 288 of file ExtSimplex.h.
References m_vct_obj, m_vct_rhs, REAL, and ExtVectorUtil::store_dot_product().
Referenced by print_io_statistics(), and print_solution().
void ExtSimplex::init_simplex () [inline]
Initializing/Loading simplex. involves standardization of matrix A and initialization of B Inverse. TODO - Need to find a proper base using pre-solve rather than Identity matrix every time.
Definition at line 49 of file ExtSimplex.h.
References ExtLPDSSet::A, ExtLPDSSet::BInverse, ExtMatrixBInverse::build_matrix_b_inverse(), extDataSet, ExtLPDSSet::get_objective_sense_bool(), m_base_col_indices, m_vct_obj, m_vct_rhs, ExtMatrixA::standardize_matrix(), ExtMatrixA::store_col_objective_values(), and ExtMatrixA::store_row_rhs_values().
Referenced by solve().
void ExtSimplex::print_io_statistics (stxxl::stats_data diff_data, ExtLPDSSet & extDataSet, unsigned int expected_read_io, unsigned int expected_write_io, bool print_header = false, bool is_objective_reqd = false) [inline]
Definition at line 252 of file ExtSimplex.h.
References ExtLPDSSet::BInverse, CONSOLE_PRINTLN, get_objective_function_value(), ExtMatrixBInverse::get_overall_density(), ExtMatrixBInverse::get_overall_nnz(), and m_iteration_count.
Referenced by solve().
void ExtSimplex::print_solution () [inline]
Performs the Cb*b.
Definition at line 294 of file ExtSimplex.h.
References CONSOLE_PRINTLN, get_objective_function_value(), and REAL.
Referenced by solve().
void ExtSimplex::solve () [inline]
solving the linear program
Definition at line 57 of file ExtSimplex.h.
References CONSOLE_PRINTLN, extDataSet, get_expected_read_io_currently(), get_expected_write_io_currently(), init_simplex(), m_iteration_count, print_io_statistics(), print_solution(), SIMPLEX_CJZJ_POSITIVE, SIMPLEX_CJZJ_UNINTIALIZED, SIMPLEX_INVALID_MIN_RATIO, and update_simplex_iteration().
Referenced by main().
unsigned int ExtSimplex::update_simplex_iteration () [inline]
Simplex iteration process.
Finding the Entering Variable - k Note: k index is with respect to Matrix A
Calculating w = < Cb x Binverse >
Getting column-k of Matrix A
Finding the Leaving Variable - r based on - min br/ykr. Note: r index is with respect to MatrixBInverse Finding yk
Finding r - leaving variable
Definition at line 119 of file ExtSimplex.h.
References ExtLPDSSet::A, ExtLPDSSet::BInverse, extDataSet, MatrixBInverseColAttr::get_a_col_index(), get_basis_dimension(), ExtMatrixBInverse::get_col_attr(), ExtMatrixA::get_col_attr(), ExtMatrixA::get_columns_count(), MatrixAColAttr::get_is_basic_col(), ExtLPDSSet::get_objective_sense_bool(), MatrixAColAttr::get_objective_value(), SimpleVector< ItemClass >::get_size(), INFINITY_VALUE, m_base_col_indices, m_iteration_count, m_vct_obj, m_vct_rhs, REAL, MatrixBInverseColAttr::set_a_col_index(), ExtMatrixBInverse::set_col_attr(), ExtMatrixA::set_col_attr(), MatrixAColAttr::set_is_basic_col(), SIMPLEX_CJZJ_NEGATIVE, SIMPLEX_CJZJ_POSITIVE, SIMPLEX_CJZJ_ZERO, SIMPLEX_INVALID_MIN_RATIO, ExtMatrixA::store_column(), ExtVectorUtil::store_dot_product(), ExtVectorUtil::update_basis_inverse(), and ExtVectorUtil::update_rhs().
Referenced by solve().
Member Data Documentation
ExtLPDSSet& ExtSimplex::extDataSet [private]
Storage spaced of Matrix Data structures A and BInverse.
Definition at line 26 of file ExtSimplex.h.
Referenced by debug_b_inverse(), debug_base_col_indices(), init_simplex(), solve(), and update_simplex_iteration().
SimpleVector<unsigned int> ExtSimplex::m_base_col_indices [private]
Definition at line 32 of file ExtSimplex.h.
Referenced by debug_base_col_indices(), get_basis_dimension(), init_simplex(), and update_simplex_iteration().
unsigned int ExtSimplex::m_iteration_count [private]
Count of number of iterations sofar.
Definition at line 34 of file ExtSimplex.h.
Referenced by print_io_statistics(), solve(), and update_simplex_iteration().
SimpleVector< double > ExtSimplex::m_vct_obj [private]
Objective Vector - Stores the Objective coefficients of base matrix.
Definition at line 31 of file ExtSimplex.h.
Referenced by debug_objective_values(), get_objective_function_value(), init_simplex(), and update_simplex_iteration().
SimpleVector< double > ExtSimplex::m_vct_rhs [private]
RHS vector to be stored in memory for better functionality. This vector is updated at every iteration of simplex.
Definition at line 29 of file ExtSimplex.h.
Referenced by debug_rhs(), debug_rhs_values(), get_objective_function_value(), init_simplex(), and update_simplex_iteration().
The documentation for this class was generated from the following file:
local/ExtSimplex.h