ExtLP: ExtNameMap Class Reference
ExtNameMap Class Reference
Detailed Description
Definition at line 15 of file ExtNameMap.h.
Public Member Functions
ExtNameMap (fixed_name_map &myMap)
bool contains (const std::string &key)
Check if the element exists.
void displayMap ()
void displayStorageStatus ()
unsigned int get (const std::string &key)
Get the element value Returns -1 if element does not exist.
void set (const std::string &key, unsigned int value)
Static Public Member Functions
static void test ()
Private Attributes
fixed_name_map & nameMap
Constructor & Destructor Documentation
ExtNameMap::ExtNameMap (fixed_name_map & myMap) [inline]
Definition at line 20 of file ExtNameMap.h.
Member Function Documentation
bool ExtNameMap::contains (const std::string & key) [inline]
Check if the element exists.
Definition at line 24 of file ExtNameMap.h.
References nameMap.
Referenced by ExtReadMPSUtil::readCols(), ExtReadMPSUtil::readRhs(), and ExtReadMPSUtil::readRows().
void ExtNameMap::displayMap () [inline]
Definition at line 47 of file ExtNameMap.h.
References CONSOLE_PRINTLN, and nameMap.
void ExtNameMap::displayStorageStatus () [inline]
Definition at line 42 of file ExtNameMap.h.
References CONSOLE_PRINTLN, and nameMap.
unsigned int ExtNameMap::get (const std::string & key) [inline]
Get the element value Returns -1 if element does not exist.
Definition at line 31 of file ExtNameMap.h.
References nameMap.
Referenced by ExtReadMPSUtil::readCols(), and ExtReadMPSUtil::readRhs().
void ExtNameMap::set (const std::string & key, unsigned int value) [inline]
Definition at line 37 of file ExtNameMap.h.
References nameMap.
Referenced by ExtReadMPSUtil::readCols(), ExtReadMPSUtil::readRows(), and Test::testExtNameMap().
static void ExtNameMap::test () [inline, static]
Inserting 1 million strings
Definition at line 57 of file ExtNameMap.h.
References CONSOLE_PRINTLN, and DEBUG.
Member Data Documentation
fixed_name_map& ExtNameMap::nameMap [private]
Definition at line 17 of file ExtNameMap.h.
Referenced by contains(), displayMap(), displayStorageStatus(), get(), and set().
The documentation for this class was generated from the following file:
local/ExtNameMap.h