ExtLP: ExtVectorUtil Class Reference
ExtVectorUtil Class Reference
Detailed Description
Util functions for Vector Arithmetic. Vector arithmetic is performed on Packed/Unpacked Vectors both from physical and external memory.
Definition at line 17 of file ExtVectorUtil.h.
Static Public Member Functions
static void append_scalar_product (double scalar_value, PackedVector &p_vct, SimpleVector< double > &p_result)
Scalar Product. Storing Result in Scattered Vector appending is very necessary while doing column-wise matrix multiplication.
static void sort_packed_vector_based_on_index (PackedVector &packed_vector)
Sorts given packed vector by first scattering and then compacting.
static void store_dot_product (PackedVector &p_vct1, PackedVector &p_vct2, double &p_dot_product)
Dot product of two vectors(one row and one col vector) < vct1.vct2 >. Both of the vectors are packed.
static void store_dot_product (SimpleVector< double > &p_vct1, SimpleVector< double > &p_vct2, double &p_dot_product)
Dot product of two vectors(one row and one col vector) < vct1.vct2 >. Both of the vectors are already scattered.
static void store_dot_product (SimpleVector< double > &p_vct1, PackedVector &p_vct2, double &p_dot_product)
Dot product of two vectors(one row and one col vector) < vct1.vct2 >. One of the vector is already scattered.
static void store_dot_product (PackedVector &p_vct1, ExtMatrixBInverse &p_BInverse, PackedVector &p_dot_product)
Packed Row Vector multiplied by Matrix.
static void store_dot_product (SimpleVector< double > &p_vct1, ExtMatrixBInverse &p_BInverse, PackedVector &p_dot_product)
Scattered Row Vector multiplied by Matrix.
static void store_dot_product (ExtMatrixBInverse &p_BInverse, PackedVector &p_vct, SimpleVector< double > &p_dot_product)
Matrix multiplied by Column Vector Used in calculating < BInverse x aj >, < BInverse x b >
static void store_scalar_product (double scalar_value, PackedVector &p_vct, PackedVector &p_result)
Scalar Product. Storing Result in packed vector.
static void store_sum (PackedVector &p_vct1, PackedVector &p_vct2, double lambda, PackedVector &p_vct_result)
Sum of vectors < vct1 + (lamda)vct2 > TODO - Check which vector can be better scattered.
static void store_sum (PackedVector &p_vct1, PackedVector &p_vct2, double lambda, SimpleVector< double > &p_vct_result)
Sum of vectors < vct1 + (lamda)vct2 > TODO - Check which vector can be better scattered.
static void update_basis_inverse (EtaVector &eta_vector, ExtMatrixBInverse &b_inverse)
Updating the basis inverse. Called at every iteration step of simplex.
static void update_rhs (EtaVector &eta_vector, SimpleVector< double > &rhs_vector)
Updating the basis inverse. Called at every iteration step of simplex TODO - Improve performance by using only the rhs_vector.
Static Private Member Functions
static double _get_scratch_pad_element (unsigned int index)
static void _resize_scratch_pad (unsigned int size)
Resizes the scratch pad to the parameter size.
static void _set_scratch_pad_element (unsigned int index, double value)
static void _validate_scratch_pad (unsigned int index)
Validate if the scratch pad can access the index.
static void _validate_scratch_pad ()
checks for the condition that scratch pad needs to be zero before any operation.
Static Private Attributes
static std::vector< double > m_scratch_pad
Scratch Pad for scattering.
Member Function Documentation
static double ExtVectorUtil::_get_scratch_pad_element (unsigned int index) [inline, static, private]
Definition at line 32 of file ExtVectorUtil.h.
References _validate_scratch_pad(), and m_scratch_pad.
Referenced by _validate_scratch_pad(), sort_packed_vector_based_on_index(), store_dot_product(), and store_sum().
static void ExtVectorUtil::_resize_scratch_pad (unsigned int size) [inline, static, private]
Resizes the scratch pad to the parameter size.
Definition at line 29 of file ExtVectorUtil.h.
References m_scratch_pad.
Referenced by _validate_scratch_pad().
static void ExtVectorUtil::_set_scratch_pad_element (unsigned int index, double value) [inline, static, private]
Definition at line 36 of file ExtVectorUtil.h.
References _validate_scratch_pad(), and m_scratch_pad.
Referenced by sort_packed_vector_based_on_index(), store_dot_product(), and store_sum().
static void ExtVectorUtil::_validate_scratch_pad (unsigned int index) [inline, static, private]
Validate if the scratch pad can access the index.
Definition at line 23 of file ExtVectorUtil.h.
References _resize_scratch_pad(), and m_scratch_pad.
static void ExtVectorUtil::_validate_scratch_pad () [inline, static, private]
checks for the condition that scratch pad needs to be zero before any operation.
Definition at line 41 of file ExtVectorUtil.h.
References _get_scratch_pad_element(), and m_scratch_pad.
Referenced by _get_scratch_pad_element(), and _set_scratch_pad_element().
static void ExtVectorUtil::append_scalar_product (double scalar_value, PackedVector & p_vct, SimpleVector< double > & p_result) [inline, static]
Scalar Product. Storing Result in Scattered Vector appending is very necessary while doing column-wise matrix multiplication.
Setting up result for storage
Definition at line 63 of file ExtVectorUtil.h.
References SimpleVector< ItemClass >::add(), PackedVector< ItemClass >::begin(), PackedVector< ItemClass >::end(), SimpleVector< ItemClass >::get_element(), PackedElement< ItemClass >::get_index(), PackedElement< ItemClass >::get_value(), and REAL.
Referenced by store_dot_product().
static void ExtVectorUtil::sort_packed_vector_based_on_index (PackedVector & packed_vector) [inline, static]
Sorts given packed vector by first scattering and then compacting.
Definition at line 267 of file ExtVectorUtil.h.
References _get_scratch_pad_element(), _set_scratch_pad_element(), PackedVector< ItemClass >::begin(), PackedVector< ItemClass >::end(), PackedVector< ItemClass >::get_real_size(), and REAL.
static void ExtVectorUtil::store_dot_product (PackedVector & p_vct1, PackedVector & p_vct2, double & p_dot_product) [inline, static]
Dot product of two vectors(one row and one col vector) < vct1.vct2 >. Both of the vectors are packed.
Definition at line 84 of file ExtVectorUtil.h.
References _get_scratch_pad_element(), _set_scratch_pad_element(), PackedVector< ItemClass >::begin(), PackedVector< ItemClass >::end(), PackedElement< ItemClass >::get_index(), PackedVector< ItemClass >::get_real_size(), PackedVector< ItemClass >::get_sparsity(), PackedElement< ItemClass >::get_value(), and REAL.
Referenced by ExtSimplex::get_objective_function_value(), store_dot_product(), and ExtSimplex::update_simplex_iteration().
static void ExtVectorUtil::store_dot_product (SimpleVector< double > & p_vct1, SimpleVector< double > & p_vct2, double & p_dot_product) [inline, static]
Dot product of two vectors(one row and one col vector) < vct1.vct2 >. Both of the vectors are already scattered.
Definition at line 126 of file ExtVectorUtil.h.
References SimpleVector< ItemClass >::get_size(), and REAL.
static void ExtVectorUtil::store_dot_product (SimpleVector< double > & p_vct1, PackedVector & p_vct2, double & p_dot_product) [inline, static]
Dot product of two vectors(one row and one col vector) < vct1.vct2 >. One of the vector is already scattered.
Definition at line 138 of file ExtVectorUtil.h.
References PackedVector< ItemClass >::begin(), PackedVector< ItemClass >::end(), PackedElement< ItemClass >::get_index(), PackedElement< ItemClass >::get_value(), and REAL.
static void ExtVectorUtil::store_dot_product (PackedVector & p_vct1, ExtMatrixBInverse & p_BInverse, PackedVector & p_dot_product) [inline, static]
Packed Row Vector multiplied by Matrix.
Definition at line 154 of file ExtVectorUtil.h.
References PackedVector< ItemClass >::add(), ExtMatrixBInverse::get_columns_count(), ExtMatrixBInverse::get_rows_count(), REAL, and store_dot_product().
static void ExtVectorUtil::store_dot_product (SimpleVector< double > & p_vct1, ExtMatrixBInverse & p_BInverse, PackedVector & p_dot_product) [inline, static]
Scattered Row Vector multiplied by Matrix.
Definition at line 164 of file ExtVectorUtil.h.
References PackedVector< ItemClass >::add(), ExtMatrixBInverse::get_columns_count(), ExtMatrixBInverse::get_rows_count(), REAL, ExtMatrixBInverse::store_column(), and store_dot_product().
static void ExtVectorUtil::store_dot_product (ExtMatrixBInverse & p_BInverse, PackedVector & p_vct, SimpleVector< double > & p_dot_product) [inline, static]
Matrix multiplied by Column Vector Used in calculating < BInverse x aj >, < BInverse x b >
Definition at line 176 of file ExtVectorUtil.h.
References append_scalar_product(), PackedVector< ItemClass >::begin(), PackedVector< ItemClass >::end(), ExtMatrixBInverse::get_rows_count(), REAL, and ExtMatrixBInverse::store_column().
static void ExtVectorUtil::store_scalar_product (double scalar_value, PackedVector & p_vct, PackedVector & p_result) [inline, static]
Scalar Product. Storing Result in packed vector.
Setting up result for storage
Definition at line 47 of file ExtVectorUtil.h.
References PackedVector< ItemClass >::add(), PackedVector< ItemClass >::begin(), PackedVector< ItemClass >::clear(), PackedVector< ItemClass >::end(), PackedElement< ItemClass >::get_index(), PackedVector< ItemClass >::get_real_size(), PackedElement< ItemClass >::get_value(), REAL, PackedVector< ItemClass >::resize(), and PackedElement< ItemClass >::set_value().
static void ExtVectorUtil::store_sum (PackedVector & p_vct1, PackedVector & p_vct2, double lambda, PackedVector & p_vct_result) [inline, static]
Sum of vectors < vct1 + (lamda)vct2 > TODO - Check which vector can be better scattered.
Definition at line 196 of file ExtVectorUtil.h.
References _get_scratch_pad_element(), _set_scratch_pad_element(), PackedVector< ItemClass >::add(), PackedVector< ItemClass >::begin(), PackedVector< ItemClass >::end(), PackedElement< ItemClass >::get_index(), PackedElement< ItemClass >::get_value(), and REAL.
Referenced by update_basis_inverse(), and update_rhs().
static void ExtVectorUtil::store_sum (PackedVector & p_vct1, PackedVector & p_vct2, double lambda, SimpleVector< double > & p_vct_result) [inline, static]
Sum of vectors < vct1 + (lamda)vct2 > TODO - Check which vector can be better scattered.
Definition at line 232 of file ExtVectorUtil.h.
References _get_scratch_pad_element(), _set_scratch_pad_element(), SimpleVector< ItemClass >::add(), PackedVector< ItemClass >::begin(), PackedVector< ItemClass >::end(), PackedElement< ItemClass >::get_index(), PackedElement< ItemClass >::get_value(), and REAL.
static void ExtVectorUtil::update_basis_inverse (EtaVector & eta_vector, ExtMatrixBInverse & b_inverse) [inline, static]
Updating the basis inverse. Called at every iteration step of simplex.
Definition at line 288 of file ExtVectorUtil.h.
References ExtMatrixBInverse::add_column(), ExtMatrixBInverse::clear_matrix_b_inverse(), MatrixBInverseColAttr::get_a_col_index(), ExtMatrixBInverse::get_col_attr(), EtaVector::get_col_index(), EtaVector::get_col_vector(), ExtMatrixBInverse::get_columns_count(), ExtMatrixBInverse::get_rows_count(), REAL, ExtMatrixBInverse::store_column(), store_sum(), and ExtMatrixBInverse::swap().
Referenced by ExtSimplex::update_simplex_iteration().
static void ExtVectorUtil::update_rhs (EtaVector & eta_vector, SimpleVector< double > & rhs_vector) [inline, static]
Updating the basis inverse. Called at every iteration step of simplex TODO - Improve performance by using only the rhs_vector.
Definition at line 316 of file ExtVectorUtil.h.
References EtaVector::get_col_index(), EtaVector::get_col_vector(), REAL, and store_sum().
Referenced by ExtSimplex::update_simplex_iteration().
Member Data Documentation
std::vector< double > ExtVectorUtil::m_scratch_pad [static, private]
Scratch Pad for scattering.
Definition at line 20 of file ExtVectorUtil.h.
Referenced by _get_scratch_pad_element(), _resize_scratch_pad(), _set_scratch_pad_element(), and _validate_scratch_pad().
The documentation for this class was generated from the following file:
local/ExtVectorUtil.h