ExtLP: PackedColVector Class Reference
PackedColVector Class Reference
Detailed Description
Definition at line 12 of file PackedColVector.h.
Public Types
typedef PackedVector::iterator iterator
Public Member Functions
PackedColVector (int defDim=0)
Initialization with input as the real_size of the column vector.
PackedColVector (PackedColVector &p_packed_col)
Copy constructor Highly uneccesary for assignment/initialization.
PackedVector & get_col_vector ()
Returns the reference to the Packed column.
double get_lower_bound () const
std::string get_name () const
double get_objective_value () const
@ Simple Getters + Setters {
double get_row_element (unsigned int row) const
}
double get_upper_bound () const
void set_col_vector (const std::vector< double > &p_vec)
Sets the col vector with complete initialization to p_vec.
void set_lower_bound (double p_low)
void set_name (std::string p_name)
void set_objective_value (double p_object)
void set_upper_bound (double p_up)
Private Attributes
double m_lower_bound
std::string m_name
double m_objective_value
double m_upper_bound
PackedVector m_vct_col
Member Typedef Documentation
typedef PackedVector::iterator PackedColVector::iterator
Definition at line 21 of file PackedColVector.h.
Constructor & Destructor Documentation
PackedColVector::PackedColVector (int defDim = 0) [inline, explicit]
Initialization with input as the real_size of the column vector.
Definition at line 23 of file PackedColVector.h.
PackedColVector::PackedColVector (PackedColVector & p_packed_col) [inline]
Copy constructor Highly uneccesary for assignment/initialization.
Definition at line 28 of file PackedColVector.h.
References DEBUG_WARNING.
Member Function Documentation
PackedVector& PackedColVector::get_col_vector () [inline]
Returns the reference to the Packed column.
Definition at line 46 of file PackedColVector.h.
References m_vct_col.
Referenced by ExtMatrixA::add_column().
double PackedColVector::get_lower_bound () const [inline]
Definition at line 39 of file PackedColVector.h.
References m_lower_bound.
std::string PackedColVector::get_name () const [inline]
Definition at line 42 of file PackedColVector.h.
References m_name.
Referenced by ExtMatrixA::add_column().
double PackedColVector::get_objective_value () const [inline]
@ Simple Getters + Setters {
Definition at line 33 of file PackedColVector.h.
References m_objective_value.
Referenced by ExtMatrixA::add_column().
double PackedColVector::get_row_element (unsigned int row) const [inline]
}
Definition at line 72 of file PackedColVector.h.
References PackedVector< ItemClass >::get(), and m_vct_col.
double PackedColVector::get_upper_bound () const [inline]
Definition at line 36 of file PackedColVector.h.
References m_upper_bound.
void PackedColVector::set_col_vector (const std::vector< double > & p_vec) [inline]
Sets the col vector with complete initialization to p_vec.
Definition at line 62 of file PackedColVector.h.
References PackedVector< ItemClass >::add(), PackedVector< ItemClass >::clear(), m_vct_col, and PackedVector< ItemClass >::resize().
void PackedColVector::set_lower_bound (double p_low) [inline]
Definition at line 58 of file PackedColVector.h.
References m_lower_bound.
void PackedColVector::set_name (std::string p_name) [inline]
Definition at line 55 of file PackedColVector.h.
References m_name.
void PackedColVector::set_objective_value (double p_object) [inline]
Definition at line 49 of file PackedColVector.h.
References m_objective_value.
Referenced by ExtReadMPSUtil::readCols().
void PackedColVector::set_upper_bound (double p_up) [inline]
Definition at line 52 of file PackedColVector.h.
References m_upper_bound.
Member Data Documentation
double PackedColVector::m_lower_bound [private]
Definition at line 15 of file PackedColVector.h.
Referenced by get_lower_bound(), and set_lower_bound().
std::string PackedColVector::m_name [private]
Definition at line 18 of file PackedColVector.h.
Referenced by get_name(), and set_name().
double PackedColVector::m_objective_value [private]
Definition at line 16 of file PackedColVector.h.
Referenced by get_objective_value(), and set_objective_value().
double PackedColVector::m_upper_bound [private]
Definition at line 14 of file PackedColVector.h.
Referenced by get_upper_bound(), and set_upper_bound().
PackedVector PackedColVector::m_vct_col [private]
Definition at line 17 of file PackedColVector.h.
Referenced by get_col_vector(), get_row_element(), and set_col_vector().
The documentation for this class was generated from the following file:
local/PackedColVector.h