ExtLP: MatrixAColAttr Class Reference
MatrixAColAttr Class Reference
Detailed Description
Stores limits for the start and end of the column in ExtMatrixA container The limits to the column is [start, end) start includes and end excludes Also includes the other necessary properties such as name and objective value.
Definition at line 20 of file ExtMatrixA.h.
Public Member Functions
MatrixAColAttr ()
MatrixAColAttr (unsigned int start, unsigned int end)
std::string get_col_name () const
unsigned int get_end () const
bool get_is_basic_col () const
bool get_is_slack_col () const
double get_objective_value () const
unsigned int get_start () const
void set_col_name (std::string col_name)
void set_end (unsigned int end)
void set_is_basic_col (bool is_basic_col)
void set_is_slack_col (bool is_slack_col)
void set_objective_value (double objective_value)
void set_start (unsigned int start)
Private Attributes
FixedString col_name
unsigned int end
bool is_basic_col
bool is_slack_col
double objective_value
unsigned int start
Constructor & Destructor Documentation
MatrixAColAttr::MatrixAColAttr () [inline]
Definition at line 28 of file ExtMatrixA.h.
MatrixAColAttr::MatrixAColAttr (unsigned int start, unsigned int end) [inline]
Definition at line 30 of file ExtMatrixA.h.
References end, and start.
Member Function Documentation
std::string MatrixAColAttr::get_col_name () const [inline]
Definition at line 61 of file ExtMatrixA.h.
References col_name.
Referenced by ExtSimplex::debug_b_inverse(), ExtSimplex::debug_base_col_indices(), Test::testExtMatrixA(), and Test::testMatrixBInverse().
unsigned int MatrixAColAttr::get_end () const [inline]
Definition at line 55 of file ExtMatrixA.h.
References end.
Referenced by ExtMatrixA::get_col_nnz(), and ExtMatrixA::store_column().
bool MatrixAColAttr::get_is_basic_col () const [inline]
Definition at line 67 of file ExtMatrixA.h.
References is_basic_col.
Referenced by ExtSimplex::update_simplex_iteration().
bool MatrixAColAttr::get_is_slack_col () const [inline]
Definition at line 64 of file ExtMatrixA.h.
References is_slack_col.
double MatrixAColAttr::get_objective_value () const [inline]
Definition at line 58 of file ExtMatrixA.h.
References objective_value.
Referenced by ExtMatrixA::store_column(), Test::testExtMatrixA(), and ExtSimplex::update_simplex_iteration().
unsigned int MatrixAColAttr::get_start () const [inline]
Definition at line 52 of file ExtMatrixA.h.
References start.
Referenced by ExtMatrixA::get_col_nnz(), and ExtMatrixA::store_column().
void MatrixAColAttr::set_col_name (std::string col_name) [inline]
Definition at line 43 of file ExtMatrixA.h.
Referenced by ExtMatrixA::_add_slack_column().
void MatrixAColAttr::set_end (unsigned int end) [inline]
Definition at line 37 of file ExtMatrixA.h.
References end.
void MatrixAColAttr::set_is_basic_col (bool is_basic_col) [inline]
Definition at line 49 of file ExtMatrixA.h.
References is_basic_col.
Referenced by ExtMatrixA::_add_slack_column(), and ExtSimplex::update_simplex_iteration().
void MatrixAColAttr::set_is_slack_col (bool is_slack_col) [inline]
Definition at line 46 of file ExtMatrixA.h.
References is_slack_col.
Referenced by ExtMatrixA::_add_slack_column().
void MatrixAColAttr::set_objective_value (double objective_value) [inline]
Definition at line 40 of file ExtMatrixA.h.
References objective_value.
Referenced by ExtMatrixA::_add_slack_column(), and ExtMatrixA::add_column().
void MatrixAColAttr::set_start (unsigned int start) [inline]
Definition at line 34 of file ExtMatrixA.h.
References start.
Member Data Documentation
FixedString MatrixAColAttr::col_name [private]
Definition at line 24 of file ExtMatrixA.h.
Referenced by get_col_name().
unsigned int MatrixAColAttr::end [private]
Definition at line 22 of file ExtMatrixA.h.
Referenced by get_end(), MatrixAColAttr(), and set_end().
bool MatrixAColAttr::is_basic_col [private]
Definition at line 26 of file ExtMatrixA.h.
Referenced by get_is_basic_col(), and set_is_basic_col().
bool MatrixAColAttr::is_slack_col [private]
Definition at line 25 of file ExtMatrixA.h.
Referenced by get_is_slack_col(), and set_is_slack_col().
double MatrixAColAttr::objective_value [private]
Definition at line 23 of file ExtMatrixA.h.
Referenced by get_objective_value(), and set_objective_value().
unsigned int MatrixAColAttr::start [private]
Definition at line 22 of file ExtMatrixA.h.
Referenced by get_start(), MatrixAColAttr(), and set_start().
The documentation for this class was generated from the following file:
local/ExtMatrixA.h