ExtLP: MatrixARowAttr Class Reference
MatrixARowAttr Class Reference
Detailed Description
Stores row related properties of ExtMatrixA container Also includes the other necessary properties such as name and rhs value.
Definition at line 74 of file ExtMatrixA.h.
Public Member Functions
double get_lhs_value () const
double get_rhs_value () const
std::string get_row_name () const
int get_row_type () const
std::string get_row_type_str () const
void set_lhs_value (double lhs_value)
void set_rhs_value (double rhs_value)
void set_row_name (std::string col_name)
void set_row_type (int row_type)
Private Attributes
double lhs_value
left and right hand side values for the constraint Range Constraint could contain both lhs and rhs values
double rhs_value
FixedString row_name
int row_type
Integer identifier for the row type 0 Equals; 1 greater than Equals; 2 Less than Equals 3 Less than; 4 Greater ; 5 Range.
Member Function Documentation
double MatrixARowAttr::get_lhs_value () const [inline]
Definition at line 112 of file ExtMatrixA.h.
References lhs_value.
double MatrixARowAttr::get_rhs_value () const [inline]
Definition at line 115 of file ExtMatrixA.h.
References rhs_value.
Referenced by Test::testExtMatrixA().
std::string MatrixARowAttr::get_row_name () const [inline]
Definition at line 97 of file ExtMatrixA.h.
References row_name.
Referenced by ExtMatrixA::_add_slack_column(), ExtSimplex::debug_b_inverse(), Test::testExtMatrixA(), and Test::testMatrixBInverse().
int MatrixARowAttr::get_row_type () const [inline]
Definition at line 100 of file ExtMatrixA.h.
References row_type.
Referenced by get_row_type_str(), and ExtMatrixA::standardize_matrix().
std::string MatrixARowAttr::get_row_type_str () const [inline]
Definition at line 103 of file ExtMatrixA.h.
References get_row_type().
Referenced by Test::testExtMatrixA().
void MatrixARowAttr::set_lhs_value (double lhs_value) [inline]
Definition at line 91 of file ExtMatrixA.h.
References lhs_value.
Referenced by ExtMatrixA::add_row().
void MatrixARowAttr::set_rhs_value (double rhs_value) [inline]
Definition at line 94 of file ExtMatrixA.h.
References rhs_value.
Referenced by ExtMatrixA::add_row(), and ExtReadMPSUtil::readRhs().
void MatrixARowAttr::set_row_name (std::string col_name) [inline]
Definition at line 85 of file ExtMatrixA.h.
References row_name.
Referenced by ExtMatrixA::add_row().
void MatrixARowAttr::set_row_type (int row_type) [inline]
Definition at line 88 of file ExtMatrixA.h.
References row_type.
Referenced by ExtMatrixA::add_row(), and ExtMatrixA::standardize_matrix().
Member Data Documentation
double MatrixARowAttr::lhs_value [private]
left and right hand side values for the constraint Range Constraint could contain both lhs and rhs values
Definition at line 83 of file ExtMatrixA.h.
Referenced by get_lhs_value(), and set_lhs_value().
double MatrixARowAttr::rhs_value [private]
Definition at line 83 of file ExtMatrixA.h.
Referenced by get_rhs_value(), and set_rhs_value().
FixedString MatrixARowAttr::row_name [private]
Definition at line 76 of file ExtMatrixA.h.
Referenced by get_row_name(), and set_row_name().
int MatrixARowAttr::row_type [private]
Integer identifier for the row type 0 Equals; 1 greater than Equals; 2 Less than Equals 3 Less than; 4 Greater ; 5 Range.
Definition at line 80 of file ExtMatrixA.h.
Referenced by get_row_type(), and set_row_type().
The documentation for this class was generated from the following file:
local/ExtMatrixA.h