ExtLP: PackedElement< ItemClass > Class Template Reference
PackedElement< ItemClass > Class Template Reference
Detailed Description
template<class ItemClass>
class PackedElement< ItemClass >
Struct needs to be accessed outside by the get() method Basic <index, value> pair to represent array/vector in packed form.
Basic <index, value> pair to represent array/vector in packed form. Struct needs to be accessed outside by the get() and set() methods only.
Definition at line 17 of file PackedVectorTemplate.h.
Public Member Functions
PackedElement ()
PackedElement (unsigned int index, ItemClass value)
PackedElement ()
PackedElement (unsigned int index, double value)
std::string debug_contents ()
Simple string with index and value.
unsigned int get_index () const
double get_value () const
unsigned int getIndex ()
ItemClass getValue ()
bool operator< (const PackedElement &other) const
For sorting based on index. Used in LinkedList for adding in sorting order.
bool operator== (const PackedElement &other) const
bool operator== (const PackedElement &other) const
void set_index (unsigned int index)
void set_value (double value)
void setIndex (unsigned int index)
void setValue (ItemClass value)
Private Attributes
unsigned int index
ItemClass value
double value
Constructor & Destructor Documentation
template<class ItemClass> PackedElement< ItemClass >::PackedElement () [inline]
Definition at line 22 of file PackedVectorTemplate.h.
template<class ItemClass> PackedElement< ItemClass >::PackedElement (unsigned int index, ItemClass value) [inline]
Definition at line 24 of file PackedVectorTemplate.h.
References PackedElement< ItemClass >::index, and PackedElement< ItemClass >::value.
template<class ItemClass> PackedElement< ItemClass >::PackedElement () [inline]
Definition at line 24 of file PackedVector.h.
template<class ItemClass> PackedElement< ItemClass >::PackedElement (unsigned int index, double value) [inline]
Definition at line 26 of file PackedVector.h.
References PackedElement< ItemClass >::index, and PackedElement< ItemClass >::value.
Member Function Documentation
template<class ItemClass> std::string PackedElement< ItemClass >::debug_contents () [inline]
Simple string with index and value.
Definition at line 51 of file PackedVector.h.
References PackedElement< ItemClass >::index, and PackedElement< ItemClass >::value.
template<class ItemClass> unsigned int PackedElement< ItemClass >::get_index () const [inline]
Definition at line 36 of file PackedVector.h.
References PackedElement< ItemClass >::index.
Referenced by EtaVector::_transform_for_b_inverse(), ExtPackedVector< ItemClass >::add(), ExtMatrixBInverse::add_column(), ExtVectorUtil::append_scalar_product(), ExtSimplex::debug_ak(), ExtSimplex::debug_b_inverse(), ExtSimplex::debug_eta(), ExtSimplex::debug_w(), ExtPackedVector< ItemClass >::get_absolute_item_value(), ExtFixedMatrix::get_column(), ExtPackedVector< ItemClass >::getAbsoluteItemValue(), ExtFixedMatrix::store_column(), ExtMatrixBInverse::store_column(), ExtMatrixA::store_column(), ExtVectorUtil::store_dot_product(), ExtMatrixBInverse::store_row(), ExtVectorUtil::store_scalar_product(), ExtVectorUtil::store_sum(), ExtVector::storeFromPackedVector(), Test::testExtMatrixA(), and Test::testMatrixBInverse().
template<class ItemClass> double PackedElement< ItemClass >::get_value () const [inline]
Definition at line 39 of file PackedVector.h.
References PackedElement< ItemClass >::value.
Referenced by EtaVector::_transform_for_b_inverse(), ExtPackedVector< ItemClass >::add(), ExtVectorUtil::append_scalar_product(), ExtSimplex::debug_ak(), ExtSimplex::debug_b_inverse(), ExtSimplex::debug_eta(), ExtSimplex::debug_w(), ExtPackedVector< ItemClass >::get_absolute_item_value(), ExtFixedMatrix::get_column(), ExtPackedVector< ItemClass >::getAbsoluteItemValue(), ExtFixedMatrix::store_column(), ExtMatrixBInverse::store_column(), ExtMatrixA::store_column(), ExtVectorUtil::store_dot_product(), ExtMatrixBInverse::store_row(), ExtVectorUtil::store_scalar_product(), ExtVectorUtil::store_sum(), ExtVector::storeFromPackedVector(), Test::testExtMatrixA(), and Test::testMatrixBInverse().
template<class ItemClass> unsigned int PackedElement< ItemClass >::getIndex () [inline]
Definition at line 34 of file PackedVectorTemplate.h.
References PackedElement< ItemClass >::index.
Referenced by PackedVector< ItemClass >::convertToUnPacked().
template<class ItemClass> ItemClass PackedElement< ItemClass >::getValue () [inline]
Definition at line 37 of file PackedVectorTemplate.h.
References PackedElement< ItemClass >::value.
Referenced by PackedVector< ItemClass >::convertToUnPacked().
template<class ItemClass> bool PackedElement< ItemClass >::operator< (const PackedElement< ItemClass > & other) const [inline]
For sorting based on index. Used in LinkedList for adding in sorting order.
Definition at line 47 of file PackedVector.h.
References PackedElement< ItemClass >::index.
template<class ItemClass> bool PackedElement< ItemClass >::operator== (const PackedElement< ItemClass > & other) const [inline]
Definition at line 40 of file PackedVectorTemplate.h.
References PackedElement< ItemClass >::index, and PackedElement< ItemClass >::value.
template<class ItemClass> bool PackedElement< ItemClass >::operator== (const PackedElement< ItemClass > & other) const [inline]
Definition at line 42 of file PackedVector.h.
References PackedElement< ItemClass >::index, and PackedElement< ItemClass >::value.
template<class ItemClass> void PackedElement< ItemClass >::set_index (unsigned int index) [inline]
Definition at line 30 of file PackedVector.h.
References PackedElement< ItemClass >::index.
Referenced by ExtPackedVector< ItemClass >::add(), PackedVector< ItemClass >::add(), and ExtMatrixBInverse::build_matrix_b_inverse().
template<class ItemClass> void PackedElement< ItemClass >::set_value (double value) [inline]
Definition at line 33 of file PackedVector.h.
References PackedElement< ItemClass >::value.
Referenced by EtaVector::_transform_for_b_inverse(), ExtPackedVector< ItemClass >::add(), PackedVector< ItemClass >::add(), ExtMatrixBInverse::build_matrix_b_inverse(), and ExtVectorUtil::store_scalar_product().
template<class ItemClass> void PackedElement< ItemClass >::setIndex (unsigned int index) [inline]
Definition at line 28 of file PackedVectorTemplate.h.
References PackedElement< ItemClass >::index.
Referenced by PackedVector< ItemClass >::add(), and PackedVector< ItemClass >::iterator::operator*().
template<class ItemClass> void PackedElement< ItemClass >::setValue (ItemClass value) [inline]
Definition at line 31 of file PackedVectorTemplate.h.
References PackedElement< ItemClass >::value.
Referenced by PackedVector< ItemClass >::add(), and PackedVector< ItemClass >::iterator::operator*().
Member Data Documentation
template<class ItemClass> unsigned int PackedElement< ItemClass >::index [private]
Definition at line 19 of file PackedVectorTemplate.h.
Referenced by PackedElement< ItemClass >::debug_contents(), PackedElement< ItemClass >::get_index(), PackedElement< ItemClass >::getIndex(), PackedElement< ItemClass >::operator<(), PackedElement< ItemClass >::operator==(), PackedElement< ItemClass >::PackedElement(), PackedElement< ItemClass >::set_index(), and PackedElement< ItemClass >::setIndex().
template<class ItemClass> ItemClass PackedElement< ItemClass >::value [private]
Definition at line 20 of file PackedVectorTemplate.h.
Referenced by PackedElement< ItemClass >::debug_contents(), PackedElement< ItemClass >::get_value(), PackedElement< ItemClass >::getValue(), PackedElement< ItemClass >::operator==(), PackedElement< ItemClass >::PackedElement(), PackedElement< ItemClass >::set_value(), and PackedElement< ItemClass >::setValue().
template<class ItemClass> double PackedElement< ItemClass >::value [private]
Definition at line 22 of file PackedVector.h.
The documentation for this class was generated from the following files:
local/deprecated/PackedVectorTemplate.h
local/PackedVector.h