ExtLP: ExtVectorPrototype Class Reference
ExtVectorPrototype Class Reference
Detailed Description
This data structure is efficient for the purpose of disk I/O The vector is in packed form if the sparsity is <= 50% and in full form if the sparsity > 50% This inturn reduces total number of I/Os
Definition at line 18 of file ExtVectorPrototype.h.
Public Member Functions
ExtVectorPrototype (int p_realSize=0)
Donot explicitly call this constructor unless very much necessary.
ExtVectorPrototype (PackedVectorPrototype &vctPacked)
Always use this constructor for storing packed vector into the disk.
void displayStorageStatus ()
void displayVector ()
double getAbsoluteIndexElement (unsigned int absoluteIndex)
unsigned int getDiskStorageCapacity ()
float getSparsity ()
Get the sparsity of the vector.
bool isPacked () const
int size () const
void storePackPackedVector (PackedVectorPrototype &vctPacked)
Externally store disk based vector into memory.
Private Types
typedef
stxxl::VECTOR_GENERATOR
< double, 4, 1, 4 *1024 >
::result real_vector
Private Attributes
bool isVctPacked
unsigned int nnz
unsigned int realSize
real_vector vctDisk
Member Typedef Documentation
typedef stxxl::VECTOR_GENERATOR< double , 4, 1, 4*1024>::result ExtVectorPrototype::real_vector [private]
Temporarily using the existing Disk Vector from stxxl Better performance might be achieved through our own Blocking structure. -- TO DO --
Definition at line 25 of file ExtVectorPrototype.h.
Constructor & Destructor Documentation
ExtVectorPrototype::ExtVectorPrototype (int p_realSize = 0) [inline]
Donot explicitly call this constructor unless very much necessary.
Definition at line 33 of file ExtVectorPrototype.h.
References nnz, and realSize.
ExtVectorPrototype::ExtVectorPrototype (PackedVectorPrototype & vctPacked) [inline]
Always use this constructor for storing packed vector into the disk.
Definition at line 39 of file ExtVectorPrototype.h.
References PackedVectorPrototype::convertToPacked(), PackedVectorPrototype::convertToUnPacked(), PackedVectorPrototype::get(), PackedVectorPrototype::getPackedSize(), PackedVectorPrototype::getSparsity(), PackedVectorPrototype::getUnPackedSize(), PackedElementPrototype::index, nnz, REAL, realSize, PackedVectorPrototype::size(), PackedElementPrototype::value, and vctDisk.
Member Function Documentation
void ExtVectorPrototype::displayStorageStatus () [inline]
Definition at line 147 of file ExtVectorPrototype.h.
void ExtVectorPrototype::displayVector () [inline]
Definition at line 120 of file ExtVectorPrototype.h.
References CONSOLE_PRINTLN, getSparsity(), isPacked(), nnz, realSize, size(), and vctDisk.
double ExtVectorPrototype::getAbsoluteIndexElement (unsigned int absoluteIndex) [inline]
Definition at line 66 of file ExtVectorPrototype.h.
References isPacked(), nnz, REAL, and vctDisk.
unsigned int ExtVectorPrototype::getDiskStorageCapacity () [inline]
Definition at line 90 of file ExtVectorPrototype.h.
References vctDisk.
float ExtVectorPrototype::getSparsity () [inline]
Get the sparsity of the vector.
Definition at line 115 of file ExtVectorPrototype.h.
References nnz, and realSize.
Referenced by displayVector().
bool ExtVectorPrototype::isPacked () const [inline]
Definition at line 93 of file ExtVectorPrototype.h.
References vctDisk.
Referenced by displayVector(), getAbsoluteIndexElement(), size(), and storePackPackedVector().
int ExtVectorPrototype::size () const [inline]
Definition at line 86 of file ExtVectorPrototype.h.
References isPacked(), nnz, and vctDisk.
Referenced by displayVector().
void ExtVectorPrototype::storePackPackedVector (PackedVectorPrototype & vctPacked) [inline]
Externally store disk based vector into memory.
Definition at line 98 of file ExtVectorPrototype.h.
References PackedVectorPrototype::add(), isPacked(), nnz, realSize, and vctDisk.
Member Data Documentation
bool ExtVectorPrototype::isVctPacked [private]
Definition at line 29 of file ExtVectorPrototype.h.
unsigned int ExtVectorPrototype::nnz [private]
Definition at line 27 of file ExtVectorPrototype.h.
Referenced by displayVector(), ExtVectorPrototype(), getAbsoluteIndexElement(), getSparsity(), size(), and storePackPackedVector().
unsigned int ExtVectorPrototype::realSize [private]
Definition at line 28 of file ExtVectorPrototype.h.
Referenced by displayVector(), ExtVectorPrototype(), getSparsity(), and storePackPackedVector().
real_vector ExtVectorPrototype::vctDisk [private]
Definition at line 26 of file ExtVectorPrototype.h.
Referenced by displayVector(), ExtVectorPrototype(), getAbsoluteIndexElement(), getDiskStorageCapacity(), isPacked(), size(), and storePackPackedVector().
The documentation for this class was generated from the following file:
local/deprecated/ExtVectorPrototype.h