ExtLP: EtaVector Class Reference
EtaVector Class Reference
Detailed Description
Eta Vector is an simple representation of elementary matrix. The non-identity column along with column_index better represents the elementary matrix.
Definition at line 15 of file EtaVector.h.
Public Member Functions
EtaVector (unsigned int col_index, PackedVector &y)
Simple Initialization with PackedVector.
EtaVector (unsigned int col_index, SimpleVector< double > &y)
Simple Initialization with SimpleVector.
unsigned int get_col_index ()
Returns the index of the non identity column.
PackedVector & get_col_vector ()
Returns the reference to the non identity column of Elementary Matrix.
Private Member Functions
void _transform_for_b_inverse ()
Performs the required transformations for generating Elementary matrix used to update B-Inverse and Rhs.
Private Attributes
unsigned int m_col_r_index
Non identity column index in elementary matrix. Generally the leaving variable index from the basis matrix.
PackedVector m_vct_col
Constructor & Destructor Documentation
EtaVector::EtaVector (unsigned int col_index, PackedVector & y) [inline]
Simple Initialization with PackedVector.
Definition at line 51 of file EtaVector.h.
References _transform_for_b_inverse().
EtaVector::EtaVector (unsigned int col_index, SimpleVector< double > & y) [inline]
Simple Initialization with SimpleVector.
Definition at line 55 of file EtaVector.h.
References _transform_for_b_inverse().
Member Function Documentation
void EtaVector::_transform_for_b_inverse () [inline, private]
Performs the required transformations for generating Elementary matrix used to update B-Inverse and Rhs.
Definition at line 24 of file EtaVector.h.
References PackedVector< ItemClass >::begin(), PackedVector< ItemClass >::end(), PackedElement< ItemClass >::get_index(), PackedElement< ItemClass >::get_value(), m_col_r_index, m_vct_col, REAL, and PackedElement< ItemClass >::set_value().
Referenced by EtaVector().
unsigned int EtaVector::get_col_index () [inline]
Returns the index of the non identity column.
Definition at line 63 of file EtaVector.h.
References m_col_r_index.
Referenced by ExtSimplex::debug_eta(), ExtVectorUtil::update_basis_inverse(), and ExtVectorUtil::update_rhs().
PackedVector& EtaVector::get_col_vector () [inline]
Returns the reference to the non identity column of Elementary Matrix.
Definition at line 59 of file EtaVector.h.
References m_vct_col.
Referenced by ExtSimplex::debug_eta(), ExtVectorUtil::update_basis_inverse(), and ExtVectorUtil::update_rhs().
Member Data Documentation
unsigned int EtaVector::m_col_r_index [private]
Non identity column index in elementary matrix. Generally the leaving variable index from the basis matrix.
Definition at line 19 of file EtaVector.h.
Referenced by _transform_for_b_inverse(), and get_col_index().
PackedVector EtaVector::m_vct_col [private]
Definition at line 20 of file EtaVector.h.
Referenced by _transform_for_b_inverse(), and get_col_vector().
The documentation for this class was generated from the following file:
local/EtaVector.h