ExtLP: MatrixBInverseColAttr Class Reference
MatrixBInverseColAttr Class Reference
Detailed Description
Stores limits for the start and end of the column in ExtMatrixBInverse container The limits to the column is [start, end) start includes and end excludes Also includes the other necessary properties such as col_index for getting column details.
Definition at line 16 of file ExtMatrixBInverse.h.
Public Member Functions
MatrixBInverseColAttr ()
MatrixBInverseColAttr (unsigned int start, unsigned int end)
unsigned int get_a_col_index ()
Column index with respect to MatrixA container for fetching necessary details of this column such as name.
unsigned int get_end ()
unsigned int get_start ()
void set_a_col_index (unsigned int col_index)
void set_end (unsigned int end)
void set_start (unsigned int start)
Private Attributes
unsigned int a_col_index
unsigned int end
unsigned int start
Constructor & Destructor Documentation
MatrixBInverseColAttr::MatrixBInverseColAttr () [inline]
Definition at line 21 of file ExtMatrixBInverse.h.
MatrixBInverseColAttr::MatrixBInverseColAttr (unsigned int start, unsigned int end) [inline]
Definition at line 23 of file ExtMatrixBInverse.h.
References end, and start.
Member Function Documentation
unsigned int MatrixBInverseColAttr::get_a_col_index () [inline]
Column index with respect to MatrixA container for fetching necessary details of this column such as name.
Definition at line 44 of file ExtMatrixBInverse.h.
References a_col_index.
Referenced by ExtSimplex::debug_b_inverse(), Test::testMatrixBInverse(), ExtVectorUtil::update_basis_inverse(), and ExtSimplex::update_simplex_iteration().
unsigned int MatrixBInverseColAttr::get_end () [inline]
Definition at line 39 of file ExtMatrixBInverse.h.
References end.
Referenced by ExtMatrixBInverse::add_column(), ExtMatrixBInverse::get_col_nnz(), and ExtMatrixBInverse::store_column().
unsigned int MatrixBInverseColAttr::get_start () [inline]
Definition at line 36 of file ExtMatrixBInverse.h.
References start.
Referenced by ExtMatrixBInverse::get_col_nnz(), and ExtMatrixBInverse::store_column().
void MatrixBInverseColAttr::set_a_col_index (unsigned int col_index) [inline]
Definition at line 33 of file ExtMatrixBInverse.h.
References a_col_index.
Referenced by ExtMatrixBInverse::add_column(), and ExtSimplex::update_simplex_iteration().
void MatrixBInverseColAttr::set_end (unsigned int end) [inline]
Definition at line 30 of file ExtMatrixBInverse.h.
References end.
void MatrixBInverseColAttr::set_start (unsigned int start) [inline]
Definition at line 27 of file ExtMatrixBInverse.h.
References start.
Member Data Documentation
unsigned int MatrixBInverseColAttr::a_col_index [private]
Definition at line 19 of file ExtMatrixBInverse.h.
Referenced by get_a_col_index(), and set_a_col_index().
unsigned int MatrixBInverseColAttr::end [private]
Definition at line 18 of file ExtMatrixBInverse.h.
Referenced by get_end(), MatrixBInverseColAttr(), and set_end().
unsigned int MatrixBInverseColAttr::start [private]
Definition at line 18 of file ExtMatrixBInverse.h.
Referenced by get_start(), MatrixBInverseColAttr(), and set_start().
The documentation for this class was generated from the following file:
local/ExtMatrixBInverse.h