ExtLP: vector_bufreader< VectorIterator > Class Template Reference
vector_bufreader< VectorIterator > Class Template Reference
vector
Detailed Description
template<typename VectorIterator>
class vector_bufreader< VectorIterator >
Buffered sequential reader from a vector using overlapped I/O.
This buffered reader can be used to read a large sequential region of a vector using overlapped I/O. The object is created from an iterator range, which can then be read to using operator<<(), or with operator*() and operator++().
The interface also fulfills all requirements of a stream. Actually most of the code is identical to stream::vector_iterator2stream.
Note that this buffered reader is inefficient for reading small ranges. This is intentional, as one can just use operator[] on the vector for that.
See Efficient Sequential Reading and Writing to Vectors
Definition at line 1667 of file ExtStxxlVector.h.
Public Types
typedef
vector_iterator::bids_container_iterator bids_container_iterator
block identifier iterator of the vector
typedef vector_iterator::block_type block_type
block type used in the vector
typedef stxxl::buf_istream
< block_type,
bids_container_iterator > buf_istream_type
construct output buffered stream used for overlapped reading
typedef
vector_bufreader_iterator
< vector_bufreader > bufreader_iterator
construct an iterator for vector_bufreader (for C++11 range-based for loop)
typedef vector_iterator::value_type value_type
value type of the output vector
typedef VectorIterator vector_iterator
template parameter: the vector iterator type
typedef
vector_iterator::vector_type vector_type
type of the input vector
Public Member Functions
vector_bufreader (vector_iterator begin, vector_iterator end, stxxl::unsigned_type nbuffers=0)
Create overlapped reader for the given iterator range.
vector_bufreader (const vector_type &vec, stxxl::unsigned_type nbuffers=0)
Create overlapped reader for the whole vector's content.
~vector_bufreader ()
Finish reading and free buffered reader.
bufreader_iterator begin ()
Return vector_bufreader_iterator for C++11 range-based for loop.
bool empty () const
Returns true once the whole range has been read.
bufreader_iterator end ()
Return vector_bufreader_iterator for C++11 range-based for loop.
const value_type & operator* () const
Return constant reference to current item.
vector_bufreader & operator++ ()
Advance to next item (asserts if !empty()).
const value_type * operator-> () const
Return constant pointer to current item.
vector_bufreader & operator>> (value_type &v)
Read current item into variable and advance to next one.
void rewind ()
Rewind stream back to begin. Note that this recreates the buffered reader and is thus not cheap.
size_t size () const
Return remaining size.
Protected Attributes
vector_iterator m_begin
iterator to the beginning of the range.
buf_istream_type * m_bufin
buffered input stream used to overlapped I/O.
vector_iterator m_end
iterator to the end of the range.
vector_iterator m_iter
internal "current" iterator into the vector.
stxxl::unsigned_type m_nbuffers
number of blocks to use as buffers.
Member Typedef Documentation
template<typename VectorIterator > typedef vector_iterator::bids_container_iterator vector_bufreader< VectorIterator >::bids_container_iterator
block identifier iterator of the vector
Definition at line 1682 of file ExtStxxlVector.h.
template<typename VectorIterator > typedef vector_iterator::block_type vector_bufreader< VectorIterator >::block_type
block type used in the vector
Definition at line 1676 of file ExtStxxlVector.h.
template<typename VectorIterator > typedef stxxl::buf_istream<block_type, bids_container_iterator> vector_bufreader< VectorIterator >::buf_istream_type
construct output buffered stream used for overlapped reading
Definition at line 1685 of file ExtStxxlVector.h.
template<typename VectorIterator > typedef vector_bufreader_iterator<vector_bufreader> vector_bufreader< VectorIterator >::bufreader_iterator
construct an iterator for vector_bufreader (for C++11 range-based for loop)
Definition at line 1688 of file ExtStxxlVector.h.
template<typename VectorIterator > typedef vector_iterator::value_type vector_bufreader< VectorIterator >::value_type
value type of the output vector
Definition at line 1673 of file ExtStxxlVector.h.
template<typename VectorIterator > typedef VectorIterator vector_bufreader< VectorIterator >::vector_iterator
template parameter: the vector iterator type
Definition at line 1670 of file ExtStxxlVector.h.
template<typename VectorIterator > typedef vector_iterator::vector_type vector_bufreader< VectorIterator >::vector_type
type of the input vector
Definition at line 1679 of file ExtStxxlVector.h.
Constructor & Destructor Documentation
template<typename VectorIterator > vector_bufreader< VectorIterator >::vector_bufreader (vector_iterator begin, vector_iterator end, stxxl::unsigned_type nbuffers = 0) [inline]
Create overlapped reader for the given iterator range.
Parameters:
begin iterator to position were to start reading in vector
end iterator to position were to end reading in vector
nbuffers number of buffers used for overlapped I/O (>= 2*D recommended)
Definition at line 1714 of file ExtStxxlVector.h.
References vector_bufreader< VectorIterator >::m_begin, vector_bufreader< VectorIterator >::m_nbuffers, and vector_bufreader< VectorIterator >::rewind().
template<typename VectorIterator > vector_bufreader< VectorIterator >::vector_bufreader (const vector_type & vec, stxxl::unsigned_type nbuffers = 0) [inline]
Create overlapped reader for the whole vector's content.
Parameters:
vec vector to read
nbuffers number of buffers used for overlapped I/O (>= 2*D recommended)
Definition at line 1729 of file ExtStxxlVector.h.
References vector_bufreader< VectorIterator >::m_begin, vector_bufreader< VectorIterator >::m_nbuffers, and vector_bufreader< VectorIterator >::rewind().
template<typename VectorIterator > vector_bufreader< VectorIterator >::~vector_bufreader () [inline]
Finish reading and free buffered reader.
Definition at line 1763 of file ExtStxxlVector.h.
References vector_bufreader< VectorIterator >::m_bufin.
Member Function Documentation
template<typename VectorIterator > bufreader_iterator vector_bufreader< VectorIterator >::begin () [inline]
Return vector_bufreader_iterator for C++11 range-based for loop.
Definition at line 1811 of file ExtStxxlVector.h.
References vector_bufreader< VectorIterator >::m_begin.
template<typename VectorIterator > bool vector_bufreader< VectorIterator >::empty () const [inline]
Returns true once the whole range has been read.
Definition at line 1806 of file ExtStxxlVector.h.
References vector_bufreader< VectorIterator >::m_end, and vector_bufreader< VectorIterator >::m_iter.
Referenced by vector_bufreader< VectorIterator >::operator++(), and vector_bufreader< VectorIterator >::rewind().
template<typename VectorIterator > bufreader_iterator vector_bufreader< VectorIterator >::end () [inline]
Return vector_bufreader_iterator for C++11 range-based for loop.
Definition at line 1816 of file ExtStxxlVector.h.
References vector_bufreader< VectorIterator >::m_end.
template<typename VectorIterator > const value_type& vector_bufreader< VectorIterator >::operator* () const [inline]
Return constant reference to current item.
Definition at line 1768 of file ExtStxxlVector.h.
Referenced by vector_bufreader< VectorIterator >::operator>>().
template<typename VectorIterator > vector_bufreader& vector_bufreader< VectorIterator >::operator++ () [inline]
Advance to next item (asserts if !empty()).
Definition at line 1778 of file ExtStxxlVector.h.
References vector_bufreader< VectorIterator >::empty(), vector_bufreader< VectorIterator >::m_bufin, and vector_bufreader< VectorIterator >::m_iter.
Referenced by vector_bufreader< VectorIterator >::operator>>().
template<typename VectorIterator > const value_type* vector_bufreader< VectorIterator >::operator-> () const [inline]
Return constant pointer to current item.
Definition at line 1773 of file ExtStxxlVector.h.
template<typename VectorIterator > vector_bufreader& vector_bufreader< VectorIterator >::operator>> (value_type & v) [inline]
Read current item into variable and advance to next one.
Definition at line 1792 of file ExtStxxlVector.h.
References vector_bufreader< VectorIterator >::operator*(), and vector_bufreader< VectorIterator >::operator++().
template<typename VectorIterator > void vector_bufreader< VectorIterator >::rewind () [inline]
Rewind stream back to begin. Note that this recreates the buffered reader and is thus not cheap.
Definition at line 1743 of file ExtStxxlVector.h.
References vector_bufreader< VectorIterator >::empty(), vector_bufreader< VectorIterator >::m_begin, vector_bufreader< VectorIterator >::m_bufin, vector_bufreader< VectorIterator >::m_end, vector_bufreader< VectorIterator >::m_iter, and vector_bufreader< VectorIterator >::m_nbuffers.
Referenced by vector_bufreader< VectorIterator >::vector_bufreader().
template<typename VectorIterator > size_t vector_bufreader< VectorIterator >::size () const [inline]
Return remaining size.
Definition at line 1800 of file ExtStxxlVector.h.
References vector_bufreader< VectorIterator >::m_begin, vector_bufreader< VectorIterator >::m_end, and vector_bufreader< VectorIterator >::m_iter.
Member Data Documentation
template<typename VectorIterator > vector_iterator vector_bufreader< VectorIterator >::m_begin [protected]
iterator to the beginning of the range.
Definition at line 1692 of file ExtStxxlVector.h.
Referenced by vector_bufreader< VectorIterator >::begin(), vector_bufreader< VectorIterator >::rewind(), vector_bufreader< VectorIterator >::size(), and vector_bufreader< VectorIterator >::vector_bufreader().
template<typename VectorIterator > buf_istream_type* vector_bufreader< VectorIterator >::m_bufin [protected]
buffered input stream used to overlapped I/O.
Definition at line 1701 of file ExtStxxlVector.h.
Referenced by vector_bufreader< VectorIterator >::operator++(), vector_bufreader< VectorIterator >::rewind(), and vector_bufreader< VectorIterator >::~vector_bufreader().
template<typename VectorIterator > vector_iterator vector_bufreader< VectorIterator >::m_end [protected]
iterator to the end of the range.
Definition at line 1698 of file ExtStxxlVector.h.
Referenced by vector_bufreader< VectorIterator >::empty(), vector_bufreader< VectorIterator >::end(), vector_bufreader< VectorIterator >::rewind(), and vector_bufreader< VectorIterator >::size().
template<typename VectorIterator > vector_iterator vector_bufreader< VectorIterator >::m_iter [protected]
internal "current" iterator into the vector.
Definition at line 1695 of file ExtStxxlVector.h.
Referenced by vector_bufreader< VectorIterator >::empty(), vector_bufreader< VectorIterator >::operator++(), vector_bufreader< VectorIterator >::rewind(), and vector_bufreader< VectorIterator >::size().
template<typename VectorIterator > stxxl::unsigned_type vector_bufreader< VectorIterator >::m_nbuffers [protected]
number of blocks to use as buffers.
Definition at line 1704 of file ExtStxxlVector.h.
Referenced by vector_bufreader< VectorIterator >::rewind(), and vector_bufreader< VectorIterator >::vector_bufreader().
The documentation for this class was generated from the following file:
local/deprecated/ExtStxxlVector.h