ExtLP: double_blocked_index< size_type, modulo2, modulo1 > Class Template Reference
double_blocked_index< size_type, modulo2, modulo1 > Class Template Reference
vector
Detailed Description
template<typename size_type, size_type modulo2, size_type modulo1>
class double_blocked_index< size_type, modulo2, modulo1 >
Definition at line 58 of file ExtStxxlVector.h.
Public Member Functions
double_blocked_index ()
double_blocked_index (size_type pos)
double_blocked_index (stxxl::unsigned_type block2, stxxl::unsigned_type block1, stxxl::unsigned_type offset)
const stxxl::unsigned_type & get_block1 () const
const stxxl::unsigned_type & get_block2 () const
const stxxl::unsigned_type & get_offset () const
size_type get_pos () const
bool operator!= (const double_blocked_index &dbi2) const
double_blocked_index operator+ (size_type addend) const
double_blocked_index & operator++ ()
double_blocked_index operator++ (int)
double_blocked_index & operator+= (size_type addend)
double_blocked_index operator- (size_type addend) const
size_type operator- (const double_blocked_index &dbi2) const
double_blocked_index & operator-- ()
double_blocked_index operator-- (int)
double_blocked_index & operator-= (size_type subtrahend)
bool operator< (const double_blocked_index &dbi2) const
bool operator<= (const double_blocked_index &dbi2) const
double_blocked_index & operator= (size_type pos)
bool operator== (const double_blocked_index &dbi2) const
bool operator> (const double_blocked_index &dbi2) const
bool operator>= (const double_blocked_index &dbi2) const
double_blocked_index & operator>>= (size_type shift)
Private Member Functions
void set (size_type pos)
Private Attributes
stxxl::unsigned_type block1
stxxl::unsigned_type block2
stxxl::unsigned_type offset
size_type pos
Static Private Attributes
static const size_type modulo12 = modulo1 * modulo2
Constructor & Destructor Documentation
template<typename size_type , size_type modulo2, size_type modulo1> double_blocked_index< size_type, modulo2, modulo1 >::double_blocked_index () [inline]
Definition at line 78 of file ExtStxxlVector.h.
Referenced by double_blocked_index< size_type, modulo2, modulo1 >::operator+(), and double_blocked_index< size_type, modulo2, modulo1 >::operator-().
template<typename size_type , size_type modulo2, size_type modulo1> double_blocked_index< size_type, modulo2, modulo1 >::double_blocked_index (size_type pos) [inline]
Definition at line 81 of file ExtStxxlVector.h.
References double_blocked_index< size_type, modulo2, modulo1 >::pos.
template<typename size_type , size_type modulo2, size_type modulo1> double_blocked_index< size_type, modulo2, modulo1 >::double_blocked_index (stxxl::unsigned_type block2, stxxl::unsigned_type block1, stxxl::unsigned_type offset) [inline]
Definition at line 84 of file ExtStxxlVector.h.
References double_blocked_index< size_type, modulo2, modulo1 >::block1, double_blocked_index< size_type, modulo2, modulo1 >::block2, double_blocked_index< size_type, modulo2, modulo1 >::modulo12, double_blocked_index< size_type, modulo2, modulo1 >::offset, and double_blocked_index< size_type, modulo2, modulo1 >::pos.
Member Function Documentation
template<typename size_type , size_type modulo2, size_type modulo1> const stxxl::unsigned_type& double_blocked_index< size_type, modulo2, modulo1 >::get_block1 () const [inline]
Definition at line 196 of file ExtStxxlVector.h.
References double_blocked_index< size_type, modulo2, modulo1 >::block1.
Referenced by vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::bid(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::const_element(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::element().
template<typename size_type , size_type modulo2, size_type modulo1> const stxxl::unsigned_type& double_blocked_index< size_type, modulo2, modulo1 >::get_block2 () const [inline]
Definition at line 193 of file ExtStxxlVector.h.
References double_blocked_index< size_type, modulo2, modulo1 >::block2.
Referenced by vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::bid(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::block_externally_updated(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::const_element(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::element(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::is_page_cached().
template<typename size_type , size_type modulo2, size_type modulo1> const stxxl::unsigned_type& double_blocked_index< size_type, modulo2, modulo1 >::get_offset () const [inline]
Definition at line 199 of file ExtStxxlVector.h.
References double_blocked_index< size_type, modulo2, modulo1 >::offset.
Referenced by vector_iterator< ValueType, AllocStr, SizeType, DiffType, BlockSize, PagerType, PageSize >::block_offset(), const_vector_iterator< ValueType, AllocStr, SizeType, DiffType, BlockSize, PagerType, PageSize >::block_offset(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::const_element(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::element().
template<typename size_type , size_type modulo2, size_type modulo1> size_type double_blocked_index< size_type, modulo2, modulo1 >::get_pos () const [inline]
Definition at line 190 of file ExtStxxlVector.h.
References double_blocked_index< size_type, modulo2, modulo1 >::pos.
Referenced by vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::element(), vector_iterator< ValueType, AllocStr, SizeType, DiffType, BlockSize, PagerType, PageSize >::operator+(), const_vector_iterator< ValueType, AllocStr, SizeType, DiffType, BlockSize, PagerType, PageSize >::operator+(), vector_iterator< ValueType, AllocStr, SizeType, DiffType, BlockSize, PagerType, PageSize >::operator-(), const_vector_iterator< ValueType, AllocStr, SizeType, DiffType, BlockSize, PagerType, PageSize >::operator-(), vector_iterator< ValueType, AllocStr, SizeType, DiffType, BlockSize, PagerType, PageSize >::operator[](), and const_vector_iterator< ValueType, AllocStr, SizeType, DiffType, BlockSize, PagerType, PageSize >::operator[]().
template<typename size_type , size_type modulo2, size_type modulo1> bool double_blocked_index< size_type, modulo2, modulo1 >::operator!= (const double_blocked_index< size_type, modulo2, modulo1 > & dbi2) const [inline]
Definition at line 171 of file ExtStxxlVector.h.
References double_blocked_index< size_type, modulo2, modulo1 >::pos.
template<typename size_type , size_type modulo2, size_type modulo1> double_blocked_index double_blocked_index< size_type, modulo2, modulo1 >::operator+ (size_type addend) const [inline]
Definition at line 151 of file ExtStxxlVector.h.
References double_blocked_index< size_type, modulo2, modulo1 >::double_blocked_index(), and double_blocked_index< size_type, modulo2, modulo1 >::pos.
template<typename size_type , size_type modulo2, size_type modulo1> double_blocked_index& double_blocked_index< size_type, modulo2, modulo1 >::operator++ () [inline]
Definition at line 99 of file ExtStxxlVector.h.
References double_blocked_index< size_type, modulo2, modulo1 >::block1, double_blocked_index< size_type, modulo2, modulo1 >::block2, double_blocked_index< size_type, modulo2, modulo1 >::modulo12, double_blocked_index< size_type, modulo2, modulo1 >::offset, and double_blocked_index< size_type, modulo2, modulo1 >::pos.
Referenced by double_blocked_index< size_type, modulo2, modulo1 >::operator++().
template<typename size_type , size_type modulo2, size_type modulo1> double_blocked_index double_blocked_index< size_type, modulo2, modulo1 >::operator++ (int) [inline]
Definition at line 119 of file ExtStxxlVector.h.
References double_blocked_index< size_type, modulo2, modulo1 >::operator++().
template<typename size_type , size_type modulo2, size_type modulo1> double_blocked_index& double_blocked_index< size_type, modulo2, modulo1 >::operator+= (size_type addend) [inline]
Definition at line 154 of file ExtStxxlVector.h.
References double_blocked_index< size_type, modulo2, modulo1 >::pos.
template<typename size_type , size_type modulo2, size_type modulo1> double_blocked_index double_blocked_index< size_type, modulo2, modulo1 >::operator- (size_type addend) const [inline]
Definition at line 158 of file ExtStxxlVector.h.
References double_blocked_index< size_type, modulo2, modulo1 >::double_blocked_index(), and double_blocked_index< size_type, modulo2, modulo1 >::pos.
template<typename size_type , size_type modulo2, size_type modulo1> size_type double_blocked_index< size_type, modulo2, modulo1 >::operator- (const double_blocked_index< size_type, modulo2, modulo1 > & dbi2) const [inline]
Definition at line 161 of file ExtStxxlVector.h.
References double_blocked_index< size_type, modulo2, modulo1 >::pos.
template<typename size_type , size_type modulo2, size_type modulo1> double_blocked_index& double_blocked_index< size_type, modulo2, modulo1 >::operator-- () [inline]
Definition at line 126 of file ExtStxxlVector.h.
References double_blocked_index< size_type, modulo2, modulo1 >::block1, double_blocked_index< size_type, modulo2, modulo1 >::block2, double_blocked_index< size_type, modulo2, modulo1 >::modulo12, double_blocked_index< size_type, modulo2, modulo1 >::offset, and double_blocked_index< size_type, modulo2, modulo1 >::pos.
Referenced by double_blocked_index< size_type, modulo2, modulo1 >::operator--().
template<typename size_type , size_type modulo2, size_type modulo1> double_blocked_index double_blocked_index< size_type, modulo2, modulo1 >::operator-- (int) [inline]
Definition at line 146 of file ExtStxxlVector.h.
References double_blocked_index< size_type, modulo2, modulo1 >::operator--().
template<typename size_type , size_type modulo2, size_type modulo1> double_blocked_index& double_blocked_index< size_type, modulo2, modulo1 >::operator-= (size_type subtrahend) [inline]
Definition at line 164 of file ExtStxxlVector.h.
References double_blocked_index< size_type, modulo2, modulo1 >::pos.
template<typename size_type , size_type modulo2, size_type modulo1> bool double_blocked_index< size_type, modulo2, modulo1 >::operator< (const double_blocked_index< size_type, modulo2, modulo1 > & dbi2) const [inline]
Definition at line 174 of file ExtStxxlVector.h.
References double_blocked_index< size_type, modulo2, modulo1 >::pos.
template<typename size_type , size_type modulo2, size_type modulo1> bool double_blocked_index< size_type, modulo2, modulo1 >::operator<= (const double_blocked_index< size_type, modulo2, modulo1 > & dbi2) const [inline]
Definition at line 177 of file ExtStxxlVector.h.
References double_blocked_index< size_type, modulo2, modulo1 >::pos.
template<typename size_type , size_type modulo2, size_type modulo1> double_blocked_index& double_blocked_index< size_type, modulo2, modulo1 >::operator= (size_type pos) [inline]
Definition at line 93 of file ExtStxxlVector.h.
References double_blocked_index< size_type, modulo2, modulo1 >::pos.
template<typename size_type , size_type modulo2, size_type modulo1> bool double_blocked_index< size_type, modulo2, modulo1 >::operator== (const double_blocked_index< size_type, modulo2, modulo1 > & dbi2) const [inline]
Definition at line 168 of file ExtStxxlVector.h.
References double_blocked_index< size_type, modulo2, modulo1 >::pos.
template<typename size_type , size_type modulo2, size_type modulo1> bool double_blocked_index< size_type, modulo2, modulo1 >::operator> (const double_blocked_index< size_type, modulo2, modulo1 > & dbi2) const [inline]
Definition at line 180 of file ExtStxxlVector.h.
References double_blocked_index< size_type, modulo2, modulo1 >::pos.
template<typename size_type , size_type modulo2, size_type modulo1> bool double_blocked_index< size_type, modulo2, modulo1 >::operator>= (const double_blocked_index< size_type, modulo2, modulo1 > & dbi2) const [inline]
Definition at line 183 of file ExtStxxlVector.h.
References double_blocked_index< size_type, modulo2, modulo1 >::pos.
template<typename size_type , size_type modulo2, size_type modulo1> double_blocked_index& double_blocked_index< size_type, modulo2, modulo1 >::operator>>= (size_type shift) [inline]
Definition at line 186 of file ExtStxxlVector.h.
References double_blocked_index< size_type, modulo2, modulo1 >::pos.
template<typename size_type , size_type modulo2, size_type modulo1> void double_blocked_index< size_type, modulo2, modulo1 >::set (size_type pos) [inline, private]
Invariant:
block2 * modulo12 + block1 * modulo1 + offset == pos && 0 <= block1 < modulo2 && 0 <= offset < modulo1
Definition at line 65 of file ExtStxxlVector.h.
References double_blocked_index< size_type, modulo2, modulo1 >::block1, double_blocked_index< size_type, modulo2, modulo1 >::block2, double_blocked_index< size_type, modulo2, modulo1 >::modulo12, double_blocked_index< size_type, modulo2, modulo1 >::offset, and double_blocked_index< size_type, modulo2, modulo1 >::pos.
Member Data Documentation
template<typename size_type , size_type modulo2, size_type modulo1> stxxl::unsigned_type double_blocked_index< size_type, modulo2, modulo1 >::block1 [private]
Definition at line 62 of file ExtStxxlVector.h.
Referenced by double_blocked_index< size_type, modulo2, modulo1 >::double_blocked_index(), double_blocked_index< size_type, modulo2, modulo1 >::get_block1(), double_blocked_index< size_type, modulo2, modulo1 >::operator++(), double_blocked_index< size_type, modulo2, modulo1 >::operator--(), and double_blocked_index< size_type, modulo2, modulo1 >::set().
template<typename size_type , size_type modulo2, size_type modulo1> stxxl::unsigned_type double_blocked_index< size_type, modulo2, modulo1 >::block2 [private]
Definition at line 62 of file ExtStxxlVector.h.
Referenced by double_blocked_index< size_type, modulo2, modulo1 >::double_blocked_index(), double_blocked_index< size_type, modulo2, modulo1 >::get_block2(), double_blocked_index< size_type, modulo2, modulo1 >::operator++(), double_blocked_index< size_type, modulo2, modulo1 >::operator--(), and double_blocked_index< size_type, modulo2, modulo1 >::set().
template<typename size_type , size_type modulo2, size_type modulo1> const size_type double_blocked_index< size_type, modulo2, modulo1 >::modulo12 = modulo1 * modulo2 [static, private]
Definition at line 59 of file ExtStxxlVector.h.
Referenced by double_blocked_index< size_type, modulo2, modulo1 >::double_blocked_index(), double_blocked_index< size_type, modulo2, modulo1 >::operator++(), double_blocked_index< size_type, modulo2, modulo1 >::operator--(), and double_blocked_index< size_type, modulo2, modulo1 >::set().
template<typename size_type , size_type modulo2, size_type modulo1> stxxl::unsigned_type double_blocked_index< size_type, modulo2, modulo1 >::offset [private]
Definition at line 62 of file ExtStxxlVector.h.
Referenced by double_blocked_index< size_type, modulo2, modulo1 >::double_blocked_index(), double_blocked_index< size_type, modulo2, modulo1 >::get_offset(), double_blocked_index< size_type, modulo2, modulo1 >::operator++(), double_blocked_index< size_type, modulo2, modulo1 >::operator--(), and double_blocked_index< size_type, modulo2, modulo1 >::set().
template<typename size_type , size_type modulo2, size_type modulo1> size_type double_blocked_index< size_type, modulo2, modulo1 >::pos [private]
Definition at line 61 of file ExtStxxlVector.h.
Referenced by double_blocked_index< size_type, modulo2, modulo1 >::double_blocked_index(), double_blocked_index< size_type, modulo2, modulo1 >::get_pos(), double_blocked_index< size_type, modulo2, modulo1 >::operator!=(), double_blocked_index< size_type, modulo2, modulo1 >::operator+(), double_blocked_index< size_type, modulo2, modulo1 >::operator++(), double_blocked_index< size_type, modulo2, modulo1 >::operator+=(), double_blocked_index< size_type, modulo2, modulo1 >::operator-(), double_blocked_index< size_type, modulo2, modulo1 >::operator--(), double_blocked_index< size_type, modulo2, modulo1 >::operator-=(), double_blocked_index< size_type, modulo2, modulo1 >::operator<(), double_blocked_index< size_type, modulo2, modulo1 >::operator<=(), double_blocked_index< size_type, modulo2, modulo1 >::operator=(), double_blocked_index< size_type, modulo2, modulo1 >::operator==(), double_blocked_index< size_type, modulo2, modulo1 >::operator>(), double_blocked_index< size_type, modulo2, modulo1 >::operator>=(), double_blocked_index< size_type, modulo2, modulo1 >::operator>>=(), and double_blocked_index< size_type, modulo2, modulo1 >::set().
The documentation for this class was generated from the following file:
local/deprecated/ExtStxxlVector.h