ExtLP: LPRow Class Reference
LPRow Class Reference
Detailed Description
(In)equality for LPs.
Class LPRow provides constraints for linear programs in the form
where a is a DSVector. l is referred to as left hand side, r as right hand side and a as row vector or the constraint vector. l and r may also take values #infinity. This static member is predefined, but may be overridden to meet the needs of the LP solver to be used.
LPRows allow to specify regular inequalities of the form
where can take any value of , by setting rhs and lhs to the same value or setting one of them to .
Since constraints in the regular form occur often, LPRows offers methods type() and value() for retreiving and of an LPRow in this form, respectively. Also, a constructor for LPRows given in regular form is provided.
Definition at line 42 of file LPRow.h.
Public Types
Types
enum Type { LESS_EQUAL, EQUAL, GREATER_EQUAL, RANGE }
(In)Equality of an LP row.
Public Member Functions
Construction / destruction
LPRow (int defDim=0)
Construct LPRow with a vector ready to hold defDim nonzeros.
~LPRow ()
Construct LPRow from passed rowVector, type and value.
Access / modification
Type type () const
get type of row.
void setType (LPRow::Type p_type)
set type of (in)equality
double value () const
double lhs () const
get left-hand side value.
std::string getName () const
get the name of the LP Row
void setName (std::string p_name)
access the name of the LP row
void setLhs (double p_left)
access left-hand side value.
double rhs () const
get right-hand side value of (in)equality.
void setRhs (double p_right)
access right-hand side value.
Consistency check
get constraint row vector
access constraint row vector.
bool isConsistent () const
check consistency.
Private Attributes
Data
double left
left-hand side of the constraint
double right
right-hand side of the constraint
std::vector< double > vec
the row vector
std::string name
Member Enumeration Documentation
enum LPRow::Type
(In)Equality of an LP row.
LPRows may be of one of the above Types. This datatype may be used for constructing new LPRows in the regular form.
Enumerator:
LESS_EQUAL
.
EQUAL
.
GREATER_EQUAL
.
RANGE
.
Definition at line 64 of file LPRow.h.
Constructor & Destructor Documentation
LPRow::LPRow (int defDim = 0) [inline, explicit]
Construct LPRow with a vector ready to hold defDim nonzeros.
Definition at line 77 of file LPRow.h.
References isConsistent().
LPRow::~LPRow () [inline]
Construct LPRow from passed rowVector, type and value.
destructor
Definition at line 102 of file LPRow.h.
Member Function Documentation
std::string LPRow::getName () const [inline]
get the name of the LP Row
Definition at line 172 of file LPRow.h.
References name.
bool LPRow::isConsistent () const [inline]
check consistency.
Definition at line 218 of file LPRow.h.
References vec.
Referenced by LPRow().
double LPRow::lhs () const [inline]
get left-hand side value.
Definition at line 166 of file LPRow.h.
References left.
Referenced by setType(), type(), and value().
double LPRow::rhs () const [inline]
get right-hand side value of (in)equality.
Definition at line 190 of file LPRow.h.
References right.
Referenced by setType(), type(), and value().
void LPRow::setLhs (double p_left) [inline]
access left-hand side value.
Definition at line 184 of file LPRow.h.
References left.
Referenced by ReadMPSUtil::readRows().
void LPRow::setName (std::string p_name) [inline]
access the name of the LP row
Definition at line 178 of file LPRow.h.
References name.
Referenced by ReadMPSUtil::readRows().
void LPRow::setRhs (double p_right) [inline]
access right-hand side value.
Definition at line 196 of file LPRow.h.
References right.
Referenced by ReadMPSUtil::readRows().
void LPRow::setType (LPRow::Type p_type) [inline]
set type of (in)equality
Definition at line 123 of file LPRow.h.
References DEBUG_ERROR, EQUAL, GREATER_EQUAL, INFINITY_VALUE, left, LESS_EQUAL, lhs(), RANGE, rhs(), and right.
Type LPRow::type () const [inline]
get type of row.
Definition at line 111 of file LPRow.h.
References EQUAL, GREATER_EQUAL, INFINITY_VALUE, LESS_EQUAL, lhs(), RANGE, and rhs().
Referenced by value().
double LPRow::value () const [inline]
This method returns for a LPRow in regular form. However, value() may only be called for LPRows with type() != RANGE.
Definition at line 151 of file LPRow.h.
References INFINITY_VALUE, lhs(), RANGE, rhs(), and type().
Member Data Documentation
double LPRow::left [private]
left-hand side of the constraint
Definition at line 48 of file LPRow.h.
Referenced by lhs(), setLhs(), and setType().
std::string LPRow::name [private]
Definition at line 51 of file LPRow.h.
Referenced by getName(), and setName().
double LPRow::right [private]
right-hand side of the constraint
Definition at line 49 of file LPRow.h.
Referenced by rhs(), setRhs(), and setType().
std::vector< double > LPRow::vec [private]
the row vector
Definition at line 50 of file LPRow.h.
Referenced by isConsistent().
The documentation for this class was generated from the following file:
local/deprecated/LPRow.h