ExtLP: Fraction Class Reference
Fraction Class Reference
Detailed Description
Definition at line 10 of file Fraction.h.
Public Member Functions
Fraction ()
Fraction (int numerator)
Fraction (int numerator, int denominator)
int getDenominator ()
int getNumerator ()
Fraction & operator+ (Fraction fraction)
Private Attributes
int denominator
int numerator
Constructor & Destructor Documentation
Fraction::Fraction () [inline]
Definition at line 15 of file Fraction.h.
References denominator, and numerator.
Referenced by operator+().
Fraction::Fraction (int numerator) [inline]
Definition at line 18 of file Fraction.h.
References numerator.
Fraction::Fraction (int numerator, int denominator) [inline]
Definition at line 21 of file Fraction.h.
References denominator, and numerator.
Member Function Documentation
int Fraction::getDenominator () [inline]
Definition at line 25 of file Fraction.h.
References denominator.
Referenced by operator+().
int Fraction::getNumerator () [inline]
Definition at line 28 of file Fraction.h.
References numerator.
Referenced by operator+().
Fraction& Fraction::operator+ (Fraction fraction) [inline]
Definition at line 31 of file Fraction.h.
References denominator, Fraction(), getDenominator(), getNumerator(), and numerator.
Member Data Documentation
int Fraction::denominator [private]
Definition at line 13 of file Fraction.h.
Referenced by Fraction(), getDenominator(), and operator+().
int Fraction::numerator [private]
Definition at line 12 of file Fraction.h.
Referenced by Fraction(), getNumerator(), and operator+().
The documentation for this class was generated from the following file:
local/deprecated/Fraction.h