ExtLP: MatrixBInverseRowAttr Class Reference
MatrixBInverseRowAttr Class Reference
Detailed Description
Stores row related properties of ExtMatrixBInverse container The limits to the row is [start, end) start includes and end excludes Also includes the other necessary properties such as row_index for fetching necessary details from ExtMatrixA.
Definition at line 53 of file ExtMatrixBInverse.h.
Public Member Functions
MatrixBInverseRowAttr ()
Simple Initialization.
MatrixBInverseRowAttr (unsigned int start, unsigned int end)
unsigned int get_capacity_end ()
Column index with respect to MatrixA container for fetching necessary details of this column such as name.
unsigned int get_end ()
unsigned int get_start ()
void set_capacity_end (unsigned int capacity_end)
void set_end (unsigned int end)
void set_start (unsigned int start)
Private Attributes
unsigned int capacity_end
Used for pre calculation of row-size during column-wise storage.
unsigned int end
unsigned int start
Constructor & Destructor Documentation
MatrixBInverseRowAttr::MatrixBInverseRowAttr () [inline]
Simple Initialization.
Definition at line 61 of file ExtMatrixBInverse.h.
MatrixBInverseRowAttr::MatrixBInverseRowAttr (unsigned int start, unsigned int end) [inline]
Definition at line 63 of file ExtMatrixBInverse.h.
References end, and start.
Member Function Documentation
unsigned int MatrixBInverseRowAttr::get_capacity_end () [inline]
Column index with respect to MatrixA container for fetching necessary details of this column such as name.
Definition at line 90 of file ExtMatrixBInverse.h.
References capacity_end.
Referenced by ExtMatrixBInverse::add_row_element().
unsigned int MatrixBInverseRowAttr::get_end () [inline]
Definition at line 82 of file ExtMatrixBInverse.h.
References end.
Referenced by ExtMatrixBInverse::add_row_element(), and ExtMatrixBInverse::store_row().
unsigned int MatrixBInverseRowAttr::get_start () [inline]
Definition at line 79 of file ExtMatrixBInverse.h.
References start.
Referenced by ExtMatrixBInverse::store_row().
void MatrixBInverseRowAttr::set_capacity_end (unsigned int capacity_end) [inline]
Definition at line 76 of file ExtMatrixBInverse.h.
References capacity_end.
Referenced by ExtMatrixBInverse::pre_calculate_row_structure().
void MatrixBInverseRowAttr::set_end (unsigned int end) [inline]
Definition at line 70 of file ExtMatrixBInverse.h.
References end.
Referenced by ExtMatrixBInverse::add_row_element(), and ExtMatrixBInverse::pre_calculate_row_structure().
void MatrixBInverseRowAttr::set_start (unsigned int start) [inline]
Definition at line 67 of file ExtMatrixBInverse.h.
References start.
Referenced by ExtMatrixBInverse::pre_calculate_row_structure().
Member Data Documentation
unsigned int MatrixBInverseRowAttr::capacity_end [private]
Used for pre calculation of row-size during column-wise storage.
Definition at line 58 of file ExtMatrixBInverse.h.
Referenced by get_capacity_end(), and set_capacity_end().
unsigned int MatrixBInverseRowAttr::end [private]
Definition at line 55 of file ExtMatrixBInverse.h.
Referenced by get_end(), MatrixBInverseRowAttr(), and set_end().
unsigned int MatrixBInverseRowAttr::start [private]
Definition at line 55 of file ExtMatrixBInverse.h.
Referenced by get_start(), MatrixBInverseRowAttr(), and set_start().
The documentation for this class was generated from the following file:
local/ExtMatrixBInverse.h