ExtLP: vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType > Class Template Reference
vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType > Class Template Reference
vector
Detailed Description
template<typename ValueType, unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64>
class vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >
External vector container.
Introduction to vector container: see STXXL Vector tutorial.
Design and Internals of vector container: see Vector.
For semantics of the methods see documentation of the STL std::vector
Template Parameters:
ValueType type of contained objects (POD with no references to internal memory)
PageSize number of blocks in a page
PagerType pager type, random_pager<x> or lru_pager<x>, where x is the default number of pages, default is lru_pager<8>
BlockSize external block size in bytes, default is 2 MiB
AllocStr one of allocation strategies: striping , RC , SR , or FR default is RC
Memory consumption: BlockSize*x*PageSize bytes
Warning:
Do not store references to the elements of an external vector. Such references might be invalidated during any following access to elements of the vector
Examples:
examples/containers/vector1.cpp.
Definition at line 705 of file ExtStxxlVector.h.
Classes
class bid_vector
Public Types
Extra Types
typedef vector_bufwriter
< iterator > bufwriter_type
vector_bufwriter compatible with this vector
typedef vector_bufreader
< const_iterator > bufreader_type
vector_bufreader compatible with this vector
typedef
vector_bufreader_reverse
< const_iterator > bufreader_reverse_type
vector_bufreader compatible with this vector
typedef bid_vector bids_container_type
typedef
bids_container_type::iterator bids_container_iterator
typedef
bids_container_type::const_iterator const_bids_container_iterator
typedef stxxl::typed_block
< BlockSize, ValueType > block_type
type of the block used in disk-memory transfers
typedef double_blocked_index
< SizeType, PageSize,
block_type::size > blocked_index_type
double-index type to reference individual elements in a block
Public Member Functions
Constructors/Destructors
vector (size_type n=0, stxxl::unsigned_type npages=pager_type().size())
Constructs external vector with n elements.
vector (stxxl::file *from, size_type size=size_type(-1), stxxl::unsigned_type npages=pager_type().size())
Construct vector from a file.
vector (const vector &obj)
copy-constructor
~vector ()
Modifier
void swap (vector &obj)
swap content
Miscellaneous
void allocate_page_cache () const
Allocate page cache, must be called to allow access to elements.
void deallocate_page_cache () const
allows to free the cache, but you may not access any element until call allocate_page_cache() again
void export_files (std::string filename_prefix)
Export data such that it is persistent on the file system. Resulting files will be numbered ascending.
stxxl::file * get_file () const
Get the file associated with this vector, or NULL.
Size and Capacity
size_type size () const
return the size of the vector.
bool empty () const
true if the vector's size is zero.
size_type capacity () const
Return the number of elelemtsn for which external memory has been allocated. capacity() is always greator than or equal to size().
size_type raw_capacity () const
Returns the number of bytes that the vector has allocated on disks.
void reserve (size_type n)
Reserves at least n elements in external memory.
void resize (size_type n)
Resize vector contents to n items.
void resize (size_type n, bool shrink_capacity)
Resize vector contents to n items, and allow the allocated external memory to shrink. Internal memory allocation remains unchanged.
Modifiers
void clear ()
Erases all of the elements and deallocates all external memory that is occupied.
void flush () const
Flushes the cache pages to the external memory.
Front and Back Access
void push_back (const_reference obj)
Append a new element at the end.
void pop_back ()
Removes the last element (without returning it, see back()).
Operators
reference back ()
Returns a reference to the last element, see More Notes.
reference front ()
Returns a reference to the first element, see More Notes.
const_reference back () const
Returns a constant reference to the last element, see More Notes.
const_reference front () const
Returns a constant reference to the first element, see More Notes.
vector & operator= (const vector &obj)
assignment operator
Iterator Construction
iterator begin ()
returns an iterator pointing to the beginning of the vector, see More Notes.
const_iterator begin () const
returns a const_iterator pointing to the beginning of the vector, see More Notes.
const_iterator cbegin () const
returns a const_iterator pointing to the beginning of the vector, see More Notes.
iterator end ()
returns an iterator pointing beyond the end of the vector, see More Notes.
const_iterator end () const
returns a const_iterator pointing beyond the end of the vector, see More Notes.
const_iterator cend () const
returns a const_iterator pointing beyond the end of the vector, see More Notes.
reverse_iterator rbegin ()
returns a reverse_iterator pointing to the end of the vector.
const_reverse_iterator rbegin () const
returns a reverse_iterator pointing to the end of the vector.
const_reverse_iterator crbegin () const
returns a reverse_iterator pointing to the end of the vector.
reverse_iterator rend ()
returns a reverse_iterator pointing beyond the beginning of the vector.
const_reverse_iterator rend () const
returns a reverse_iterator pointing beyond the beginning of the vector.
const_reverse_iterator crend () const
returns a reverse_iterator pointing beyond the beginning of the vector.
Direct Element Access
reference operator[] (size_type offset)
access the element at the given vector's offset
const_reference operator[] (size_type offset) const
access the element at the given vector's offset
reference at (size_type offset)
access the element at the given vector's offset
const_reference at (size_type offset) const
access the element at the given vector's offset
bool is_element_cached (size_type offset) const
return true if the given vector offset is in cache
Capacity
template<typename ForwardIterator >
void set_content (const ForwardIterator &bid_begin, const ForwardIterator &bid_end, size_type n)
Set the blocks and the size of this container explicitly. The vector must be completely empty before.
stxxl::unsigned_type numpages () const
Number of pages used by the pager.
Protected Member Functions
bids_container_iterator bid (const size_type &offset)
bids_container_iterator bid (const blocked_index_type &offset)
const_bids_container_iterator bid (const size_type &offset) const
const_bids_container_iterator bid (const blocked_index_type &offset) const
void block_externally_updated (size_type offset) const
void block_externally_updated (const blocked_index_type &offset) const
const_reference const_element (size_type offset) const
const_reference const_element (const blocked_index_type &offset) const
reference element (size_type offset)
reference element (const blocked_index_type &offset)
bool is_page_cached (const blocked_index_type &offset) const
void page_externally_updated (stxxl::unsigned_type page_no) const
void read_page (stxxl::int_type page_no, stxxl::int_type cache_slot) const
void write_page (stxxl::int_type page_no, stxxl::int_type cache_slot) const
Private Types
enum { valid_on_disk = 0, uninitialized = 1, dirty = 2 }
Private Member Functions
void _resize (size_type n)
Resize vector, only allow capacity growth.
void _resize_shrink_capacity (size_type n)
Resize vector, also allow reduction of external memory capacity.
stxxl::uint64 file_length () const
size_type size_from_file_length (stxxl::uint64 file_length) const
Private Attributes
alloc_strategy_type m_alloc_strategy
bids_container_type m_bids
stxxl::block_manager * m_bm
stxxl::simple_vector
< block_type > * m_cache
bool m_exported
std::queue< stxxl::int_type > m_free_slots
stxxl::file * m_from
std::vector< unsigned char > m_page_status
status of each page (valid_on_disk, uninitialized or dirty)
std::vector< stxxl::int_type > m_page_to_slot
pager_type m_pager
size_type m_size
stxxl::simple_vector
< stxxl::int_type > m_slot_to_page
Standard Types
enum constants { block_size = BlockSize, page_size = PageSize, on_disk = -1 }
typedef ValueType value_type
The type of elements stored in the vector.
typedef value_type & reference
reference to value_type
typedef const value_type & const_reference
constant reference to value_type
typedef value_type * pointer
pointer to value_type
typedef const value_type * const_pointer
constant pointer to value_type
typedef SizeType size_type
an unsigned 64-bit integral type
typedef stxxl::int64 difference_type
typedef PagerType pager_type
typedef AllocStr alloc_strategy_type
typedef vector_iterator
< value_type,
alloc_strategy_type, size_type,
difference_type, block_size,
pager_type, page_size > iterator
iterator used to iterate through a vector, see More Notes.
typedef const_vector_iterator
< value_type,
alloc_strategy_type, size_type,
difference_type, block_size,
pager_type, page_size > const_iterator
constant iterator used to iterate through a vector, see More Notes.
typedef std::reverse_iterator
< iterator > reverse_iterator
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator
Member Typedef Documentation
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> typedef AllocStr vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::alloc_strategy_type
Definition at line 725 of file ExtStxxlVector.h.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> typedef bids_container_type::iterator vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::bids_container_iterator
Definition at line 769 of file ExtStxxlVector.h.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> typedef bid_vector vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::bids_container_type
Definition at line 768 of file ExtStxxlVector.h.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> typedef stxxl::typed_block<BlockSize, ValueType> vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::block_type
type of the block used in disk-memory transfers
Definition at line 773 of file ExtStxxlVector.h.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> typedef double_blocked_index<SizeType, PageSize, block_type::size> vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::blocked_index_type
double-index type to reference individual elements in a block
Definition at line 775 of file ExtStxxlVector.h.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> typedef vector_bufreader_reverse<const_iterator> vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::bufreader_reverse_type
vector_bufreader compatible with this vector
Definition at line 756 of file ExtStxxlVector.h.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> typedef vector_bufreader<const_iterator> vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::bufreader_type
vector_bufreader compatible with this vector
Definition at line 753 of file ExtStxxlVector.h.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> typedef vector_bufwriter<iterator> vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::bufwriter_type
vector_bufwriter compatible with this vector
Definition at line 750 of file ExtStxxlVector.h.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> typedef bids_container_type::const_iterator vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::const_bids_container_iterator
Definition at line 770 of file ExtStxxlVector.h.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> typedef const_vector_iterator<value_type, alloc_strategy_type, size_type, difference_type, block_size, pager_type, page_size> vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::const_iterator
constant iterator used to iterate through a vector, see More Notes.
Definition at line 739 of file ExtStxxlVector.h.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> typedef const value_type* vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::const_pointer
constant pointer to value_type
Definition at line 719 of file ExtStxxlVector.h.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> typedef const value_type& vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::const_reference
constant reference to value_type
Definition at line 715 of file ExtStxxlVector.h.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> typedef std::reverse_iterator<const_iterator> vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::const_reverse_iterator
Definition at line 742 of file ExtStxxlVector.h.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> typedef stxxl::int64 vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::difference_type
Definition at line 722 of file ExtStxxlVector.h.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> typedef vector_iterator<value_type, alloc_strategy_type, size_type, difference_type, block_size, pager_type, page_size> vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::iterator
iterator used to iterate through a vector, see More Notes.
Definition at line 734 of file ExtStxxlVector.h.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> typedef PagerType vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::pager_type
Definition at line 724 of file ExtStxxlVector.h.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> typedef value_type* vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::pointer
pointer to value_type
Definition at line 717 of file ExtStxxlVector.h.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> typedef value_type& vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::reference
reference to value_type
Definition at line 713 of file ExtStxxlVector.h.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> typedef std::reverse_iterator<iterator> vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::reverse_iterator
Definition at line 741 of file ExtStxxlVector.h.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> typedef SizeType vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::size_type
an unsigned 64-bit integral type
Definition at line 721 of file ExtStxxlVector.h.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> typedef ValueType vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::value_type
The type of elements stored in the vector.
Definition at line 711 of file ExtStxxlVector.h.
Member Enumeration Documentation
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> anonymous enum [private]
Enumerator:
valid_on_disk
uninitialized
dirty
Definition at line 786 of file ExtStxxlVector.h.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> enum vector::constants
Enumerator:
block_size
page_size
on_disk
Definition at line 726 of file ExtStxxlVector.h.
Constructor & Destructor Documentation
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::vector (size_type n = 0, stxxl::unsigned_type npages = pager_type().size()) [inline]
Constructs external vector with n elements.
Parameters:
n Number of elements.
npages Number of cached pages.
Definition at line 823 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::allocate_page_cache(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_alloc_strategy, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_bids, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_bm, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_free_slots, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_page_status, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_page_to_slot, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::numpages(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::on_disk, and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::uninitialized.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::vector (stxxl::file * from, size_type size = size_type(-1), stxxl::unsigned_type npages = pager_type().size()) [inline]
Construct vector from a file.
Parameters:
from file to be constructed from
size Number of elements.
npages Number of cached pages.
Warning:
Only one vector can be assigned to a particular (physical) file. The block size of the vector must be a multiple of the element size sizeof(ValueType) and the page size (4096).
Definition at line 1086 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::allocate_page_cache(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_bids, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_bm, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_free_slots, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_page_status, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_page_to_slot, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::numpages(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::on_disk, and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::valid_on_disk.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::vector (const vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType > & obj) [inline]
copy-constructor
Definition at line 1128 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::allocate_page_cache(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::begin(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::end(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_alloc_strategy, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_bids, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_bm, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_exported, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_free_slots, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_page_status, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_page_to_slot, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::numpages(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::on_disk, and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::uninitialized.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::~vector () [inline]
Definition at line 1291 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::file_length(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::flush(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_bids, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_bm, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_cache, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_exported, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_from, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::size(), and STXXL_VERBOSE_VECTOR.
Member Function Documentation
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> void vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::_resize (size_type n) [inline, private]
Resize vector, only allow capacity growth.
Definition at line 966 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_free_slots, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_page_status, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_page_to_slot, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_size, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::on_disk, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::page_size, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::reserve(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::uninitialized.
Referenced by vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::resize().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> void vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::_resize_shrink_capacity (size_type n) [inline, private]
Resize vector, also allow reduction of external memory capacity.
Definition at line 983 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_bids, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_bm, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_from, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_page_status, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_size, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::page_size, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::reserve(), STXXL_VERBOSE_VECTOR, and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::valid_on_disk.
Referenced by vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::resize().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> void vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::allocate_page_cache () const [inline]
Allocate page cache, must be called to allow access to elements.
Definition at line 875 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_cache, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::numpages(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::page_size.
Referenced by vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::vector().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> reference vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::at (size_type offset) [inline]
access the element at the given vector's offset
Definition at line 1242 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::element(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::size().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> const_reference vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::at (size_type offset) const [inline]
access the element at the given vector's offset
Definition at line 1247 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::const_element(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::size().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> reference vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::back () [inline]
Returns a reference to the last element, see More Notes.
Definition at line 1058 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::element(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_size.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> const_reference vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::back () const [inline]
Returns a constant reference to the last element, see More Notes.
Definition at line 1066 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::const_element(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_size.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> iterator vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::begin () [inline]
returns an iterator pointing to the beginning of the vector, see More Notes.
Definition at line 1178 of file ExtStxxlVector.h.
Referenced by vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::cbegin(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::crend(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::rend(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::vector().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> const_iterator vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::begin () const [inline]
returns a const_iterator pointing to the beginning of the vector, see More Notes.
Definition at line 1182 of file ExtStxxlVector.h.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> bids_container_iterator vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::bid (const size_type & offset) [inline, protected]
Definition at line 1372 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_bids, and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::size().
Referenced by vector_iterator< ValueType, AllocStr, SizeType, DiffType, BlockSize, PagerType, PageSize >::bid().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> bids_container_iterator vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::bid (const blocked_index_type & offset) [inline, protected]
Definition at line 1377 of file ExtStxxlVector.h.
References double_blocked_index< size_type, modulo2, modulo1 >::get_block1(), double_blocked_index< size_type, modulo2, modulo1 >::get_block2(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_bids.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> const_bids_container_iterator vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::bid (const size_type & offset) const [inline, protected]
Definition at line 1382 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_bids, and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::size().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> const_bids_container_iterator vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::bid (const blocked_index_type & offset) const [inline, protected]
Definition at line 1387 of file ExtStxxlVector.h.
References double_blocked_index< size_type, modulo2, modulo1 >::get_block1(), double_blocked_index< size_type, modulo2, modulo1 >::get_block2(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_bids.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> void vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::block_externally_updated (size_type offset) const [inline, protected]
Definition at line 1492 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::page_externally_updated(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::page_size.
Referenced by vector_iterator< ValueType, AllocStr, SizeType, DiffType, BlockSize, PagerType, PageSize >::block_externally_updated(), and const_vector_iterator< ValueType, AllocStr, SizeType, DiffType, BlockSize, PagerType, PageSize >::block_externally_updated().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> void vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::block_externally_updated (const blocked_index_type & offset) const [inline, protected]
Definition at line 1495 of file ExtStxxlVector.h.
References double_blocked_index< size_type, modulo2, modulo1 >::get_block2(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::page_externally_updated().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> size_type vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::capacity () const [inline]
Return the number of elelemtsn for which external memory has been allocated. capacity() is always greator than or equal to size().
Definition at line 903 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_bids.
Referenced by vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::reserve().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> const_iterator vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::cbegin () const [inline]
returns a const_iterator pointing to the beginning of the vector, see More Notes.
Definition at line 1186 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::begin().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> const_iterator vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::cend () const [inline]
returns a const_iterator pointing beyond the end of the vector, see More Notes.
Definition at line 1198 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::end().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> void vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::clear () [inline]
Erases all of the elements and deallocates all external memory that is occupied.
Definition at line 1023 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_bids, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_bm, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_free_slots, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_from, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_page_status, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_page_to_slot, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_size, and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::numpages().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> const_reference vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::const_element (size_type offset) const [inline, protected]
Definition at line 1498 of file ExtStxxlVector.h.
Referenced by vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::at(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::back(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::front(), vector_iterator< ValueType, AllocStr, SizeType, DiffType, BlockSize, PagerType, PageSize >::operator*(), const_vector_iterator< ValueType, AllocStr, SizeType, DiffType, BlockSize, PagerType, PageSize >::operator*(), vector_iterator< ValueType, AllocStr, SizeType, DiffType, BlockSize, PagerType, PageSize >::operator->(), const_vector_iterator< ValueType, AllocStr, SizeType, DiffType, BlockSize, PagerType, PageSize >::operator->(), vector_iterator< ValueType, AllocStr, SizeType, DiffType, BlockSize, PagerType, PageSize >::operator[](), const_vector_iterator< ValueType, AllocStr, SizeType, DiffType, BlockSize, PagerType, PageSize >::operator[](), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::operator[]().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> const_reference vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::const_element (const blocked_index_type & offset) const [inline, protected]
Definition at line 1501 of file ExtStxxlVector.h.
References double_blocked_index< size_type, modulo2, modulo1 >::get_block1(), double_blocked_index< size_type, modulo2, modulo1 >::get_block2(), double_blocked_index< size_type, modulo2, modulo1 >::get_offset(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_cache, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_free_slots, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_page_to_slot, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_pager, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_slot_to_page, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::on_disk, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::page_size, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::read_page(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::write_page().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> const_reverse_iterator vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::crbegin () const [inline]
returns a reverse_iterator pointing to the end of the vector.
Definition at line 1211 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::end().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> const_reverse_iterator vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::crend () const [inline]
returns a reverse_iterator pointing beyond the beginning of the vector.
Definition at line 1223 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::begin().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> void vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::deallocate_page_cache () const [inline]
allows to free the cache, but you may not access any element until call allocate_page_cache() again
Definition at line 883 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::flush(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_cache.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> reference vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::element (size_type offset) [inline, protected]
Definition at line 1426 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::size().
Referenced by vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::at(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::back(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::front(), vector_iterator< ValueType, AllocStr, SizeType, DiffType, BlockSize, PagerType, PageSize >::operator*(), vector_iterator< ValueType, AllocStr, SizeType, DiffType, BlockSize, PagerType, PageSize >::operator->(), vector_iterator< ValueType, AllocStr, SizeType, DiffType, BlockSize, PagerType, PageSize >::operator[](), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::operator[](), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::push_back().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> reference vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::element (const blocked_index_type & offset) [inline, protected]
Definition at line 1432 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::dirty, double_blocked_index< size_type, modulo2, modulo1 >::get_block1(), double_blocked_index< size_type, modulo2, modulo1 >::get_block2(), double_blocked_index< size_type, modulo2, modulo1 >::get_offset(), double_blocked_index< size_type, modulo2, modulo1 >::get_pos(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_cache, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_free_slots, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_page_status, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_page_to_slot, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_pager, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_slot_to_page, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::on_disk, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::page_size, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::read_page(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::size(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::write_page().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> bool vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::empty () const [inline]
true if the vector's size is zero.
Examples:
examples/containers/vector1.cpp.
Definition at line 897 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_size.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> iterator vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::end () [inline]
returns an iterator pointing beyond the end of the vector, see More Notes.
Definition at line 1190 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_size.
Referenced by vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::cend(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::crbegin(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::rbegin(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::vector().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> const_iterator vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::end () const [inline]
returns a const_iterator pointing beyond the end of the vector, see More Notes.
Definition at line 1194 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_size.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> void vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::export_files (std::string filename_prefix) [inline]
Export data such that it is persistent on the file system. Resulting files will be numbered ascending.
Definition at line 1326 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_bids, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_exported, and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_size.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> stxxl::uint64 vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::file_length () const [inline, private]
Definition at line 804 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::size().
Referenced by vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::~vector().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> void vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::flush () const [inline]
Flushes the cache pages to the external memory.
Definition at line 1263 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_free_slots, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_page_to_slot, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_slot_to_page, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::numpages(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::on_disk, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::page_size, STXXL_VERBOSE_VECTOR, and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::write_page().
Referenced by vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::deallocate_page_cache(), vector_iterator< ValueType, AllocStr, SizeType, DiffType, BlockSize, PagerType, PageSize >::flush(), const_vector_iterator< ValueType, AllocStr, SizeType, DiffType, BlockSize, PagerType, PageSize >::flush(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::~vector().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> reference vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::front () [inline]
Returns a reference to the first element, see More Notes.
Definition at line 1062 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::element().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> const_reference vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::front () const [inline]
Returns a constant reference to the first element, see More Notes.
Definition at line 1070 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::const_element().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> stxxl::file* vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::get_file () const [inline]
Get the file associated with this vector, or NULL.
Definition at line 1342 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_from.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> bool vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::is_element_cached (size_type offset) const [inline]
return true if the given vector offset is in cache
Definition at line 1253 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::is_page_cached().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> bool vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::is_page_cached (const blocked_index_type & offset) const [inline, protected]
Definition at line 1536 of file ExtStxxlVector.h.
References double_blocked_index< size_type, modulo2, modulo1 >::get_block2(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_page_to_slot.
Referenced by vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::is_element_cached().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> stxxl::unsigned_type vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::numpages () const [inline]
Number of pages used by the pager.
Definition at line 1365 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_pager.
Referenced by vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::allocate_page_cache(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::clear(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::flush(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::vector().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> vector& vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::operator= (const vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType > & obj) [inline]
assignment operator
Definition at line 1164 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::swap().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> reference vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::operator[] (size_type offset) [inline]
access the element at the given vector's offset
Definition at line 1233 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::element().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> const_reference vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::operator[] (size_type offset) const [inline]
access the element at the given vector's offset
Definition at line 1237 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::const_element().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> void vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::page_externally_updated (stxxl::unsigned_type page_no) const [inline, protected]
Definition at line 1477 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::dirty, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_free_slots, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_page_status, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_page_to_slot, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::on_disk, STXXL_VERBOSE_VECTOR, and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::valid_on_disk.
Referenced by vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::block_externally_updated().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> void vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::pop_back () [inline]
Removes the last element (without returning it, see back()).
Examples:
examples/containers/vector1.cpp.
Definition at line 1048 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_size, and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::resize().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> void vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::push_back (const_reference obj) [inline]
Append a new element at the end.
Examples:
examples/containers/vector1.cpp.
Definition at line 1042 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::element(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_size, and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::resize().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> size_type vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::raw_capacity () const [inline]
Returns the number of bytes that the vector has allocated on disks.
Definition at line 907 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_bids.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> reverse_iterator vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::rbegin () [inline]
returns a reverse_iterator pointing to the end of the vector.
Definition at line 1203 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::end().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> const_reverse_iterator vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::rbegin () const [inline]
returns a reverse_iterator pointing to the end of the vector.
Definition at line 1207 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::end().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> void vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::read_page (stxxl::int_type page_no, stxxl::int_type cache_slot) const [inline, protected]
Definition at line 1392 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_bids, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_page_status, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::page_size, STXXL_VERBOSE_VECTOR, and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::uninitialized.
Referenced by vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::const_element(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::element().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> reverse_iterator vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::rend () [inline]
returns a reverse_iterator pointing beyond the beginning of the vector.
Definition at line 1215 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::begin().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> const_reverse_iterator vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::rend () const [inline]
returns a reverse_iterator pointing beyond the beginning of the vector.
Definition at line 1219 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::begin().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> void vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::reserve (size_type n) [inline]
Reserves at least n elements in external memory.
If n is less than or equal to capacity(), this call has no effect. Otherwise, it is a request for allocation of additional external memory. If the request is successful, then capacity() is greater than or equal to n; otherwise capacity() is unchanged. In either case, size() is unchanged.
Definition at line 918 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::capacity(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_alloc_strategy, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_bids, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_bm, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_from, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_page_status, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_page_to_slot, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::on_disk, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::page_size, STXXL_VERBOSE_VECTOR, and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::uninitialized.
Referenced by vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::_resize(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::_resize_shrink_capacity().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> void vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::resize (size_type n) [inline]
Resize vector contents to n items.
Warning:
this will not call the constructor of objects in external memory!
Definition at line 948 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::_resize().
Referenced by vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::pop_back(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::push_back().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> void vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::resize (size_type n, bool shrink_capacity) [inline]
Resize vector contents to n items, and allow the allocated external memory to shrink. Internal memory allocation remains unchanged.
Warning:
this will not call the constructor of objects in external memory!
Definition at line 955 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::_resize(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::_resize_shrink_capacity().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> template<typename ForwardIterator > void vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::set_content (const ForwardIterator & bid_begin, const ForwardIterator & bid_end, size_type n) [inline]
Set the blocks and the size of this container explicitly. The vector must be completely empty before.
Definition at line 1354 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_bids, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_page_status, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_page_to_slot, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_size, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::on_disk, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::page_size, and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::valid_on_disk.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> size_type vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::size () const [inline]
return the size of the vector.
Definition at line 893 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_size.
Referenced by vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::at(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::bid(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::element(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::file_length(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::~vector().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> size_type vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::size_from_file_length (stxxl::uint64 file_length) const [inline, private]
Definition at line 798 of file ExtStxxlVector.h.
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> void vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::swap (vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType > & obj) [inline]
swap content
Definition at line 855 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_alloc_strategy, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_bids, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_cache, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_exported, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_free_slots, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_from, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_page_status, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_page_to_slot, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_pager, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_size, and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_slot_to_page.
Referenced by vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::operator=().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> void vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::write_page (stxxl::int_type page_no, stxxl::int_type cache_slot) const [inline, protected]
Definition at line 1408 of file ExtStxxlVector.h.
References vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::dirty, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_bids, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_page_status, vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::page_size, STXXL_VERBOSE_VECTOR, and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::valid_on_disk.
Referenced by vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::const_element(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::element(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::flush().
Member Data Documentation
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> alloc_strategy_type vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_alloc_strategy [private]
Definition at line 780 of file ExtStxxlVector.h.
Referenced by vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::reserve(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::swap(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::vector().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> bids_container_type vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_bids [private]
Definition at line 782 of file ExtStxxlVector.h.
Referenced by vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::_resize_shrink_capacity(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::bid(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::capacity(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::clear(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::export_files(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::raw_capacity(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::read_page(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::reserve(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::set_content(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::swap(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::vector(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::write_page(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::~vector().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> stxxl::block_manager* vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_bm [private]
Definition at line 796 of file ExtStxxlVector.h.
Referenced by vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::_resize_shrink_capacity(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::clear(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::reserve(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::vector(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::~vector().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> stxxl::simple_vector<block_type>* vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_cache [mutable, private]
Definition at line 794 of file ExtStxxlVector.h.
Referenced by vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::allocate_page_cache(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::const_element(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::deallocate_page_cache(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::element(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::swap(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::~vector().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> bool vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_exported [private]
Definition at line 797 of file ExtStxxlVector.h.
Referenced by vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::export_files(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::swap(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::vector(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::~vector().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> std::queue<stxxl::int_type> vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_free_slots [mutable, private]
Definition at line 793 of file ExtStxxlVector.h.
Referenced by vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::_resize(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::clear(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::const_element(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::element(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::flush(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::page_externally_updated(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::swap(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::vector().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> stxxl::file* vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_from [private]
Definition at line 795 of file ExtStxxlVector.h.
Referenced by vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::_resize_shrink_capacity(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::clear(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::get_file(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::reserve(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::swap(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::~vector().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> std::vector<unsigned char> vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_page_status [mutable, private]
status of each page (valid_on_disk, uninitialized or dirty)
Definition at line 790 of file ExtStxxlVector.h.
Referenced by vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::_resize(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::_resize_shrink_capacity(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::clear(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::element(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::page_externally_updated(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::read_page(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::reserve(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::set_content(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::swap(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::vector(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::write_page().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> std::vector<stxxl::int_type> vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_page_to_slot [mutable, private]
Definition at line 791 of file ExtStxxlVector.h.
Referenced by vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::_resize(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::clear(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::const_element(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::element(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::flush(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::is_page_cached(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::page_externally_updated(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::reserve(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::set_content(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::swap(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::vector().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> pager_type vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_pager [mutable, private]
Definition at line 783 of file ExtStxxlVector.h.
Referenced by vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::const_element(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::element(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::numpages(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::swap().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> size_type vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_size [private]
Definition at line 781 of file ExtStxxlVector.h.
Referenced by vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::_resize(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::_resize_shrink_capacity(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::back(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::clear(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::empty(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::end(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::export_files(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::pop_back(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::push_back(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::set_content(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::size(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::swap().
template<typename ValueType , unsigned PageSize = 4, typename PagerType = stxxl::lru_pager<1>, unsigned BlockSize = STXXL_DEFAULT_BLOCK_SIZE(ValueType), typename AllocStr = STXXL_DEFAULT_ALLOC_STRATEGY, typename SizeType = stxxl::uint64> stxxl::simple_vector<stxxl::int_type> vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::m_slot_to_page [mutable, private]
Definition at line 792 of file ExtStxxlVector.h.
Referenced by vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::const_element(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::element(), vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::flush(), and vector< ValueType, PageSize, PagerType, BlockSize, AllocStr, SizeType >::swap().
The documentation for this class was generated from the following file:
local/deprecated/ExtStxxlVector.h