ExtLP: Test Class Reference
Test Class Reference
Detailed Description
Definition at line 17 of file Test.h.
Static Public Member Functions
static void test ()
Test template.
static void testExtMatrixA (ExtLPDSSet &extDataSet)
static void testExtNameMap ()
static void testExtPackedVector ()
static void testExtVector ()
static void testExtVectorPrototype ()
Testing ExtVector.
static void testLinkedList ()
static void testMatrixBInverse (ExtLPDSSet &extDataSet)
static void testPackedVector2 ()
Testing Packed Vector.
Member Function Documentation
static void Test::test () [inline, static]
Test template.
Definition at line 151 of file Test.h.
References CONSOLE_PRINTLN.
static void Test::testExtMatrixA (ExtLPDSSet & extDataSet) [inline, static]
Column-wise display of LP Tableau
Obj Row in Rhs Column
---------------- Sparsity Analysis
Definition at line 255 of file Test.h.
References ExtLPDSSet::A, DEBUG_FILE, DEBUG_FILE_WITH_TIMESTAMP, DEBUG_SIMPLE, ExtMatrixA::get_col_attr(), MatrixAColAttr::get_col_name(), ExtMatrixA::get_col_nnz(), ExtMatrixA::get_col_sparsity(), ExtMatrixA::get_columns_count(), PackedElement< ItemClass >::get_index(), ExtLPDSSet::get_objective_name(), MatrixAColAttr::get_objective_value(), ExtLPDSSet::get_problem_name(), ExtLPDSSet::get_rhs_name(), MatrixARowAttr::get_rhs_value(), ExtMatrixA::get_row_attr(), MatrixARowAttr::get_row_name(), MatrixARowAttr::get_row_type_str(), ExtMatrixA::get_rows_count(), PackedElement< ItemClass >::get_value(), MAX_KEY_LEN, and ExtMatrixA::store_column().
static void Test::testExtNameMap () [inline, static]
Inserting 1 million strings
Definition at line 19 of file Test.h.
References CONSOLE_PRINTLN, DEBUG_MEMORY, and ExtNameMap::set().
static void Test::testExtPackedVector () [inline, static]
Definition at line 228 of file Test.h.
References PackedVector< ItemClass >::add(), CONSOLE_PRINTLN, DEBUG_MEMORY, and REAL.
static void Test::testExtVector () [inline, static]
Definition at line 186 of file Test.h.
References ExtVector::add(), ExtVector::allocate_cache(), CONSOLE_PRINTLN, ExtVector::deallocate_cache(), DEBUG_MEMORY, REAL, and ExtVector::resize().
static void Test::testExtVectorPrototype () [inline, static]
Testing ExtVector.
Definition at line 160 of file Test.h.
References PackedVectorPrototype::add(), CONSOLE_PRINTLN, and DEBUG_MEMORY.
static void Test::testLinkedList () [inline, static]
Definition at line 38 of file Test.h.
References LinkedList< ItemClass >::add(), LinkedList< ItemClass >::begin(), LinkedList< ItemClass >::clear(), CONSOLE_PRINTLN, DEBUG, DEBUG_ERROR, DEBUG_MEMORY, LinkedList< ItemClass >::end(), REAL, and LinkedList< ItemClass >::size().
static void Test::testMatrixBInverse (ExtLPDSSet & extDataSet) [inline, static]
Definition at line 349 of file Test.h.
References ExtLPDSSet::A, PackedVector< ItemClass >::begin(), ExtLPDSSet::BInverse, DEBUG, DEBUG_FILE, DEBUG_FILE_WITH_TIMESTAMP, PackedVector< ItemClass >::end(), MatrixBInverseColAttr::get_a_col_index(), ExtMatrixBInverse::get_col_attr(), ExtMatrixA::get_col_attr(), MatrixAColAttr::get_col_name(), ExtMatrixBInverse::get_columns_count(), PackedElement< ItemClass >::get_index(), ExtMatrixA::get_row_attr(), MatrixARowAttr::get_row_name(), ExtMatrixBInverse::get_rows_count(), PackedElement< ItemClass >::get_value(), MAX_KEY_LEN, and ExtMatrixBInverse::store_column().
static void Test::testPackedVector2 () [inline, static]
Testing Packed Vector.
Definition at line 131 of file Test.h.
References PackedVector< ItemClass >::add(), CONSOLE_PRINTLN, PackedVector< ItemClass >::displayVector(), and REAL.
The documentation for this class was generated from the following file:
local/Test.h