ExtLP: ExtColVector Class Reference
ExtColVector Class Reference
Detailed Description
Definition at line 13 of file ExtColVector.h.
Public Types
typedef ExtPackedVector::iterator iterator
Accessing iterator of the PackedVector.
Public Member Functions
Construction / destruction
ExtColVector (PackedColVector &packedColVector)
default constructor.
void storeFromPackedVector (PackedVector &packedVector)
Access / modification
double obj () const
get objective value.
void setObj (double p_object)
access objective value.
double upper () const
get upper bound.
void setUpper (double p_up)
access upper bound.
double lower () const
get lower bound.
std::string getName () const
get name of the LP Column
double getRowElement (unsigned int index)
get the absolute index element of the current packed col vector
void setName (std::string p_name)
access the name of the LP Column
void setLower (double p_low)
access lower bound.
iterator begin ()
Returns the beginning iterator.
iterator end ()
Returns the ending iterator.
void allocate_cache ()
Allocating cache.
void deallocate_cache ()
Deallocating cache.
unsigned int real_size ()
gets the real size of vector (size when unpacked)
float get_sparsity ()
gets the sparsity of the vector
unsigned int get_nnz ()
gets the total number of non-zero values in the vector
Private Member Functions
void deallocatePackedVector ()
Private Attributes
Data
double m_up
upper bound
double m_low
lower bound
double m_object
objective value
ExtPackedVector * m_vctPacked
std::string m_name
column vector - packed version
Member Typedef Documentation
typedef ExtPackedVector::iterator ExtColVector::iterator
Accessing iterator of the PackedVector.
Definition at line 33 of file ExtColVector.h.
Constructor & Destructor Documentation
ExtColVector::ExtColVector (PackedColVector & packedColVector) [inline, explicit]
default constructor.
Construct LPCol with a column vector ready for taking defDim nonzeros.
Definition at line 41 of file ExtColVector.h.
References m_vctPacked.
Member Function Documentation
void ExtColVector::allocate_cache () [inline]
Allocating cache.
Definition at line 124 of file ExtColVector.h.
References ExtPackedVector< ItemClass >::allocate_cache(), and m_vctPacked.
iterator ExtColVector::begin () [inline]
Returns the beginning iterator.
Definition at line 115 of file ExtColVector.h.
References ExtPackedVector< ItemClass >::begin(), and m_vctPacked.
void ExtColVector::deallocate_cache () [inline]
Deallocating cache.
Definition at line 128 of file ExtColVector.h.
References ExtPackedVector< ItemClass >::deallocate_cache(), and m_vctPacked.
void ExtColVector::deallocatePackedVector () [inline, private]
Definition at line 25 of file ExtColVector.h.
References m_vctPacked.
iterator ExtColVector::end () [inline]
Returns the ending iterator.
Definition at line 120 of file ExtColVector.h.
References ExtPackedVector< ItemClass >::end(), and m_vctPacked.
unsigned int ExtColVector::get_nnz () [inline]
gets the total number of non-zero values in the vector
Definition at line 140 of file ExtColVector.h.
References m_vctPacked, and ExtPackedVector< ItemClass >::nnz().
Referenced by ExtReadMPSUtil::readMPS().
float ExtColVector::get_sparsity () [inline]
gets the sparsity of the vector
Definition at line 136 of file ExtColVector.h.
References ExtPackedVector< ItemClass >::get_sparsity(), and m_vctPacked.
Referenced by ExtReadMPSUtil::readCols(), and ExtReadMPSUtil::readMPS().
std::string ExtColVector::getName () const [inline]
get name of the LP Column
Definition at line 87 of file ExtColVector.h.
References m_name.
Referenced by ExtReadMPSUtil::readCols().
double ExtColVector::getRowElement (unsigned int index) [inline]
get the absolute index element of the current packed col vector
Definition at line 92 of file ExtColVector.h.
References ExtPackedVector< ItemClass >::allocate_cache(), ExtPackedVector< ItemClass >::deallocate_cache(), DEBUG_ERROR, ExtPackedVector< ItemClass >::get_absolute_item_value(), m_vctPacked, and REAL.
double ExtColVector::lower () const [inline]
get lower bound.
Definition at line 82 of file ExtColVector.h.
References m_low.
double ExtColVector::obj () const [inline]
get objective value.
Definition at line 64 of file ExtColVector.h.
References m_object.
unsigned int ExtColVector::real_size () [inline]
gets the real size of vector (size when unpacked)
Definition at line 132 of file ExtColVector.h.
References m_vctPacked, and ExtPackedVector< ItemClass >::size().
void ExtColVector::setLower (double p_low) [inline]
access lower bound.
Definition at line 110 of file ExtColVector.h.
References m_low.
void ExtColVector::setName (std::string p_name) [inline]
access the name of the LP Column
Definition at line 105 of file ExtColVector.h.
References m_name.
void ExtColVector::setObj (double p_object) [inline]
access objective value.
Definition at line 68 of file ExtColVector.h.
References m_object.
void ExtColVector::setUpper (double p_up) [inline]
access upper bound.
Definition at line 77 of file ExtColVector.h.
References m_up.
void ExtColVector::storeFromPackedVector (PackedVector & packedVector) [inline]
Definition at line 48 of file ExtColVector.h.
References m_vctPacked.
double ExtColVector::upper () const [inline]
get upper bound.
Definition at line 73 of file ExtColVector.h.
References m_up.
Member Data Documentation
double ExtColVector::m_low [private]
lower bound
Definition at line 20 of file ExtColVector.h.
Referenced by lower(), and setLower().
std::string ExtColVector::m_name [private]
column vector - packed version
Definition at line 23 of file ExtColVector.h.
Referenced by getName(), and setName().
double ExtColVector::m_object [private]
objective value
Definition at line 21 of file ExtColVector.h.
Referenced by obj(), and setObj().
double ExtColVector::m_up [private]
upper bound
Definition at line 19 of file ExtColVector.h.
Referenced by setUpper(), and upper().
ExtPackedVector* ExtColVector::m_vctPacked [private]
Definition at line 22 of file ExtColVector.h.
Referenced by allocate_cache(), begin(), deallocate_cache(), deallocatePackedVector(), end(), ExtColVector(), get_nnz(), get_sparsity(), getRowElement(), real_size(), and storeFromPackedVector().
The documentation for this class was generated from the following file:
local/deprecated/ExtColVector.h