ExtLP: PackedRowVector Class Reference
PackedRowVector Class Reference
Detailed Description
PackedRowVector: Meant to store the row of the LP Tableau Only meant for keeping track of REAL values pertaining to the LP Column.
Definition at line 14 of file PackedRowVector.h.
Public Types
enum Type { LESS_EQUAL, EQUAL, GREATER_EQUAL, RANGE }
Public Member Functions
PackedRowVector ()
Initialization.
double get_lhs () const
std::string get_name () const
double get_rhs () const
int get_row_type ()
TODO - Return proper row type as per the Matrix A Integer identifier for the row type 0 Equals; 1 greater than Equals; 2 Less than Equals 3 Less than; 4 Greater ; 5 Range.
Type get_type () const
double get_value () const
void set_lhs (double p_left)
void set_name (std::string p_name)
void set_rhs (double p_right)
void set_type (Type p_type)
Private Attributes
double m_lhs_value
std::string m_name
double m_rhs_value
Member Enumeration Documentation
enum PackedRowVector::Type
Enumerator:
LESS_EQUAL
EQUAL
GREATER_EQUAL
RANGE
Definition at line 20 of file PackedRowVector.h.
Constructor & Destructor Documentation
PackedRowVector::PackedRowVector () [inline, explicit]
Initialization.
Definition at line 28 of file PackedRowVector.h.
Member Function Documentation
double PackedRowVector::get_lhs () const [inline]
Definition at line 82 of file PackedRowVector.h.
References m_lhs_value.
Referenced by ExtMatrixA::add_row(), get_type(), get_value(), and set_type().
std::string PackedRowVector::get_name () const [inline]
Definition at line 85 of file PackedRowVector.h.
References m_name.
Referenced by ExtMatrixA::add_row().
double PackedRowVector::get_rhs () const [inline]
Definition at line 94 of file PackedRowVector.h.
References m_rhs_value.
Referenced by ExtMatrixA::add_row(), get_type(), get_value(), and set_type().
int PackedRowVector::get_row_type () [inline]
TODO - Return proper row type as per the Matrix A Integer identifier for the row type 0 Equals; 1 greater than Equals; 2 Less than Equals 3 Less than; 4 Greater ; 5 Range.
Used in ExtMatrixA to externally store row attributes.
Definition at line 36 of file PackedRowVector.h.
References EQUAL, get_type(), GREATER_EQUAL, LESS_EQUAL, and RANGE.
Referenced by ExtMatrixA::add_row().
Type PackedRowVector::get_type () const [inline]
Definition at line 46 of file PackedRowVector.h.
References EQUAL, get_lhs(), get_rhs(), GREATER_EQUAL, INFINITY_VALUE, LESS_EQUAL, and RANGE.
Referenced by get_row_type(), and get_value().
double PackedRowVector::get_value () const [inline]
Definition at line 78 of file PackedRowVector.h.
References get_lhs(), get_rhs(), get_type(), INFINITY_VALUE, and RANGE.
void PackedRowVector::set_lhs (double p_left) [inline]
Definition at line 91 of file PackedRowVector.h.
References m_lhs_value.
Referenced by ExtReadMPSUtil::readRows().
void PackedRowVector::set_name (std::string p_name) [inline]
Definition at line 88 of file PackedRowVector.h.
References m_name.
Referenced by ExtReadMPSUtil::readRows().
void PackedRowVector::set_rhs (double p_right) [inline]
Definition at line 97 of file PackedRowVector.h.
References m_rhs_value.
Referenced by ExtReadMPSUtil::readRows().
void PackedRowVector::set_type (Type p_type) [inline]
Definition at line 55 of file PackedRowVector.h.
References DEBUG_ERROR, EQUAL, get_lhs(), get_rhs(), GREATER_EQUAL, INFINITY_VALUE, LESS_EQUAL, m_lhs_value, m_rhs_value, and RANGE.
Member Data Documentation
double PackedRowVector::m_lhs_value [private]
Definition at line 16 of file PackedRowVector.h.
Referenced by get_lhs(), set_lhs(), and set_type().
std::string PackedRowVector::m_name [private]
Definition at line 18 of file PackedRowVector.h.
Referenced by get_name(), and set_name().
double PackedRowVector::m_rhs_value [private]
Definition at line 17 of file PackedRowVector.h.
Referenced by get_rhs(), set_rhs(), and set_type().
The documentation for this class was generated from the following file:
local/PackedRowVector.h