ExtLP: ReadMPSUtil Class Reference
ReadMPSUtil Class Reference
Detailed Description
Definition at line 15 of file ReadMPSUtil.h.
Public Member Functions
bool readMPS (std::istream &is)
Static Public Member Functions
static void readCols (MPSInput &mps, std::vector< LPRow > &arrRow, std::map< std::string, int > &mapRowNumber, std::vector< LPCol > &arrCol, std::map< std::string, int > &mapColNumber)
Process COLUMNS section.
static void readName (MPSInput &mps)
Process NAME section.
static void readObjname (MPSInput &mps)
Process OBJNAME section. This Section is an ILOG extension.
static void readObjsen (MPSInput &mps)
Process OBJSEN section. This Section is an ILOG extension.
static void readRhs (MPSInput &mps, std::vector< LPRow > &arrRow, std::map< std::string, int > &mapRowNumber)
Process RHS section.
static void readRows (MPSInput &mps, std::vector< LPRow > &arrRow, std::map< std::string, int > &mapRowNumber)
Process ROWS section.
Member Function Documentation
static void ReadMPSUtil::readCols (MPSInput & mps, std::vector< LPRow > & arrRow, std::map< std::string, int > & mapRowNumber, std::vector< LPCol > & arrCol, std::map< std::string, int > & mapColNumber) [inline, static]
Process COLUMNS section.
Definition at line 171 of file ReadMPSUtil.h.
References DEBUG_PARSER, MPSInput::entryIgnored(), MPSInput::field0(), MPSInput::field1(), MPSInput::field2(), MPSInput::field3(), MPSInput::field4(), MPSInput::field5(), INFINITY_VALUE, MPSInput::MAX_LINE_LEN, MPSInput::objName(), MPSInput::readLine(), REAL, MPSInput::RHS, LPCol::setObj(), MPSInput::setSection(), and MPSInput::syntaxError().
Referenced by readMPS().
bool ReadMPSUtil::readMPS (std::istream & is) [inline]
Debugging the logic and results /////////////////////////////////////////////////////////////
Rhs Column in objective constraint
Definition at line 381 of file ReadMPSUtil.h.
References MPSInput::COLUMNS, DEBUG_PARSER, DEBUG_SIMPLE, MPSInput::OBJNAME, MPSInput::objName(), MPSInput::OBJSEN, MPSInput::probName(), readCols(), readName(), readObjname(), readObjsen(), readRhs(), readRows(), MPSInput::RHS, MPSInput::rhsName(), MPSInput::ROWS, and MPSInput::section().
Referenced by ReadFileUtil::readFile().
static void ReadMPSUtil::readName (MPSInput & mps) [inline, static]
Process NAME section.
Definition at line 18 of file ReadMPSUtil.h.
References MPSInput::field0(), MPSInput::field1(), MPSInput::OBJNAME, MPSInput::OBJSEN, MPSInput::readLine(), MPSInput::ROWS, MPSInput::setProbName(), MPSInput::setSection(), and MPSInput::syntaxError().
Referenced by readMPS().
static void ReadMPSUtil::readObjname (MPSInput & mps) [inline, static]
Process OBJNAME section. This Section is an ILOG extension.
Definition at line 86 of file ReadMPSUtil.h.
References MPSInput::field0(), MPSInput::field1(), MPSInput::readLine(), MPSInput::ROWS, MPSInput::setObjName(), MPSInput::setSection(), and MPSInput::syntaxError().
Referenced by readMPS().
static void ReadMPSUtil::readObjsen (MPSInput & mps) [inline, static]
Process OBJSEN section. This Section is an ILOG extension.
Definition at line 55 of file ReadMPSUtil.h.
References MPSInput::field0(), MPSInput::field1(), MPSInput::OBJNAME, MPSInput::readLine(), MPSInput::ROWS, MPSInput::setObjSense(), MPSInput::setSection(), and MPSInput::syntaxError().
Referenced by readMPS().
static void ReadMPSUtil::readRhs (MPSInput & mps, std::vector< LPRow > & arrRow, std::map< std::string, int > & mapRowNumber) [inline, static]
Process RHS section.
Definition at line 292 of file ReadMPSUtil.h.
References MPSInput::BOUNDS, DEBUG_PARSER, MPSInput::ENDATA, MPSInput::entryIgnored(), MPSInput::field0(), MPSInput::field1(), MPSInput::field2(), MPSInput::field3(), MPSInput::field4(), MPSInput::field5(), INFINITY_VALUE, MPSInput::insertName(), MPSInput::MAX_LINE_LEN, MPSInput::RANGES, MPSInput::readLine(), REAL, MPSInput::setRhsName(), MPSInput::setSection(), and MPSInput::syntaxError().
Referenced by readMPS().
static void ReadMPSUtil::readRows (MPSInput & mps, std::vector< LPRow > & arrRow, std::map< std::string, int > & mapRowNumber) [inline, static]
Process ROWS section.
Definition at line 109 of file ReadMPSUtil.h.
References MPSInput::COLUMNS, MPSInput::field0(), MPSInput::field1(), MPSInput::field2(), INFINITY_VALUE, MPSInput::objName(), MPSInput::readLine(), LPRow::setLhs(), LPRow::setName(), MPSInput::setObjName(), LPRow::setRhs(), MPSInput::setSection(), and MPSInput::syntaxError().
Referenced by readMPS().
The documentation for this class was generated from the following file:
local/deprecated/ReadMPSUtil.h