ExtLP: local/extlp.cpp File Reference
local/extlp.cpp File Reference
#include "ReadFileUtil.h"
#include "ExtNameMap.h"
#include "Test.h"
#include "Console.h"
#include "ExtSimplex.h"
Functions
unsigned int get_expected_io_currently (ExtLPDSSet &extDataSet)
unsigned int get_expected_read_io_currently ()
unsigned int get_expected_write_io_currently (ExtLPDSSet &extDataSet)
int main (int argc, char *argv[])
void print_io_statistics (stxxl::stats_data diff_data, ExtLPDSSet &extDataSet, unsigned int expected_read_io, unsigned int expected_write_io, bool print_header=false)
[example]
Function Documentation
unsigned int get_expected_io_currently (ExtLPDSSet & extDataSet)
Definition at line 66 of file extlp.cpp.
References ExtLPDSSet::A, ExtMatrixA::get_element_size(), ExtMatrixA::get_overall_nnz(), and MATRIX_A_BLOCK_SIZE.
unsigned int get_expected_read_io_currently ()
Definition at line 71 of file extlp.cpp.
Referenced by main().
unsigned int get_expected_write_io_currently (ExtLPDSSet & extDataSet)
Definition at line 75 of file extlp.cpp.
References ExtLPDSSet::A, ExtMatrixA::get_element_size(), ExtMatrixA::get_overall_nnz(), and MATRIX_A_BLOCK_SIZE.
Referenced by main().
int main (int argc, char * argv[])
Examples:
examples/algo/copy_and_sort_file.cpp, examples/algo/phonebills.cpp, examples/algo/phonebills_genlog.cpp, examples/algo/sort_file.cpp, examples/applications/skew3.cpp, examples/common/cmdline.cpp, examples/containers/copy_file.cpp, examples/containers/deque1.cpp, examples/containers/deque2.cpp, examples/containers/map1.cpp, examples/containers/matrix1.cpp, examples/containers/pqueue1.cpp, examples/containers/pqueue2.cpp, examples/containers/queue1.cpp, examples/containers/queue2.cpp, examples/containers/sequence1.cpp, examples/containers/sorter1.cpp, examples/containers/sorter2.cpp, examples/containers/stack1.cpp, examples/containers/stack2.cpp, examples/containers/vector1.cpp, examples/containers/vector2.cpp, examples/containers/vector_buf.cpp, and examples/stream/stream1.cpp.
Definition at line 80 of file extlp.cpp.
References CONSOLE_PRINT, CONSOLE_PRINTLN, DATA_LEAF_CACHE_COUNT, DATA_NODE_CACHE_COUNT, DEBUG_MEMORY, DEBUG_SIMPLE, get_expected_read_io_currently(), get_expected_write_io_currently(), print_io_statistics(), Console::printUsage(), Console::printVersionInfo(), ReadFileUtil::readFileUsingDisk(), and ExtSimplex::solve().
void print_io_statistics (stxxl::stats_data diff_data, ExtLPDSSet & extDataSet, unsigned int expected_read_io, unsigned int expected_write_io, bool print_header = false)
[example]
Definition at line 35 of file extlp.cpp.
References ExtLPDSSet::A, CONSOLE_PRINTLN, ExtMatrixA::get_overall_density(), and ExtMatrixA::get_overall_nnz().
Referenced by main().